using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FTAnalyzer.Mapping
{
    public class CountyConversion
    {
        public static readonly Dictionary<Region, List<County>> CONVERSIONS = new Dictionary<Region, List<County>>();
        public static readonly List<County> MODERN_COUNTIES;

        public class County
        {
            public string CountyCode { get; private set; }
            public string CountyName { get; private set; }

            public County(string code, string countyName)
            {
                CountyCode = code;
                CountyName = countyName;
            }

            public override string ToString()
            {
                return CountyCode + ": " + CountyName;
            }
        }

        public static List<County> GetCounties(Region lookup)
        {
            if (CONVERSIONS.ContainsKey(lookup))
                return CONVERSIONS[lookup];
            return new List<County>();
        }

        public static County OS_GetCounty(string code)
        {
            return MODERN_COUNTIES.First(c => c.CountyCode.Equals(code));
        }

        #region Modern County List
        public static County OS_ABERDEENSHIRE = new County("AB", "Aberdeenshire");
        public static County OS_ANGUS = new County("AG", "Angus");
        public static County OS_ABERDEEN_CITY = new County("AN", "Aberdeen City");
        public static County OS_ARGYLL_AND_BUTE = new County("AR", "Argyll and Bute");
        public static County OS_BRADFORD = new County("BA", "Bradford");
        public static County OS_BLACKBURN_WITH_DARWEN = new County("BB", "Blackburn with Darwen");
        public static County OS_BRACKNELL_FOREST = new County("BC", "Bracknell Forest");
        public static County OS_BARKING_AND_DAGENHAM = new County("BD", "Barking and Dagenham");
        public static County OS_BRIDGEND = new County("BE", "Bridgend");
        public static County OS_BEDFORDSHIRE = new County("BF", "Bedfordshire");
        public static County OS_BLAENAU_GWENT = new County("BG", "Blaenau Gwent");
        public static County OS_CITY_OF_BRIGHTON_AND_HOVE = new County("BH", "City of Brighton and Hove");
        public static County OS_BIRMINGHAM = new County("BI", "Birmingham");
        public static County OS_CENTRAL_BEDFORDSHIRE = new County("BK", "Central Bedfordshire"); // extra to gazetteer index
        public static County OS_BARNSLEY = new County("BL", "Barnsley");
        public static County OS_BUCKINGHAMSHIRE = new County("BM", "Buckinghamshire");
        public static County OS_BARNET = new County("BN", "Barnet");
        public static County OS_BOLTON = new County("BO", "Bolton");
        public static County OS_BLACKPOOL = new County("BP", "Blackpool");
        public static County OS_BROMLEY = new County("BR", "Bromley");
        public static County OS_BATH_AND_NORTH_EAST_SOMERSET = new County("BS", "Bath and North East Somerset");
        public static County OS_BRENT = new County("BT", "Brent");
        public static County OS_BOURNEMOUTH = new County("BU", "Bournemouth");
        public static County OS_BEXLEY = new County("BX", "Bexley");
        public static County OS_BURY = new County("BY", "Bury");
        public static County OS_BRISTOL = new County("BZ", "City of Bristol");
        public static County OS_CALDERDALE = new County("CA", "Calderdale");
        public static County OS_CAMBRIDGESHIRE = new County("CB", "Cambridgeshire");
        public static County OS_CARDIFF = new County("CD", "Cardiff");
        public static County OS_CEREDIGION = new County("CE", "Ceredigion");
        public static County OS_CAERPHILLY = new County("CF", "Caerphilly");
        public static County OS_CHESHIRE_EAST = new County("CH", "Cheshire East");
        public static County OS_CHESHIRE_WEST_AND_CHESTER = new County("CC", "Cheshire West and Chester");
        public static County OS_CLACKMANNANSHIRE = new County("CL", "Clackmannanshire");
        public static County OS_CAMDEN = new County("CM", "Camden");
        public static County OS_CORNWALL = new County("CN", "Cornwall");
        public static County OS_CARMARTHENSHIRE = new County("CT", "Carmarthenshire");
        public static County OS_CUMBRIA = new County("CU", "Cumbria");
        public static County OS_COVENTRY = new County("CV", "Coventry");
        public static County OS_CONWY = new County("CW", "Conwy");
        public static County OS_CROYDON = new County("CY", "Croydon");
        public static County OS_CITY_OF_DERBY = new County("DB", "City of Derby");
        public static County OS_DUNDEE_CITY = new County("DD", "Dundee City");
        public static County OS_DENBIGHSHIRE = new County("DE", "Denbighshire");
        public static County OS_DUMFRIES_AND_GALLOWAY = new County("DG", "Dumfries and Galloway");
        public static County OS_DARLINGTON = new County("DL", "Darlington");
        public static County OS_DEVON = new County("DN", "Devon");
        public static County OS_DONCASTER = new County("DR", "Doncaster");
        public static County OS_DORSET = new County("DT", "Dorset");
        public static County OS_DURHAM = new County("DU", "Durham");
        public static County OS_DERBYSHIRE = new County("DY", "Derbyshire");
        public static County OS_DUDLEY = new County("DZ", "Dudley");
        public static County OS_EAST_AYRSHIRE = new County("EA", "East Ayrshire");
        public static County OS_CITY_OF_EDINBURGH = new County("EB", "City of Edinburgh");
        public static County OS_EAST_DUNBARTONSHIRE = new County("ED", "East Dunbartonshire");
        public static County OS_EALING = new County("EG", "Ealing");
        public static County OS_EAST_LOTHIAN = new County("EL", "East Lothian");
        public static County OS_ENFIELD = new County("EN", "Enfield");
        public static County OS_EAST_RENFREWSHIRE = new County("ER", "East Renfrewshire");
        public static County OS_EAST_SUSSEX = new County("ES", "East Sussex");
        public static County OS_ESSEX = new County("EX", "Essex");
        public static County OS_EAST_RIDING_OF_YORKSHIRE = new County("EY", "East Riding of Yorkshire");
        public static County OS_FALKIRK = new County("FA", "Falkirk");
        public static County OS_FIFE = new County("FF", "Fife");
        public static County OS_FLINTSHIRE = new County("FL", "Flintshire");
        public static County OS_GATESHEAD = new County("GH", "Gateshead");
        public static County OS_GLASGOW_CITY = new County("GL", "Glasgow City");
        public static County OS_GLOUCESTERSHIRE = new County("GR", "Gloucestershire");
        public static County OS_GREENWICH = new County("GW", "Greenwich");
        public static County OS_GWYNEDD = new County("GY", "Gwynedd");
        public static County OS_HALTON = new County("HA", "Halton");
        public static County OS_HERTFORDSHIRE = new County("HD", "Hertfordshire");
        public static County OS_HEREFORDSHIRE = new County("HE", "Herefordshire");
        public static County OS_HAMMERSMITH_AND_FULHAM = new County("HF", "Hammersmith and Fulham");
        public static County OS_HARINGEY = new County("HG", "Haringey");
        public static County OS_HILLINGDON = new County("HI", "Hillingdon");
        public static County OS_HIGHLAND = new County("HL", "Highland");
        public static County OS_HACKNEY = new County("HN", "Hackney");
        public static County OS_HAMPSHIRE = new County("HP", "Hampshire");
        public static County OS_HARROW = new County("HR", "Harrow");
        public static County OS_HOUNSLOW = new County("HS", "Hounslow");
        public static County OS_HARTLEPOOL = new County("HT", "Hartlepool");
        public static County OS_HAVERING = new County("HV", "Havering");
        public static County OS_ISLE_OF_ANGLESEY = new County("IA", "Isle of Anglesey");
        public static County OS_ISLINGTON = new County("IL", "Islington");
        public static County OS_ISLE_OF_MAN = new County("IM", "Isle of Man");
        public static County OS_INVERCLYDE = new County("IN", "Inverclyde");
        public static County OS_ISLES_OF_SCILLY = new County("IS", "Isles of Scilly");
        public static County OS_CITY_OF_INVERNESS = new County("IV", "City of Inverness");
        public static County OS_ISLE_OF_WIGHT = new County("IW", "Isle of Wight");
        public static County OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA = new County("KC", "Royal Borough of Kensington and Chelsea");
        public static County OS_KINGSTON_UPON_THAMES = new County("KG", "Kingston upon Thames");
        public static County OS_CITY_OF_KINGSTON_UPON_HULL = new County("KH", "City of Kingston upon Hull");
        public static County OS_KIRKLEES = new County("KL", "Kirklees");
        public static County OS_KNOWSLEY = new County("KN", "Knowsley");
        public static County OS_KENT = new County("KT", "Kent");
        public static County OS_LANCASHIRE = new County("LA", "Lancashire");
        public static County OS_LAMBETH = new County("LB", "Lambeth");
        public static County OS_CITY_OF_LEICESTER = new County("LC", "City of Leicester");
        public static County OS_LEEDS = new County("LD", "Leeds");
        public static County OS_LINCOLNSHIRE = new County("LL", "Lincolnshire");
        public static County OS_LUTON = new County("LN", "Luton");
        public static County OS_CITY_OF_LONDON = new County("LO", "City of London");
        public static County OS_LIVERPOOL = new County("LP", "Liverpool");
        public static County OS_LEWISHAM = new County("LS", "Lewisham");
        public static County OS_LEICESTERSHIRE = new County("LT", "Leicestershire");
        public static County OS_MANCHESTER = new County("MA", "Manchester");
        public static County OS_MIDDLESBROUGH = new County("MB", "Middlesbrough");
        public static County OS_MEDWAY = new County("ME", "Medway");
        public static County OS_MIDLOTHIAN = new County("MI", "Midlothian");
        public static County OS_MILTON_KEYNES = new County("MK", "Milton Keynes");
        public static County OS_MONMOUTHSHIRE = new County("MM", "Monmouthshire");
        public static County OS_MORAY = new County("MO", "Moray");
        public static County OS_MERTON = new County("MR", "Merton");
        public static County OS_MERTHYR_TYDFIL = new County("MT", "Merthyr Tydfil");
        public static County OS_NORTH_AYRSHIRE = new County("NA", "North Ayrshire");
        public static County OS_NORTH_EAST_LINCOLNSHIRE = new County("NC", "North East Lincolnshire");
        public static County OS_NORTHUMBERLAND = new County("ND", "Northumberland");
        public static County OS_NEWPORT = new County("NE", "Newport");
        public static County OS_CITY_OF_NOTTINGHAM = new County("NG", "City of Nottingham");
        public static County OS_NEWHAM = new County("NH", "Newham");
        public static County OS_NORTH_LINCOLNSHIRE = new County("NI", "North Lincolnshire");
        public static County OS_NORFOLK = new County("NK", "Norfolk");
        public static County OS_NORTH_LANARKSHIRE = new County("NL", "North Lanarkshire");
        public static County OS_NORTHAMPTONSHIRE = new County("NN", "Northamptonshire");
        public static County OS_NEATH_PORT_TALBOT = new County("NP", "Neath Port Talbot");
        public static County OS_NORTH_TYNESIDE = new County("NR", "North Tyneside");
        public static County OS_NORTH_SOMERSET = new County("NS", "North Somerset");
        public static County OS_NOTTINGHAMSHIRE = new County("NT", "Nottinghamshire");
        public static County OS_NEWCASTLE_UPON_TYNE = new County("NW", "Newcastle upon Tyne");
        public static County OS_NORTH_YORKSHIRE = new County("NY", "North Yorkshire");
        public static County OS_OLDHAM = new County("OH", "Oldham");
        public static County OS_ORKNEY_ISLANDS = new County("OK", "Orkney Islands");
        public static County OS_OXFORDSHIRE = new County("ON", "Oxfordshire");
        public static County OS_PEMBROKESHIRE = new County("PB", "Pembrokeshire");
        public static County OS_CITY_OF_PETERBOROUGH = new County("PE", "City of Peterborough");
        public static County OS_PERTH_AND_KINROSS = new County("PK", "Perth and Kinross");
        public static County OS_POOLE = new County("PL", "Poole");
        public static County OS_CITY_OF_PORTSMOUTH = new County("PO", "City of Portsmouth");
        public static County OS_POWYS = new County("PW", "Powys");
        public static County OS_CITY_OF_PLYMOUTH = new County("PY", "City of Plymouth");
        public static County OS_REDBRIDGE = new County("RB", "Redbridge");
        public static County OS_REDCAR_AND_CLEVELAND = new County("RC", "Redcar and Cleveland");
        public static County OS_ROCHDALE = new County("RD", "Rochdale");
        public static County OS_RENFREWSHIRE = new County("RE", "Renfrewshire");
        public static County OS_READING = new County("RG", "Reading");
        public static County OS_RHONDDA_CYNON_TAFF = new County("RH", "Rhondda Cynon Taff");
        public static County OS_RUTLAND = new County("RL", "Rutland");
        public static County OS_ROTHERHAM = new County("RO", "Rotherham");
        public static County OS_RICHMOND_UPON_THAMES = new County("RT", "Richmond upon Thames");
        public static County OS_SANDWELL = new County("SA", "Sandwell");
        public static County OS_SCOTTISH_BORDERS = new County("SB", "Scottish Borders");
        public static County OS_SALFORD = new County("SC", "Salford");
        public static County OS_SWINDON = new County("SD", "Swindon");
        public static County OS_SEFTON = new County("SE", "Sefton");
        public static County OS_STAFFORDSHIRE = new County("SF", "Staffordshire");
        public static County OS_SOUTH_GLOUCESTERSHIRE = new County("SG", "South Gloucestershire");
        public static County OS_SHROPSHIRE = new County("SH", "Shropshire");
        public static County OS_SHETLAND_ISLANDS = new County("SI", "Shetland Islands");
        public static County OS_CITY_OF_STOKE_ON_TRENT = new County("SJ", "City of Stoke-on-Trent");
        public static County OS_SUFFOLK = new County("SK", "Suffolk");
        public static County OS_SOUTH_LANARKSHIRE = new County("SL", "South Lanarkshire");
        public static County OS_STOCKTON_ON_TEES = new County("SM", "Stockton-on-Tees");
        public static County OS_ST_HELENS = new County("SN", "St Helens");
        public static County OS_CITY_OF_SOUTHAMPTON = new County("SO", "City of Southampton");
        public static County OS_SHEFFIELD = new County("SP", "Sheffield");
        public static County OS_SOLIHULL = new County("SQ", "Solihull");
        public static County OS_STIRLING = new County("SR", "Stirling");
        public static County OS_SWANSEA = new County("SS", "Swansea");
        public static County OS_SOMERSET = new County("ST", "Somerset");
        public static County OS_SURREY = new County("SU", "Surrey");
        public static County OS_SUNDERLAND = new County("SV", "Sunderland");
        public static County OS_SOUTHWARK = new County("SW", "Southwark");
        public static County OS_SOUTH_AYRSHIRE = new County("SX", "South Ayrshire");
        public static County OS_SOUTH_TYNESIDE = new County("SY", "South Tyneside");
        public static County OS_SUTTON = new County("SZ", "Sutton");
        public static County OS_TORBAY = new County("TB", "Torbay");
        public static County OS_TORFAEN = new County("TF", "Torfaen");
        public static County OS_TOWER_HAMLETS = new County("TH", "Tower Hamlets");
        public static County OS_TRAFFORD = new County("TR", "Trafford");
        public static County OS_TAMESIDE = new County("TS", "Tameside");
        public static County OS_THURROCK = new County("TU", "Thurrock");
        public static County OS_VALE_OF_GLAMORGAN = new County("VG", "Vale of Glamorgan");
        public static County OS_WALSALL = new County("WA", "Walsall");
        public static County OS_WEST_BERKSHIRE = new County("WB", "West Berkshire");
        public static County OS_WINDSOR_AND_MAIDENHEAD = new County("WC", "Windsor and Maidenhead");
        public static County OS_WEST_DUNBARTONSHIRE = new County("WD", "West Dunbartonshire");
        public static County OS_WAKEFIELD = new County("WE", "Wakefield");
        public static County OS_WALTHAM_FOREST = new County("WF", "Waltham Forest");
        public static County OS_WARRINGTON = new County("WG", "Warrington");
        public static County OS_CITY_OF_WOLVERHAMPTON = new County("WH", "City of Wolverhampton");
        public static County OS_WESTERN_ISLES = new County("WI", "Na h-Eileanan an Iar");
        public static County OS_WOKINGHAM = new County("WJ", "Wokingham");
        public static County OS_WARWICKSHIRE = new County("WK", "Warwickshire");
        public static County OS_WEST_LOTHIAN = new County("WL", "West Lothian");
        public static County OS_CITY_OF_WESTMINSTER = new County("WM", "City of Westminster");
        public static County OS_WIGAN = new County("WN", "Wigan");
        public static County OS_WORCESTERSHIRE = new County("WO", "Worcestershire");
        public static County OS_TELFORD_AND_WREKIN = new County("WP", "Telford and Wrekin");
        public static County OS_WIRRAL = new County("WR", "Wirral");
        public static County OS_WEST_SUSSEX = new County("WS", "West Sussex");
        public static County OS_WILTSHIRE = new County("WT", "Wiltshire");
        public static County OS_WANDSWORTH = new County("WW", "Wandsworth");
        public static County OS_WREXHAM = new County("WX", "Wrexham");
        public static County OS_YORK = new County("YK", "York");
        public static County OS_SOUTHEND_ON_SEA = new County("YS", "Southend-on-Sea");
        public static County OS_SLOUGH = new County("YT", "Slough");
        public static County OS_STOCKPORT = new County("YY", "Stockport");
        #endregion

        static CountyConversion()
        {
            MODERN_COUNTIES = new List<County>(new County[] { 
                OS_ABERDEEN_CITY, OS_ANGUS, OS_ABERDEENSHIRE, OS_ARGYLL_AND_BUTE, OS_BRADFORD, OS_BLACKBURN_WITH_DARWEN,
                OS_BRACKNELL_FOREST, OS_BARKING_AND_DAGENHAM, OS_BRIDGEND, OS_BEDFORDSHIRE, OS_BLAENAU_GWENT, 
                OS_CITY_OF_BRIGHTON_AND_HOVE, OS_BIRMINGHAM, OS_CENTRAL_BEDFORDSHIRE, OS_BARNSLEY, OS_BUCKINGHAMSHIRE,
                OS_BARNET, OS_BOLTON, OS_BLACKPOOL, OS_BROMLEY, OS_BATH_AND_NORTH_EAST_SOMERSET, OS_BRENT, OS_BOURNEMOUTH,
                OS_BEXLEY, OS_BURY, OS_BRISTOL, OS_CALDERDALE, OS_CAMBRIDGESHIRE, OS_CARDIFF, OS_CEREDIGION, OS_CAERPHILLY, 
                OS_CHESHIRE_EAST, OS_CHESHIRE_WEST_AND_CHESTER, OS_CLACKMANNANSHIRE, OS_CAMDEN, OS_CORNWALL, 
                OS_CARMARTHENSHIRE, OS_CUMBRIA, OS_COVENTRY, OS_CONWY, OS_CROYDON, OS_CITY_OF_DERBY, OS_DUNDEE_CITY, OS_DENBIGHSHIRE,
                OS_DUMFRIES_AND_GALLOWAY, OS_DARLINGTON, OS_DEVON, OS_DONCASTER, OS_DORSET, OS_DURHAM, OS_DERBYSHIRE, OS_EAST_AYRSHIRE,
                OS_CITY_OF_EDINBURGH, OS_EAST_DUNBARTONSHIRE, OS_EALING, OS_EAST_LOTHIAN, OS_ENFIELD, OS_EAST_RENFREWSHIRE, 
                OS_EAST_SUSSEX, OS_ESSEX, OS_EAST_RIDING_OF_YORKSHIRE, OS_FALKIRK, OS_FIFE, OS_FLINTSHIRE, OS_GATESHEAD, 
                OS_GLASGOW_CITY, OS_GLOUCESTERSHIRE, OS_GREENWICH, OS_GWYNEDD, OS_HALTON, OS_HERTFORDSHIRE, OS_HEREFORDSHIRE,
                OS_HAMMERSMITH_AND_FULHAM, OS_HARINGEY, OS_HILLINGDON, OS_HIGHLAND, OS_HACKNEY, OS_HAMPSHIRE, OS_HARROW,
                OS_HOUNSLOW, OS_HARTLEPOOL, OS_HAVERING, OS_ISLE_OF_ANGLESEY, OS_ISLINGTON, OS_ISLE_OF_MAN, OS_INVERCLYDE,
                OS_ISLES_OF_SCILLY, OS_CITY_OF_INVERNESS, OS_ISLE_OF_WIGHT, OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA,
                OS_KINGSTON_UPON_THAMES, OS_CITY_OF_KINGSTON_UPON_HULL, OS_KIRKLEES, OS_KNOWSLEY, OS_KENT, OS_LANCASHIRE,
                OS_LAMBETH, OS_CITY_OF_LEICESTER, OS_LEEDS, OS_LINCOLNSHIRE, OS_LUTON, OS_CITY_OF_LONDON, OS_LIVERPOOL, 
                OS_LEWISHAM, OS_LEICESTERSHIRE, OS_MANCHESTER, OS_MIDDLESBROUGH, OS_MEDWAY, OS_MIDLOTHIAN, OS_MILTON_KEYNES,
                OS_MONMOUTHSHIRE
        });
            //bool ignore = Regions.IsKnownRegion("Aberdeenshire"); // forced Regions static class to load.
            AddConversion(Regions.CAITHNESS, OS_HIGHLAND);
            AddConversion(Regions.SUTHERLAND, OS_HIGHLAND);
            AddConversion(Regions.ROSS_CROMARTY, OS_HIGHLAND);
            AddConversion(Regions.ROSS_CROMARTY, OS_WESTERN_ISLES);
            AddConversion(Regions.INVERNESS, OS_HIGHLAND);
            AddConversion(Regions.INVERNESS, OS_ABERDEENSHIRE);
            AddConversion(Regions.INVERNESS, OS_MORAY);
            AddConversion(Regions.INVERNESS, OS_ARGYLL_AND_BUTE);
            AddConversion(Regions.INVERNESS, OS_WESTERN_ISLES);
            AddConversion(Regions.NAIRN, OS_HIGHLAND);
            AddConversion(Regions.NAIRN, OS_MORAY);
            AddConversion(Regions.MORAY, OS_MORAY);
            AddConversion(Regions.MORAY, OS_ABERDEENSHIRE);
            AddConversion(Regions.MORAY, OS_HIGHLAND);
            AddConversion(Regions.BANFF, OS_MORAY);
            AddConversion(Regions.BANFF, OS_ABERDEENSHIRE);
            AddConversion(Regions.ABERDEEN, OS_ABERDEEN_CITY);
            AddConversion(Regions.ABERDEEN, OS_ABERDEENSHIRE);
            AddConversion(Regions.ABERDEEN, OS_MORAY);
            AddConversion(Regions.KINCARDINE, OS_ABERDEENSHIRE);
            AddConversion(Regions.KINCARDINE, OS_ABERDEEN_CITY);
            AddConversion(Regions.KINCARDINE, OS_ANGUS);
            AddConversion(Regions.ANGUS, OS_ANGUS);
            AddConversion(Regions.ANGUS, OS_ABERDEENSHIRE);
            AddConversion(Regions.ANGUS, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.ANGUS, OS_DUNDEE_CITY);
            AddConversion(Regions.PERTH, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.PERTH, OS_STIRLING);
            AddConversion(Regions.PERTH, OS_CLACKMANNANSHIRE);
            AddConversion(Regions.PERTH, OS_FIFE);
            AddConversion(Regions.PERTH, OS_ANGUS);
            AddConversion(Regions.PERTH, OS_DUNDEE_CITY);
            AddConversion(Regions.ARGYLL, OS_ARGYLL_AND_BUTE);
            AddConversion(Regions.ARGYLL, OS_HIGHLAND);
            AddConversion(Regions.ARGYLL, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.ARGYLL, OS_STIRLING);
            AddConversion(Regions.BUTE, OS_ARGYLL_AND_BUTE);
            AddConversion(Regions.BUTE, OS_NORTH_AYRSHIRE);
            AddConversion(Regions.AYR, OS_EAST_AYRSHIRE);
            AddConversion(Regions.AYR, OS_NORTH_AYRSHIRE);
            AddConversion(Regions.AYR, OS_SOUTH_AYRSHIRE);
            AddConversion(Regions.RENFREW, OS_GLASGOW_CITY);
            AddConversion(Regions.RENFREW, OS_INVERCLYDE);
            AddConversion(Regions.RENFREW, OS_RENFREWSHIRE);
            AddConversion(Regions.RENFREW, OS_EAST_RENFREWSHIRE);
            AddConversion(Regions.DUNBARTON, OS_EAST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, OS_WEST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, OS_GLASGOW_CITY);
            AddConversion(Regions.DUNBARTON, OS_NORTH_LANARKSHIRE);
            AddConversion(Regions.DUNBARTON, OS_STIRLING);
            AddConversion(Regions.STIRLING, OS_STIRLING);
            AddConversion(Regions.STIRLING, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.STIRLING, OS_EAST_DUNBARTONSHIRE);
            AddConversion(Regions.STIRLING, OS_NORTH_LANARKSHIRE);
            AddConversion(Regions.STIRLING, OS_FALKIRK);
            AddConversion(Regions.STIRLING, OS_CLACKMANNANSHIRE);
            AddConversion(Regions.CLACKMANNAN, OS_CLACKMANNANSHIRE);
            AddConversion(Regions.CLACKMANNAN, OS_STIRLING);
            AddConversion(Regions.CLACKMANNAN, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.KINROSS, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.KINROSS, OS_FIFE);
            AddConversion(Regions.KINROSS, OS_CLACKMANNANSHIRE);
            AddConversion(Regions.FIFE, OS_FIFE);
            AddConversion(Regions.FIFE, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.WEST_LOTHIAN, OS_WEST_LOTHIAN);
            AddConversion(Regions.WEST_LOTHIAN, OS_NORTH_LANARKSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, OS_SOUTH_LANARKSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, OS_CITY_OF_EDINBURGH);
            AddConversion(Regions.WEST_LOTHIAN, OS_FALKIRK);
            AddConversion(Regions.WEST_LOTHIAN, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.MIDLOTHIAN, OS_CITY_OF_EDINBURGH);
            AddConversion(Regions.MIDLOTHIAN, OS_MIDLOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, OS_WEST_LOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, OS_EAST_LOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.EAST_LOTHIAN, OS_EAST_LOTHIAN);
            AddConversion(Regions.EAST_LOTHIAN, OS_MIDLOTHIAN);
            AddConversion(Regions.EAST_LOTHIAN, OS_CITY_OF_EDINBURGH);
            AddConversion(Regions.EAST_LOTHIAN, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.EAST_LOTHIAN, OS_EAST_LOTHIAN);
            AddConversion(Regions.BERWICK, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.BERWICK, OS_EAST_LOTHIAN);
            AddConversion(Regions.BERWICK, OS_MIDLOTHIAN);
            AddConversion(Regions.ROXBURGH, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.DUMFRIES, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.DUMFRIES, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.DUMFRIES, OS_SOUTH_LANARKSHIRE);
            AddConversion(Regions.KIRKCUDBRIGHT, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.WIGTOWN, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.LANARK, OS_GLASGOW_CITY);
            AddConversion(Regions.LANARK, OS_NORTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, OS_SOUTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.LANARK, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.LANARK, OS_WEST_LOTHIAN);
            AddConversion(Regions.LANARK, OS_EAST_RENFREWSHIRE);
            AddConversion(Regions.SELKIRK, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.PEEBLES, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.PEEBLES, OS_SOUTH_LANARKSHIRE);
            AddConversion(Regions.PEEBLES, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.PEEBLES, OS_MIDLOTHIAN);
            AddConversion(Regions.PEEBLES, OS_WEST_LOTHIAN);
            AddConversion(Regions.ABERDEEN_CITY, OS_ABERDEEN_CITY);
            AddConversion(Regions.ABERDEEN_CITY, OS_ABERDEENSHIRE);
            AddConversion(Regions.ORKNEY, OS_ORKNEY_ISLANDS);
            AddConversion(Regions.SHETLAND, OS_SHETLAND_ISLANDS);
            AddConversion(Regions.BORDERS, OS_SCOTTISH_BORDERS);

            #region Modern Counties - as per Gazetteer

            AddConversion(Regions.BARKING, OS_BARKING_AND_DAGENHAM);
            AddConversion(Regions.BARNET, OS_BARNET);
            AddConversion(Regions.BARNSLEY, OS_BARNSLEY);
            AddConversion(Regions.BATH, OS_BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.BEDS, OS_CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BERKS, OS_WEST_BERKSHIRE);
            AddConversion(Regions.BEXLEY, OS_BEXLEY);
            AddConversion(Regions.BIRMINGHAM, OS_BIRMINGHAM);
            AddConversion(Regions.BLACKBURN, OS_BLACKBURN_WITH_DARWEN);
            AddConversion(Regions.BLACKPOOL, OS_BLACKPOOL);
            AddConversion(Regions.BLAENAU_GWENT, OS_BLAENAU_GWENT);
            AddConversion(Regions.BOLTON, OS_BOLTON);
            AddConversion(Regions.BOURNEMOUTH, OS_BOURNEMOUTH);
            AddConversion(Regions.BRACKNELL, OS_BRACKNELL_FOREST);
            AddConversion(Regions.BRADFORD, OS_BRADFORD);
            AddConversion(Regions.BRENT, OS_BRENT);
            AddConversion(Regions.BRIDGEND, OS_BRIDGEND);
            AddConversion(Regions.BRIGHTON, OS_CITY_OF_BRIGHTON_AND_HOVE);
            AddConversion(Regions.BRISTOL, OS_BRISTOL);
            AddConversion(Regions.BROMLEY, OS_BROMLEY);
            AddConversion(Regions.BUCKS, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.BURY, OS_BURY);
            AddConversion(Regions.BUTE, OS_ARGYLL_AND_BUTE);
            AddConversion(Regions.CAERPHILLY, OS_CAERPHILLY);
            AddConversion(Regions.CALDERDALE, OS_CALDERDALE);
            AddConversion(Regions.CAMBS, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.CAMDEN, OS_CAMDEN);
            AddConversion(Regions.CARDIFF, OS_CARDIFF);
            AddConversion(Regions.CARMARTHEN, OS_CARMARTHENSHIRE);
            AddConversion(Regions.CENTRAL_BEDFORDSHIRE, OS_CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.CEREDIGION, OS_CEREDIGION);
            AddConversion(Regions.CHESHIRE, OS_CHESHIRE_EAST);
            AddConversion(Regions.CHESHIRE, OS_CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.CLACKMANNAN, OS_CLACKMANNANSHIRE);
            AddConversion(Regions.CONWY, OS_CONWY);
            AddConversion(Regions.CORNWALL, OS_CORNWALL);
            AddConversion(Regions.COVENTRY, OS_COVENTRY);
            AddConversion(Regions.CROYDON, OS_CROYDON);
            AddConversion(Regions.CUMBRIA, OS_CUMBRIA);
            AddConversion(Regions.DARLINGTON, OS_DARLINGTON);
            AddConversion(Regions.DENBIGH, OS_DENBIGHSHIRE);
            AddConversion(Regions.DERBY, OS_CITY_OF_DERBY);
            AddConversion(Regions.DERBY, OS_DERBYSHIRE);
            AddConversion(Regions.DEVON, OS_DEVON);
            AddConversion(Regions.DONCASTER, OS_DONCASTER);
            AddConversion(Regions.DORSET, OS_DORSET);
            AddConversion(Regions.DUDLEY, OS_DUDLEY);
            AddConversion(Regions.DUMFRIES_GALLOWAY, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.DUNBARTON, OS_EAST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, OS_WEST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNDEE_CITY, OS_DUNDEE_CITY);
            AddConversion(Regions.DURHAM, OS_DURHAM);
            AddConversion(Regions.EALING, OS_EALING);
            AddConversion(Regions.EAST_AYRSHIRE, OS_EAST_AYRSHIRE);
            AddConversion(Regions.EAST_DUNBARTONSHIRE, OS_EAST_DUNBARTONSHIRE);
            AddConversion(Regions.EAST_LOTHIAN, OS_EAST_LOTHIAN);
            AddConversion(Regions.EAST_RENFREW, OS_EAST_RENFREWSHIRE);
            AddConversion(Regions.EAST_YORKSHIRE, OS_EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.EAST_SUSSEX, OS_EAST_SUSSEX);
            AddConversion(Regions.EDINBURGH_CITY, OS_CITY_OF_EDINBURGH);
            AddConversion(Regions.ENFIELD, OS_ENFIELD);
            AddConversion(Regions.ESSEX, OS_ESSEX);
            AddConversion(Regions.FALKIRK, OS_FALKIRK);
            AddConversion(Regions.FIFE, OS_FIFE);
            AddConversion(Regions.FLINT, OS_FLINTSHIRE);
            AddConversion(Regions.GATESHEAD, OS_GATESHEAD);
            AddConversion(Regions.GLASGOW_CITY, OS_GLASGOW_CITY);
            AddConversion(Regions.GLOUCS, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.GLOUCS, OS_SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.GREENWICH, OS_GREENWICH);
            AddConversion(Regions.GWYNEDD, OS_GWYNEDD);
            AddConversion(Regions.HACKNEY, OS_HACKNEY);
            AddConversion(Regions.HALTON, OS_HALTON);
            AddConversion(Regions.HAMMERSMITH, OS_HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.HANTS, OS_HAMPSHIRE);
            AddConversion(Regions.HARINGEY, OS_HARINGEY);
            AddConversion(Regions.HARROW, OS_HARROW);
            AddConversion(Regions.HARTLEPOOL, OS_HARTLEPOOL);
            AddConversion(Regions.HAVERING, OS_HAVERING);
            AddConversion(Regions.HEREFORD, OS_HEREFORDSHIRE);
            AddConversion(Regions.HERTS, OS_HERTFORDSHIRE);
            AddConversion(Regions.HIGHLAND, OS_HIGHLAND);
            AddConversion(Regions.HILLINGDON, OS_HILLINGDON);
            AddConversion(Regions.HOUNSLOW, OS_HOUNSLOW);
            AddConversion(Regions.INVERCLYDE, OS_INVERCLYDE);
            AddConversion(Regions.ANGLESEY, OS_ISLE_OF_ANGLESEY);
            AddConversion(Regions.IOM, OS_ISLE_OF_MAN);
            AddConversion(Regions.IOW, OS_ISLE_OF_WIGHT);
            AddConversion(Regions.ISLES_OF_SCILLY, OS_ISLES_OF_SCILLY);
            AddConversion(Regions.ISLINGTON, OS_ISLINGTON);
            AddConversion(Regions.KENT, OS_KENT);
            AddConversion(Regions.KINGSTON_HULL, OS_CITY_OF_KINGSTON_UPON_HULL);
            AddConversion(Regions.KINGSTON_THAMES, OS_KINGSTON_UPON_THAMES);
            AddConversion(Regions.KIRKLEES, OS_KIRKLEES);
            AddConversion(Regions.KNOWSLEY, OS_KNOWSLEY);
            AddConversion(Regions.LAMBETH, OS_LAMBETH);
            AddConversion(Regions.LANARK, OS_NORTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, OS_SOUTH_LANARKSHIRE);
            AddConversion(Regions.LANCS, OS_LANCASHIRE);
            AddConversion(Regions.LEEDS, OS_LEEDS);
            AddConversion(Regions.LEICESTER_CITY, OS_CITY_OF_LEICESTER);
            AddConversion(Regions.LEICS, OS_LEICESTERSHIRE);
            AddConversion(Regions.LEWISHAM, OS_LEWISHAM);
            AddConversion(Regions.LINCS, OS_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, OS_NORTH_EAST_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.LIVERPOOL, OS_LIVERPOOL);
            AddConversion(Regions.LONDON, OS_CITY_OF_LONDON);
            AddConversion(Regions.LOTHIAN, OS_EAST_LOTHIAN);
            AddConversion(Regions.LOTHIAN, OS_WEST_LOTHIAN);
            AddConversion(Regions.LUTON, OS_LUTON);
            AddConversion(Regions.MANCHESTER, OS_MANCHESTER);
            AddConversion(Regions.MEDWAY, OS_MEDWAY);
            AddConversion(Regions.MERTHYL, OS_MERTHYR_TYDFIL);
            AddConversion(Regions.MERTON, OS_MERTON);
            AddConversion(Regions.MIDDLESBROUGH, OS_MIDDLESBROUGH);
            AddConversion(Regions.MIDLOTHIAN, OS_MIDLOTHIAN);
            AddConversion(Regions.MILTON_KEYNES, OS_MILTON_KEYNES);
            AddConversion(Regions.MONMOUTH, OS_MONMOUTHSHIRE);
            AddConversion(Regions.MORAY, OS_MORAY);
            AddConversion(Regions.WESTERN_ISLES, OS_WESTERN_ISLES);
            AddConversion(Regions.NEATH, OS_NEATH_PORT_TALBOT);
            AddConversion(Regions.NEWCASTLE, OS_NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.NEWHAM, OS_NEWHAM);
            AddConversion(Regions.NEWPORT, OS_NEWPORT);
            AddConversion(Regions.NORFOLK, OS_NORFOLK);
            AddConversion(Regions.NORTH_AYRSHIRE, OS_NORTH_AYRSHIRE);
            AddConversion(Regions.NE_LINCOLNSHIRE, OS_NORTH_EAST_LINCOLNSHIRE);
            AddConversion(Regions.NORTH_LANARK, OS_NORTH_LANARKSHIRE);
            AddConversion(Regions.NORTH_LINCOLNSHIRE, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.NORTH_SOMERSET, OS_NORTH_SOMERSET);
            AddConversion(Regions.NORTH_TYNESIDE, OS_NORTH_TYNESIDE);
            AddConversion(Regions.NORTH_YORKSHIRE, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.NORTHUMBERLAND, OS_NORTHUMBERLAND);
            AddConversion(Regions.NOTTINGHAM_CITY, OS_CITY_OF_NOTTINGHAM);
            AddConversion(Regions.NOTTS, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.OLDHAM, OS_OLDHAM);
            AddConversion(Regions.ORKNEY, OS_ORKNEY_ISLANDS);
            AddConversion(Regions.OXFORD, OS_OXFORDSHIRE);
            AddConversion(Regions.PEMBROKE, OS_PEMBROKESHIRE);
            AddConversion(Regions.PERTH_KINROSS, OS_PERTH_AND_KINROSS);
            AddConversion(Regions.PETERBOROUGH, OS_CITY_OF_PETERBOROUGH);
            AddConversion(Regions.PLYMOUTH, OS_CITY_OF_PLYMOUTH);
            AddConversion(Regions.POOLE, OS_POOLE);
            AddConversion(Regions.PORTSMOUTH, OS_CITY_OF_PORTSMOUTH);
            AddConversion(Regions.POWYS, OS_POWYS);
            AddConversion(Regions.READING, OS_READING);
            AddConversion(Regions.REDBRIDGE, OS_REDBRIDGE);
            AddConversion(Regions.REDCAR, OS_REDCAR_AND_CLEVELAND);
            AddConversion(Regions.RENFREW, OS_EAST_RENFREWSHIRE);
            AddConversion(Regions.RENFREW, OS_RENFREWSHIRE);
            AddConversion(Regions.RHONDDA, OS_RHONDDA_CYNON_TAFF);
            AddConversion(Regions.RICHMOND_THAMES, OS_RICHMOND_UPON_THAMES);
            AddConversion(Regions.ROCHDALE, OS_ROCHDALE);
            AddConversion(Regions.ROTHERHAM, OS_ROTHERHAM);
            AddConversion(Regions.KENSINGTON, OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.RUTLAND, OS_RUTLAND);
            AddConversion(Regions.SALFORD, OS_SALFORD);
            AddConversion(Regions.SANDWELL, OS_SANDWELL);
            AddConversion(Regions.BORDERS, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.SEFTON, OS_SEFTON);
            AddConversion(Regions.SHEFFIELD, OS_SHEFFIELD);
            AddConversion(Regions.SHETLAND, OS_SHETLAND_ISLANDS);
            AddConversion(Regions.SHROPS, OS_SHROPSHIRE);
            AddConversion(Regions.SLOUGH, OS_SLOUGH);
            AddConversion(Regions.SOLIHULL, OS_SOLIHULL);
            AddConversion(Regions.SOMERSET, OS_BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.SOMERSET, OS_NORTH_SOMERSET);
            AddConversion(Regions.SOMERSET, OS_SOMERSET);
            AddConversion(Regions.SOUTH_AYRSHIRE, OS_SOUTH_AYRSHIRE);
            AddConversion(Regions.SOUTH_GLOUCESTERSHIRE, OS_SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.SOUTH_LANARK, OS_SOUTH_LANARKSHIRE);
            AddConversion(Regions.SOUTH_TYNESIDE, OS_SOUTH_TYNESIDE);
            AddConversion(Regions.SOUTHAMPTON, OS_CITY_OF_SOUTHAMPTON);
            AddConversion(Regions.SOUTHEND, OS_SOUTHEND_ON_SEA);
            AddConversion(Regions.SOUTHWARK, OS_SOUTHWARK);
            AddConversion(Regions.ST_HELENS, OS_ST_HELENS);
            AddConversion(Regions.STAFFS, OS_STAFFORDSHIRE);
            AddConversion(Regions.STIRLING, OS_STIRLING);
            AddConversion(Regions.STOCKPORT, OS_STOCKPORT);
            AddConversion(Regions.STOCKTON, OS_STOCKTON_ON_TEES);
            AddConversion(Regions.STOKE, OS_CITY_OF_STOKE_ON_TRENT);
            AddConversion(Regions.SUFFOLK, OS_SUFFOLK);
            AddConversion(Regions.SUNDERLAND, OS_SUNDERLAND);
            AddConversion(Regions.SURREY, OS_SURREY);
            AddConversion(Regions.SUSSEX, OS_EAST_SUSSEX);
            AddConversion(Regions.SUSSEX, OS_WEST_SUSSEX);
            AddConversion(Regions.SUTTON, OS_SUTTON);
            AddConversion(Regions.SWANSEA, OS_SWANSEA);
            AddConversion(Regions.SWINDON, OS_SWINDON);
            AddConversion(Regions.TAMESIDE, OS_TAMESIDE);
            AddConversion(Regions.TELFORD, OS_TELFORD_AND_WREKIN);
            AddConversion(Regions.THURROCK, OS_THURROCK);
            AddConversion(Regions.TORBAY, OS_TORBAY);
            AddConversion(Regions.TORFAEN, OS_TORFAEN);
            AddConversion(Regions.TOWER_HAMLETS, OS_TOWER_HAMLETS);
            AddConversion(Regions.TRAFFORD, OS_TRAFFORD);
            AddConversion(Regions.VALE_GLAMORGAN, OS_VALE_OF_GLAMORGAN);
            AddConversion(Regions.WAKEFIELD, OS_WAKEFIELD);
            AddConversion(Regions.WALSALL, OS_WALSALL);
            AddConversion(Regions.WALTHAM_FOREST, OS_WALTHAM_FOREST);
            AddConversion(Regions.WANDSWORTH, OS_WANDSWORTH);
            AddConversion(Regions.WARRINGTON, OS_WARRINGTON);
            AddConversion(Regions.WARWICK, OS_WARWICKSHIRE);
            AddConversion(Regions.WEST_BERKSHIRE, OS_WEST_BERKSHIRE);
            AddConversion(Regions.WEST_DUNBARTON, OS_WEST_DUNBARTONSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, OS_WEST_LOTHIAN);
            AddConversion(Regions.WEST_SUSSEX, OS_WEST_SUSSEX);
            AddConversion(Regions.WESTERN_ISLES, OS_WESTERN_ISLES);
            AddConversion(Regions.WESTMINSTER, OS_CITY_OF_WESTMINSTER);
            AddConversion(Regions.WIGAN, OS_WIGAN);
            AddConversion(Regions.WILTS, OS_WILTSHIRE);
            AddConversion(Regions.WINDSOR, OS_WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.WIRRAL, OS_WIRRAL);
            AddConversion(Regions.WOKINGHAM, OS_WOKINGHAM);
            AddConversion(Regions.WOLVERHAMPTON, OS_CITY_OF_WOLVERHAMPTON);
            AddConversion(Regions.WORCESTER, OS_WORCESTERSHIRE);
            AddConversion(Regions.WREXHAM, OS_WREXHAM);
            AddConversion(Regions.YORK, OS_YORK);
            #endregion

            // Alternate names for Modern Counties
            //CONVERSIONS.Add(new County("Barking", OS_BARKING_AND_DAGENHAM);
            //CONVERSIONS.Add(new County("Bath", OS_BATH_AND_NORTH_EAST_SOMERSET);
            //CONVERSIONS.Add(new County("Bedford", OS_BEDFORD);
            //CONVERSIONS.Add(new County("Blackburn", OS_BLACKBURN_WITH_DARWEN);
            //CONVERSIONS.Add(new County("Brighton", OS_CITY_OF_BRIGHTON_AND_HOVE);
            //CONVERSIONS.Add(new County("Bristol", OS_BRISTOL);
            //CONVERSIONS.Add(new County("Chelsea", OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            //CONVERSIONS.Add(new County("Chester", OS_CHESHIRE_WEST_AND_CHESTER);
            //CONVERSIONS.Add(new County("Hammersmith", OS_HAMMERSMITH_AND_FULHAM);
            //CONVERSIONS.Add(new County("Kensington and Chelsea", OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            //CONVERSIONS.Add(new County("Kensington", OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            //CONVERSIONS.Add(new County("Telford", OS_TELFORD_AND_WREKIN);
            //CONVERSIONS.Add(new County("Tyneside", OS_NORTH_TYNESIDE);
            //CONVERSIONS.Add(new County("Tyneside", OS_SOUTH_TYNESIDE);
            //AddConversion(Regions.WARWICK, OS_BIRMINGHAM);
            //CONVERSIONS.Add(new County("Windsor", OS_WINDSOR_AND_MAIDENHEAD);
            //CONVERSIONS.Add(new County("Wrekin", OS_TELFORD_AND_WREKIN);

            // from parish maps
            AddConversion(Regions.ANGLESEY, OS_ISLE_OF_ANGLESEY);
            AddConversion(Regions.BEDS, OS_BEDFORDSHIRE);
            AddConversion(Regions.BEDS, OS_CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BEDS, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.BEDS, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.BEDS, OS_HERTFORDSHIRE);
            AddConversion(Regions.BEDS, OS_LUTON);
            AddConversion(Regions.BEDS, OS_MILTON_KEYNES);
            AddConversion(Regions.BERKS, OS_BRACKNELL_FOREST);
            AddConversion(Regions.BERKS, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.BERKS, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.BERKS, OS_HAMPSHIRE);
            AddConversion(Regions.BERKS, OS_OXFORDSHIRE);
            AddConversion(Regions.BERKS, OS_READING);
            AddConversion(Regions.BERKS, OS_SWINDON);
            AddConversion(Regions.BERKS, OS_SURREY);
            AddConversion(Regions.BERKS, OS_WEST_BERKSHIRE);
            AddConversion(Regions.BERKS, OS_WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.BERKS, OS_WOKINGHAM);
            AddConversion(Regions.BERKS, OS_WILTSHIRE);
            AddConversion(Regions.BRECON, OS_BLAENAU_GWENT);
            AddConversion(Regions.BRECON, OS_CEREDIGION);
            AddConversion(Regions.BRECON, OS_CAERPHILLY);
            AddConversion(Regions.BRECON, OS_CARMARTHENSHIRE);
            AddConversion(Regions.BRECON, OS_HEREFORDSHIRE);
            AddConversion(Regions.BRECON, OS_MONMOUTHSHIRE);
            AddConversion(Regions.BRECON, OS_MERTHYR_TYDFIL);
            AddConversion(Regions.BRECON, OS_NEATH_PORT_TALBOT);
            AddConversion(Regions.BRECON, OS_POWYS);
            AddConversion(Regions.BRECON, OS_RHONDDA_CYNON_TAFF);
            AddConversion(Regions.BRECON, OS_TORFAEN);
            AddConversion(Regions.BUCKS, OS_BEDFORDSHIRE);
            AddConversion(Regions.BUCKS, OS_CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BUCKS, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.BUCKS, OS_HERTFORDSHIRE);
            AddConversion(Regions.BUCKS, OS_MILTON_KEYNES);
            AddConversion(Regions.BUCKS, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.BUCKS, OS_OXFORDSHIRE);
            AddConversion(Regions.BUCKS, OS_SURREY);
            AddConversion(Regions.BUCKS, OS_WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.BUCKS, OS_WOKINGHAM);
            AddConversion(Regions.BUCKS, OS_SLOUGH);
            AddConversion(Regions.CAERNARFON, OS_CONWY);
            AddConversion(Regions.CAERNARFON, OS_GWYNEDD);
            AddConversion(Regions.CAERNARFON, OS_ISLE_OF_ANGLESEY);
            AddConversion(Regions.CAMBS, OS_CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.CAMBS, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.CAMBS, OS_ESSEX);
            AddConversion(Regions.CAMBS, OS_HERTFORDSHIRE);
            AddConversion(Regions.CAMBS, OS_LINCOLNSHIRE);
            AddConversion(Regions.CAMBS, OS_NORFOLK);
            AddConversion(Regions.CAMBS, OS_CITY_OF_PETERBOROUGH);
            AddConversion(Regions.CAMBS, OS_SUFFOLK);
            AddConversion(Regions.CEREDIGION, OS_CEREDIGION);
            AddConversion(Regions.CEREDIGION, OS_CARMARTHENSHIRE);
            AddConversion(Regions.CEREDIGION, OS_GWYNEDD);
            AddConversion(Regions.CEREDIGION, OS_PEMBROKESHIRE);
            AddConversion(Regions.CEREDIGION, OS_POWYS);
            AddConversion(Regions.CARMARTHEN, OS_CEREDIGION);
            AddConversion(Regions.CARMARTHEN, OS_CARMARTHENSHIRE);
            AddConversion(Regions.CARMARTHEN, OS_NEATH_PORT_TALBOT);
            AddConversion(Regions.CARMARTHEN, OS_PEMBROKESHIRE);
            AddConversion(Regions.CARMARTHEN, OS_POWYS);
            AddConversion(Regions.CARMARTHEN, OS_SWANSEA);
            AddConversion(Regions.CHESHIRE, OS_CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.CHESHIRE, OS_CHESHIRE_EAST);
            AddConversion(Regions.CHESHIRE, OS_DERBYSHIRE);
            AddConversion(Regions.CHESHIRE, OS_FLINTSHIRE);
            AddConversion(Regions.CHESHIRE, OS_HALTON);
            AddConversion(Regions.CHESHIRE, OS_MANCHESTER);
            AddConversion(Regions.CHESHIRE, OS_OLDHAM);
            AddConversion(Regions.CHESHIRE, OS_STAFFORDSHIRE);
            AddConversion(Regions.CHESHIRE, OS_SHROPSHIRE);
            AddConversion(Regions.CHESHIRE, OS_TRAFFORD);
            AddConversion(Regions.CHESHIRE, OS_TAMESIDE);
            AddConversion(Regions.CHESHIRE, OS_WARRINGTON);
            AddConversion(Regions.CHESHIRE, OS_WIRRAL);
            AddConversion(Regions.CHESHIRE, OS_WREXHAM);
            AddConversion(Regions.CHESHIRE, OS_STOCKPORT);
            AddConversion(Regions.CORNWALL, OS_CORNWALL);
            AddConversion(Regions.CORNWALL, OS_DEVON);
            AddConversion(Regions.DURHAM, OS_CUMBRIA);
            AddConversion(Regions.DURHAM, OS_DARLINGTON);
            AddConversion(Regions.DURHAM, OS_DURHAM);
            AddConversion(Regions.DURHAM, OS_GATESHEAD);
            AddConversion(Regions.DURHAM, OS_HARTLEPOOL);
            AddConversion(Regions.DURHAM, OS_MIDDLESBROUGH);
            AddConversion(Regions.DURHAM, OS_NORTHUMBERLAND);
            AddConversion(Regions.DURHAM, OS_NORTH_TYNESIDE);
            AddConversion(Regions.DURHAM, OS_NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.DURHAM, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.DURHAM, OS_STOCKTON_ON_TEES);
            AddConversion(Regions.DURHAM, OS_SUNDERLAND);
            AddConversion(Regions.DURHAM, OS_SOUTH_TYNESIDE);
            AddConversion(Regions.CUMBERLAND, OS_CUMBRIA);
            AddConversion(Regions.CUMBERLAND, OS_DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.CUMBERLAND, OS_NORTHUMBERLAND);
            AddConversion(Regions.CUMBERLAND, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.DENBIGH, OS_CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.DENBIGH, OS_CONWY);
            AddConversion(Regions.DENBIGH, OS_DENBIGHSHIRE);
            AddConversion(Regions.DENBIGH, OS_FLINTSHIRE);
            AddConversion(Regions.DENBIGH, OS_GWYNEDD);
            AddConversion(Regions.DENBIGH, OS_POWYS);
            AddConversion(Regions.DENBIGH, OS_SHROPSHIRE);
            AddConversion(Regions.DENBIGH, OS_WREXHAM);
            AddConversion(Regions.DERBY, OS_CHESHIRE_EAST);
            AddConversion(Regions.DERBY, OS_CITY_OF_DERBY);
            AddConversion(Regions.DERBY, OS_DERBYSHIRE);
            AddConversion(Regions.DERBY, OS_LEICESTERSHIRE);
            AddConversion(Regions.DERBY, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.DERBY, OS_STAFFORDSHIRE);
            AddConversion(Regions.DERBY, OS_SHEFFIELD);
            AddConversion(Regions.DERBY, OS_TAMESIDE);
            AddConversion(Regions.DERBY, OS_STOCKPORT);
            AddConversion(Regions.DEVON, OS_CORNWALL);
            AddConversion(Regions.DEVON, OS_DEVON);
            AddConversion(Regions.DEVON, OS_HAMPSHIRE);
            AddConversion(Regions.DEVON, OS_CITY_OF_PLYMOUTH);
            AddConversion(Regions.DEVON, OS_SOMERSET);
            AddConversion(Regions.DEVON, OS_TORBAY);
            AddConversion(Regions.DORSET, OS_BOURNEMOUTH);
            AddConversion(Regions.DORSET, OS_DEVON);
            AddConversion(Regions.DORSET, OS_DORSET);
            AddConversion(Regions.DORSET, OS_POOLE);
            AddConversion(Regions.DORSET, OS_SOMERSET);
            AddConversion(Regions.DORSET, OS_WILTSHIRE);
            AddConversion(Regions.DURHAM, OS_CUMBRIA);
            AddConversion(Regions.DURHAM, OS_DARLINGTON);
            AddConversion(Regions.DURHAM, OS_DURHAM);
            AddConversion(Regions.DURHAM, OS_GATESHEAD);
            AddConversion(Regions.DURHAM, OS_HARTLEPOOL);
            AddConversion(Regions.DURHAM, OS_MIDDLESBROUGH);
            AddConversion(Regions.DURHAM, OS_NORTHUMBERLAND);
            AddConversion(Regions.DURHAM, OS_NORTH_TYNESIDE);
            AddConversion(Regions.DURHAM, OS_NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.DURHAM, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.DURHAM, OS_STOCKTON_ON_TEES);
            AddConversion(Regions.DURHAM, OS_SUNDERLAND);
            AddConversion(Regions.DURHAM, OS_SOUTH_TYNESIDE);
            AddConversion(Regions.ESSEX, OS_BARKING_AND_DAGENHAM);
            AddConversion(Regions.ESSEX, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.ESSEX, OS_ENFIELD);
            AddConversion(Regions.ESSEX, OS_ESSEX);
            AddConversion(Regions.ESSEX, OS_GREENWICH);
            AddConversion(Regions.ESSEX, OS_HERTFORDSHIRE);
            AddConversion(Regions.ESSEX, OS_HAVERING);
            AddConversion(Regions.ESSEX, OS_KENT);
            AddConversion(Regions.ESSEX, OS_MEDWAY);
            AddConversion(Regions.ESSEX, OS_NEWHAM);
            AddConversion(Regions.ESSEX, OS_REDBRIDGE);
            AddConversion(Regions.ESSEX, OS_SUFFOLK);
            AddConversion(Regions.ESSEX, OS_THURROCK);
            AddConversion(Regions.ESSEX, OS_WALTHAM_FOREST);
            AddConversion(Regions.ESSEX, OS_SOUTHEND_ON_SEA);
            AddConversion(Regions.FLINT, OS_CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.FLINT, OS_CONWY);
            AddConversion(Regions.FLINT, OS_DENBIGHSHIRE);
            AddConversion(Regions.FLINT, OS_FLINTSHIRE);
            AddConversion(Regions.FLINT, OS_SHROPSHIRE);
            AddConversion(Regions.FLINT, OS_WREXHAM);
            AddConversion(Regions.GLAMORGAN, OS_BRIDGEND);
            AddConversion(Regions.GLAMORGAN, OS_CARDIFF);
            AddConversion(Regions.GLAMORGAN, OS_CAERPHILLY);
            AddConversion(Regions.GLAMORGAN, OS_CARMARTHENSHIRE);
            AddConversion(Regions.GLAMORGAN, OS_MERTHYR_TYDFIL);
            AddConversion(Regions.GLAMORGAN, OS_NEWPORT);
            AddConversion(Regions.GLAMORGAN, OS_NEATH_PORT_TALBOT);
            AddConversion(Regions.GLAMORGAN, OS_POWYS);
            AddConversion(Regions.GLAMORGAN, OS_RHONDDA_CYNON_TAFF);
            AddConversion(Regions.GLAMORGAN, OS_SWANSEA);
            AddConversion(Regions.GLAMORGAN, OS_VALE_OF_GLAMORGAN);
            AddConversion(Regions.GLOUCS, OS_BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.GLOUCS, OS_BRISTOL);
            AddConversion(Regions.GLOUCS, OS_DORSET);
            AddConversion(Regions.GLOUCS, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.GLOUCS, OS_HEREFORDSHIRE);
            AddConversion(Regions.GLOUCS, OS_MONMOUTHSHIRE);
            AddConversion(Regions.GLOUCS, OS_NORTH_SOMERSET);
            AddConversion(Regions.GLOUCS, OS_OXFORDSHIRE);
            AddConversion(Regions.GLOUCS, OS_SWINDON);
            AddConversion(Regions.GLOUCS, OS_SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.GLOUCS, OS_WARWICKSHIRE);
            AddConversion(Regions.GLOUCS, OS_WORCESTERSHIRE);
            AddConversion(Regions.GLOUCS, OS_WILTSHIRE);
            AddConversion(Regions.HANTS, OS_BOURNEMOUTH);
            AddConversion(Regions.HANTS, OS_DORSET);
            AddConversion(Regions.HANTS, OS_HALTON);
            AddConversion(Regions.HANTS, OS_HAMPSHIRE);
            AddConversion(Regions.HANTS, OS_ISLE_OF_WIGHT);
            AddConversion(Regions.HANTS, OS_POOLE);
            AddConversion(Regions.HANTS, OS_CITY_OF_PORTSMOUTH);
            AddConversion(Regions.HANTS, OS_CITY_OF_SOUTHAMPTON);
            AddConversion(Regions.HANTS, OS_SURREY);
            AddConversion(Regions.HANTS, OS_WEST_BERKSHIRE);
            AddConversion(Regions.HANTS, OS_WOKINGHAM);
            AddConversion(Regions.HANTS, OS_WEST_SUSSEX);
            AddConversion(Regions.HANTS, OS_WILTSHIRE);
            AddConversion(Regions.HEREFORD, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.HEREFORD, OS_HEREFORDSHIRE);
            AddConversion(Regions.HEREFORD, OS_MONMOUTHSHIRE);
            AddConversion(Regions.HEREFORD, OS_POWYS);
            AddConversion(Regions.HEREFORD, OS_SHROPSHIRE);
            AddConversion(Regions.HEREFORD, OS_WORCESTERSHIRE);
            AddConversion(Regions.HERTS, OS_CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.HERTS, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.HERTS, OS_BARNET);
            AddConversion(Regions.HERTS, OS_ENFIELD);
            AddConversion(Regions.HERTS, OS_ESSEX);
            AddConversion(Regions.HERTS, OS_HERTFORDSHIRE);
            AddConversion(Regions.HERTS, OS_HILLINGDON);
            AddConversion(Regions.HERTS, OS_HARROW);
            AddConversion(Regions.HUNTS, OS_BEDFORDSHIRE);
            AddConversion(Regions.HUNTS, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.HUNTS, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.HUNTS, OS_CITY_OF_PETERBOROUGH);
            AddConversion(Regions.KENT, OS_BROMLEY);
            AddConversion(Regions.KENT, OS_BEXLEY);
            AddConversion(Regions.KENT, OS_CROYDON);
            AddConversion(Regions.KENT, OS_EAST_SUSSEX);
            AddConversion(Regions.KENT, OS_GREENWICH);
            AddConversion(Regions.KENT, OS_HAVERING);
            AddConversion(Regions.KENT, OS_KENT);
            AddConversion(Regions.KENT, OS_LEWISHAM);
            AddConversion(Regions.KENT, OS_MEDWAY);
            AddConversion(Regions.KENT, OS_NEWHAM);
            AddConversion(Regions.KENT, OS_SURREY);
            AddConversion(Regions.KENT, OS_TOWER_HAMLETS);
            AddConversion(Regions.KENT, OS_THURROCK);
            AddConversion(Regions.LANCS, OS_BLACKBURN_WITH_DARWEN);
            AddConversion(Regions.LANCS, OS_BOLTON);
            AddConversion(Regions.LANCS, OS_BLACKPOOL);
            AddConversion(Regions.LANCS, OS_BURY);
            AddConversion(Regions.LANCS, OS_CALDERDALE);
            AddConversion(Regions.LANCS, OS_CHESHIRE_EAST);
            AddConversion(Regions.LANCS, OS_CUMBRIA);
            AddConversion(Regions.LANCS, OS_HALTON);
            AddConversion(Regions.LANCS, OS_KNOWSLEY);
            AddConversion(Regions.LANCS, OS_LANCASHIRE);
            AddConversion(Regions.LANCS, OS_LIVERPOOL);
            AddConversion(Regions.LANCS, OS_MANCHESTER);
            AddConversion(Regions.LANCS, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.LANCS, OS_OLDHAM);
            AddConversion(Regions.LANCS, OS_ROCHDALE);
            AddConversion(Regions.LANCS, OS_SALFORD);
            AddConversion(Regions.LANCS, OS_SEFTON);
            AddConversion(Regions.LANCS, OS_ST_HELENS);
            AddConversion(Regions.LANCS, OS_TRAFFORD);
            AddConversion(Regions.LANCS, OS_TAMESIDE);
            AddConversion(Regions.LANCS, OS_WARRINGTON);
            AddConversion(Regions.LANCS, OS_WIGAN);
            AddConversion(Regions.LANCS, OS_STOCKPORT);
            AddConversion(Regions.LEICS, OS_DERBYSHIRE);
            AddConversion(Regions.LEICS, OS_CITY_OF_LEICESTER);
            AddConversion(Regions.LEICS, OS_LINCOLNSHIRE);
            AddConversion(Regions.LEICS, OS_LEICESTERSHIRE);
            AddConversion(Regions.LEICS, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.LEICS, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.LEICS, OS_RUTLAND);
            AddConversion(Regions.LEICS, OS_STAFFORDSHIRE);
            AddConversion(Regions.LEICS, OS_WARWICKSHIRE);
            AddConversion(Regions.LINCS, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.LINCS, OS_DONCASTER);
            AddConversion(Regions.LINCS, OS_EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.LINCS, OS_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, OS_LEICESTERSHIRE);
            AddConversion(Regions.LINCS, OS_NORTH_EAST_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, OS_NORFOLK);
            AddConversion(Regions.LINCS, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.LINCS, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.LINCS, OS_CITY_OF_PETERBOROUGH);
            AddConversion(Regions.LINCS, OS_RUTLAND);
            AddConversion(Regions.LONDON, OS_BRACKNELL_FOREST);
            AddConversion(Regions.LONDON, OS_BARNET);
            AddConversion(Regions.LONDON, OS_BROMLEY);
            AddConversion(Regions.LONDON, OS_BRENT);
            AddConversion(Regions.LONDON, OS_CAMDEN);
            AddConversion(Regions.LONDON, OS_CROYDON);
            AddConversion(Regions.LONDON, OS_EALING);
            AddConversion(Regions.LONDON, OS_ENFIELD);
            AddConversion(Regions.LONDON, OS_EAST_SUSSEX);
            AddConversion(Regions.LONDON, OS_ESSEX);
            AddConversion(Regions.LONDON, OS_HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.LONDON, OS_HARINGEY);
            AddConversion(Regions.LONDON, OS_HILLINGDON);
            AddConversion(Regions.LONDON, OS_HACKNEY);
            AddConversion(Regions.LONDON, OS_HARROW);
            AddConversion(Regions.LONDON, OS_HOUNSLOW);
            AddConversion(Regions.LONDON, OS_ISLINGTON);
            AddConversion(Regions.LONDON, OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.LONDON, OS_KINGSTON_UPON_THAMES);
            AddConversion(Regions.LONDON, OS_KENT);
            AddConversion(Regions.LONDON, OS_LAMBETH);
            AddConversion(Regions.LONDON, OS_CITY_OF_LONDON);
            AddConversion(Regions.LONDON, OS_LEWISHAM);
            AddConversion(Regions.LONDON, OS_MERTON);
            AddConversion(Regions.LONDON, OS_NEWHAM);
            AddConversion(Regions.LONDON, OS_RICHMOND_UPON_THAMES);
            AddConversion(Regions.LONDON, OS_SURREY);
            AddConversion(Regions.LONDON, OS_SOUTHWARK);
            AddConversion(Regions.LONDON, OS_SUTTON);
            AddConversion(Regions.LONDON, OS_TOWER_HAMLETS);
            AddConversion(Regions.LONDON, OS_WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.LONDON, OS_CITY_OF_WESTMINSTER);
            AddConversion(Regions.LONDON, OS_WEST_SUSSEX);
            AddConversion(Regions.LONDON, OS_WEST_SUSSEX);
            AddConversion(Regions.LONDON, OS_WANDSWORTH);
            AddConversion(Regions.LONDON, OS_WANDSWORTH);
            AddConversion(Regions.MANCHESTER, OS_OLDHAM);
            AddConversion(Regions.MANCHESTER, OS_OLDHAM);
            AddConversion(Regions.MANCHESTER, OS_TAMESIDE);
            AddConversion(Regions.MERIONETH, OS_CONWY);
            AddConversion(Regions.MERIONETH, OS_DENBIGHSHIRE);
            AddConversion(Regions.MERIONETH, OS_GWYNEDD);
            AddConversion(Regions.MERIONETH, OS_POWYS);
            AddConversion(Regions.MIDDLESEX, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.MIDDLESEX, OS_BARNET);
            AddConversion(Regions.MIDDLESEX, OS_BRENT);
            AddConversion(Regions.MIDDLESEX, OS_CAMDEN);
            AddConversion(Regions.MIDDLESEX, OS_EALING);
            AddConversion(Regions.MIDDLESEX, OS_ENFIELD);
            AddConversion(Regions.MIDDLESEX, OS_ESSEX);
            AddConversion(Regions.MIDDLESEX, OS_HERTFORDSHIRE);
            AddConversion(Regions.MIDDLESEX, OS_HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.MIDDLESEX, OS_HARINGEY);
            AddConversion(Regions.MIDDLESEX, OS_HILLINGDON);
            AddConversion(Regions.MIDDLESEX, OS_HACKNEY);
            AddConversion(Regions.MIDDLESEX, OS_HARROW);
            AddConversion(Regions.MIDDLESEX, OS_HOUNSLOW);
            AddConversion(Regions.MIDDLESEX, OS_ISLINGTON);
            AddConversion(Regions.MIDDLESEX, OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.MIDDLESEX, OS_LAMBETH);
            AddConversion(Regions.MIDDLESEX, OS_CITY_OF_LONDON);
            AddConversion(Regions.MIDDLESEX, OS_NEWHAM);
            AddConversion(Regions.MIDDLESEX, OS_RICHMOND_UPON_THAMES);
            AddConversion(Regions.MIDDLESEX, OS_SURREY);
            AddConversion(Regions.MIDDLESEX, OS_SOUTHWARK);
            AddConversion(Regions.MIDDLESEX, OS_TOWER_HAMLETS);
            AddConversion(Regions.MIDDLESEX, OS_WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.MIDDLESEX, OS_CITY_OF_WESTMINSTER);
            AddConversion(Regions.MIDDLESEX, OS_WANDSWORTH);
            AddConversion(Regions.MONMOUTH, OS_BLAENAU_GWENT);
            AddConversion(Regions.MONMOUTH, OS_CARDIFF);
            AddConversion(Regions.MONMOUTH, OS_CAERPHILLY);
            AddConversion(Regions.MONMOUTH, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.MONMOUTH, OS_HEREFORDSHIRE);
            AddConversion(Regions.MONMOUTH, OS_MONMOUTHSHIRE);
            AddConversion(Regions.MONMOUTH, OS_MERTHYR_TYDFIL);
            AddConversion(Regions.MONMOUTH, OS_NEWPORT);
            AddConversion(Regions.MONMOUTH, OS_POWYS);
            AddConversion(Regions.MONMOUTH, OS_RHONDDA_CYNON_TAFF);
            AddConversion(Regions.MONMOUTH, OS_TORFAEN);
            AddConversion(Regions.MONTGOMERY, OS_CEREDIGION);
            AddConversion(Regions.MONTGOMERY, OS_GWYNEDD);
            AddConversion(Regions.MONTGOMERY, OS_POWYS);
            AddConversion(Regions.MONTGOMERY, OS_SHROPSHIRE);
            AddConversion(Regions.NORFOLK, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.NORFOLK, OS_LINCOLNSHIRE);
            AddConversion(Regions.NORFOLK, OS_NORFOLK);
            AddConversion(Regions.NORFOLK, OS_SUFFOLK);
            AddConversion(Regions.NORTH_YORKSHIRE, OS_DARLINGTON);
            AddConversion(Regions.NORTH_YORKSHIRE, OS_MIDDLESBROUGH);
            AddConversion(Regions.NORTH_YORKSHIRE, OS_REDCAR_AND_CLEVELAND);
            AddConversion(Regions.NORTH_YORKSHIRE, OS_STOCKTON_ON_TEES);
            AddConversion(Regions.NORTHAMPTON, OS_BEDFORDSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_LINCOLNSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_LEICESTERSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_MILTON_KEYNES);
            AddConversion(Regions.NORTHAMPTON, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_OXFORDSHIRE);
            AddConversion(Regions.NORTHAMPTON, OS_CITY_OF_PETERBOROUGH);
            AddConversion(Regions.NORTHAMPTON, OS_WARWICKSHIRE);
            AddConversion(Regions.NORTHUMBERLAND, OS_CUMBRIA);
            AddConversion(Regions.NORTHUMBERLAND, OS_DURHAM);
            AddConversion(Regions.NORTHUMBERLAND, OS_GATESHEAD);
            AddConversion(Regions.NORTHUMBERLAND, OS_NORTHUMBERLAND);
            AddConversion(Regions.NORTHUMBERLAND, OS_NORTH_TYNESIDE);
            AddConversion(Regions.NORTHUMBERLAND, OS_NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.NORTHUMBERLAND, OS_SCOTTISH_BORDERS);
            AddConversion(Regions.NOTTS, OS_DONCASTER);
            AddConversion(Regions.NOTTS, OS_DERBYSHIRE);
            AddConversion(Regions.NOTTS, OS_LINCOLNSHIRE);
            AddConversion(Regions.NOTTS, OS_LEICESTERSHIRE);
            AddConversion(Regions.NOTTS, OS_CITY_OF_NOTTINGHAM);
            AddConversion(Regions.NOTTS, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.NOTTS, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.OXFORD, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.OXFORD, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.OXFORD, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.OXFORD, OS_OXFORDSHIRE);
            AddConversion(Regions.OXFORD, OS_READING);
            AddConversion(Regions.OXFORD, OS_WEST_BERKSHIRE);
            AddConversion(Regions.OXFORD, OS_WOKINGHAM);
            AddConversion(Regions.OXFORD, OS_WARWICKSHIRE);
            AddConversion(Regions.PEMBROKE, OS_CEREDIGION);
            AddConversion(Regions.PEMBROKE, OS_CARMARTHENSHIRE);
            AddConversion(Regions.PEMBROKE, OS_PEMBROKESHIRE);
            AddConversion(Regions.RADNOR, OS_CEREDIGION);
            AddConversion(Regions.RADNOR, OS_HEREFORDSHIRE);
            AddConversion(Regions.RADNOR, OS_POWYS);
            AddConversion(Regions.RADNOR, OS_SHROPSHIRE);
            AddConversion(Regions.RUTLAND, OS_LINCOLNSHIRE);
            AddConversion(Regions.RUTLAND, OS_LEICESTERSHIRE);
            AddConversion(Regions.RUTLAND, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.RUTLAND, OS_RUTLAND);
            AddConversion(Regions.SHROPS, OS_CHESHIRE_EAST);
            AddConversion(Regions.SHROPS, OS_HEREFORDSHIRE);
            AddConversion(Regions.SHROPS, OS_POWYS);
            AddConversion(Regions.SHROPS, OS_STAFFORDSHIRE);
            AddConversion(Regions.SHROPS, OS_SHROPSHIRE);
            AddConversion(Regions.SHROPS, OS_WORCESTERSHIRE);
            AddConversion(Regions.SHROPS, OS_TELFORD_AND_WREKIN);
            AddConversion(Regions.SHROPS, OS_WREXHAM);
            AddConversion(Regions.SOMERSET, OS_BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.SOMERSET, OS_BRISTOL);
            AddConversion(Regions.SOMERSET, OS_DEVON);
            AddConversion(Regions.SOMERSET, OS_DORSET);
            AddConversion(Regions.SOMERSET, OS_NORTH_SOMERSET);
            AddConversion(Regions.SOMERSET, OS_SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.SOMERSET, OS_SOMERSET);
            AddConversion(Regions.SOMERSET, OS_WILTSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_BRADFORD);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_BARNSLEY);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_CALDERDALE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_CHESHIRE_EAST);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_CUMBRIA);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_DONCASTER);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_DURHAM);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_DERBYSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_KIRKLEES);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_LANCASHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_LEEDS);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_MANCHESTER);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_OLDHAM);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_ROCHDALE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_ROTHERHAM);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_SHEFFIELD);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_TAMESIDE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_WAKEFIELD);
            AddConversion(Regions.SOUTH_YORKSHIRE, OS_YORK);
            AddConversion(Regions.STAFFS, OS_BIRMINGHAM);
            AddConversion(Regions.STAFFS, OS_CHESHIRE_EAST);
            AddConversion(Regions.STAFFS, OS_DERBYSHIRE);
            AddConversion(Regions.STAFFS, OS_DUDLEY);
            AddConversion(Regions.STAFFS, OS_SANDWELL);
            AddConversion(Regions.STAFFS, OS_STAFFORDSHIRE);
            AddConversion(Regions.STAFFS, OS_SHROPSHIRE);
            AddConversion(Regions.STAFFS, OS_CITY_OF_STOKE_ON_TRENT);
            AddConversion(Regions.STAFFS, OS_SOUTH_TYNESIDE);
            AddConversion(Regions.STAFFS, OS_WALSALL);
            AddConversion(Regions.STAFFS, OS_CITY_OF_WOLVERHAMPTON);
            AddConversion(Regions.STAFFS, OS_WARWICKSHIRE);
            AddConversion(Regions.STAFFS, OS_WORCESTERSHIRE);
            AddConversion(Regions.SUFFOLK, OS_CAMBRIDGESHIRE);
            AddConversion(Regions.SUFFOLK, OS_ESSEX);
            AddConversion(Regions.SUFFOLK, OS_NORFOLK);
            AddConversion(Regions.SUFFOLK, OS_SUFFOLK);
            AddConversion(Regions.SURREY, OS_BRACKNELL_FOREST);
            AddConversion(Regions.SURREY, OS_BROMLEY);
            AddConversion(Regions.SURREY, OS_CROYDON);
            AddConversion(Regions.SURREY, OS_EAST_SUSSEX);
            AddConversion(Regions.SURREY, OS_HAMPSHIRE);
            AddConversion(Regions.SURREY, OS_HOUNSLOW);
            AddConversion(Regions.SURREY, OS_ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.SURREY, OS_KINGSTON_UPON_THAMES);
            AddConversion(Regions.SURREY, OS_KENT);
            AddConversion(Regions.SURREY, OS_LAMBETH);
            AddConversion(Regions.SURREY, OS_CITY_OF_LONDON);
            AddConversion(Regions.SURREY, OS_LEWISHAM);
            AddConversion(Regions.SURREY, OS_MERTON);
            AddConversion(Regions.SURREY, OS_RICHMOND_UPON_THAMES);
            AddConversion(Regions.SURREY, OS_SURREY);
            AddConversion(Regions.SURREY, OS_SOUTHWARK);
            AddConversion(Regions.SURREY, OS_SUTTON);
            AddConversion(Regions.SURREY, OS_TOWER_HAMLETS);
            AddConversion(Regions.SURREY, OS_WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.SURREY, OS_CITY_OF_WESTMINSTER);
            AddConversion(Regions.SURREY, OS_WEST_SUSSEX);
            AddConversion(Regions.SURREY, OS_WANDSWORTH);
            AddConversion(Regions.SUSSEX, OS_CITY_OF_BRIGHTON_AND_HOVE);
            AddConversion(Regions.SUSSEX, OS_EAST_SUSSEX);
            AddConversion(Regions.SUSSEX, OS_HAMPSHIRE);
            AddConversion(Regions.SUSSEX, OS_KENT);
            AddConversion(Regions.SUSSEX, OS_SURREY);
            AddConversion(Regions.SUSSEX, OS_WEST_SUSSEX);
            AddConversion(Regions.WARWICK, OS_BIRMINGHAM);
            AddConversion(Regions.WARWICK, OS_BUCKINGHAMSHIRE);
            AddConversion(Regions.WARWICK, OS_COVENTRY);
            AddConversion(Regions.WARWICK, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.WARWICK, OS_LEICESTERSHIRE);
            AddConversion(Regions.WARWICK, OS_NORTHAMPTONSHIRE);
            AddConversion(Regions.WARWICK, OS_OXFORDSHIRE);
            AddConversion(Regions.WARWICK, OS_STAFFORDSHIRE);
            AddConversion(Regions.WARWICK, OS_SOLIHULL);
            AddConversion(Regions.WARWICK, OS_WARWICKSHIRE);
            AddConversion(Regions.WARWICK, OS_WORCESTERSHIRE);
            AddConversion(Regions.WEST_GLAMORGAN, OS_SWANSEA);
            AddConversion(Regions.WEST_YORKSHIRE, OS_BRADFORD);
            AddConversion(Regions.WEST_YORKSHIRE, OS_BARNSLEY);
            AddConversion(Regions.WEST_YORKSHIRE, OS_CALDERDALE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_CHESHIRE_EAST);
            AddConversion(Regions.WEST_YORKSHIRE, OS_CUMBRIA);
            AddConversion(Regions.WEST_YORKSHIRE, OS_DONCASTER);
            AddConversion(Regions.WEST_YORKSHIRE, OS_DURHAM);
            AddConversion(Regions.WEST_YORKSHIRE, OS_DERBYSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_KIRKLEES);
            AddConversion(Regions.WEST_YORKSHIRE, OS_LANCASHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_LEEDS);
            AddConversion(Regions.WEST_YORKSHIRE, OS_MANCHESTER);
            AddConversion(Regions.WEST_YORKSHIRE, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_OLDHAM);
            AddConversion(Regions.WEST_YORKSHIRE, OS_ROCHDALE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_ROTHERHAM);
            AddConversion(Regions.WEST_YORKSHIRE, OS_SHEFFIELD);
            AddConversion(Regions.WEST_YORKSHIRE, OS_TAMESIDE);
            AddConversion(Regions.WEST_YORKSHIRE, OS_WAKEFIELD);
            AddConversion(Regions.WEST_YORKSHIRE, OS_YORK);
            AddConversion(Regions.WESTMORLAND, OS_CUMBRIA);
            AddConversion(Regions.WESTMORLAND, OS_DURHAM);
            AddConversion(Regions.WESTMORLAND, OS_LANCASHIRE);
            AddConversion(Regions.WILTS, OS_BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.WILTS, OS_DORSET);
            AddConversion(Regions.WILTS, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.WILTS, OS_HAMPSHIRE);
            AddConversion(Regions.WILTS, OS_OXFORDSHIRE);
            AddConversion(Regions.WILTS, OS_SWINDON);
            AddConversion(Regions.WILTS, OS_SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.WILTS, OS_SOMERSET);
            AddConversion(Regions.WILTS, OS_WEST_BERKSHIRE);
            AddConversion(Regions.WILTS, OS_WILTSHIRE);
            AddConversion(Regions.WORCESTER, OS_BIRMINGHAM);
            AddConversion(Regions.WORCESTER, OS_DUDLEY);
            AddConversion(Regions.WORCESTER, OS_GLOUCESTERSHIRE);
            AddConversion(Regions.WORCESTER, OS_HEREFORDSHIRE);
            AddConversion(Regions.WORCESTER, OS_SANDWELL);
            AddConversion(Regions.WORCESTER, OS_STAFFORDSHIRE);
            AddConversion(Regions.WORCESTER, OS_SHROPSHIRE);
            AddConversion(Regions.WORCESTER, OS_SOLIHULL);
            AddConversion(Regions.WORCESTER, OS_WARWICKSHIRE);
            AddConversion(Regions.WORCESTER, OS_WORCESTERSHIRE);
            AddConversion(Regions.YORKS, OS_BRADFORD);
            AddConversion(Regions.YORKS, OS_BARNSLEY);
            AddConversion(Regions.YORKS, OS_CALDERDALE);
            AddConversion(Regions.YORKS, OS_CUMBRIA);
            AddConversion(Regions.YORKS, OS_DARLINGTON);
            AddConversion(Regions.YORKS, OS_DONCASTER);
            AddConversion(Regions.YORKS, OS_DURHAM);
            AddConversion(Regions.YORKS, OS_DERBYSHIRE);
            AddConversion(Regions.YORKS, OS_EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.YORKS, OS_CITY_OF_KINGSTON_UPON_HULL);
            AddConversion(Regions.YORKS, OS_KIRKLEES);
            AddConversion(Regions.YORKS, OS_LANCASHIRE);
            AddConversion(Regions.YORKS, OS_LEEDS);
            AddConversion(Regions.YORKS, OS_MANCHESTER);
            AddConversion(Regions.YORKS, OS_MIDDLESBROUGH);
            AddConversion(Regions.YORKS, OS_NORTH_LINCOLNSHIRE);
            AddConversion(Regions.YORKS, OS_NOTTINGHAMSHIRE);
            AddConversion(Regions.YORKS, OS_NORTH_YORKSHIRE);
            AddConversion(Regions.YORKS, OS_OLDHAM);
            AddConversion(Regions.YORKS, OS_REDCAR_AND_CLEVELAND);
            AddConversion(Regions.YORKS, OS_ROCHDALE);
            AddConversion(Regions.YORKS, OS_ROTHERHAM);
            AddConversion(Regions.YORKS, OS_STOCKTON_ON_TEES);
            AddConversion(Regions.YORKS, OS_SHEFFIELD);
            AddConversion(Regions.YORKS, OS_TAMESIDE);
            AddConversion(Regions.YORKS, OS_WAKEFIELD);
            AddConversion(Regions.YORKS, OS_YORK);
        }

        private static void AddConversion(Region region, County county)
        {
            List<County> counties;
 	        if(CONVERSIONS.ContainsKey(region))
                counties = CONVERSIONS[region];
            else
            {
                counties = new List<County>();
                CONVERSIONS.Add(region, counties);
            }
            counties.Add(county);
        }
    }
}
