using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FTAnalyzer.Mapping
{
    public class CountyConversion
    {
        public static readonly Dictionary<Region, List<County>> CONVERSIONS = new Dictionary<Region, List<County>>();
        public static readonly List<County> MODERN_COUNTIES;

        public class County
        {
            public string CountyCode { get; private set; }
            public string CountyName { get; private set; }

            public County(string code, string countyName)
            {
                CountyCode = code;
                CountyName = countyName;
            }

            public override string ToString()
            {
                return CountyCode + ": " + CountyName;
            }
        }

        public static List<County> GetCounties(Region lookup)
        {
            if (CONVERSIONS.ContainsKey(lookup))
                return CONVERSIONS[lookup];
            return new List<County>();
        }

        public static County GetCounty(string code)
        {
            return MODERN_COUNTIES.First(c => c.CountyCode.Equals(code));
        }

        public static County ABERDEENSHIRE = new County("AB", "Aberdeenshire");
        public static County ANGUS = new County("AG", "Angus");
        public static County ABERDEEN_CITY = new County("AN", "Aberdeen City");
        public static County ARGYLL_AND_BUTE = new County("AR", "Argyll and Bute");
        public static County BRADFORD = new County("BA", "Bradford");
        public static County BLACKBURN_WITH_DARWEN = new County("BB", "Blackburn with Darwen");
        public static County BRACKNELL_FOREST = new County("BC", "Bracknell Forest");
        public static County BARKING_AND_DAGENHAM = new County("BD", "Barking and Dagenham");
        public static County BRIDGEND = new County("BE", "Bridgend");
        public static County BEDFORDSHIRE = new County("BF", "Bedfordshire");
        public static County BLAENAU_GWENT = new County("BG", "Blaenau Gwent");
        public static County CITY_OF_BRIGHTON_AND_HOVE = new County("BH", "City of Brighton and Hove");
        public static County BIRMINGHAM = new County("BI", "Birmingham");
        public static County CENTRAL_BEDFORDSHIRE = new County("BK", "Central Bedfordshire"); // extra to gazetteer index
        public static County BARNSLEY = new County("BL", "Barnsley");
        public static County BUCKINGHAMSHIRE = new County("BM", "Buckinghamshire");
        public static County BARNET = new County("BN", "Barnet");
        public static County BOLTON = new County("BO", "Bolton");
        public static County BLACKPOOL = new County("BP", "Blackpool");
        public static County BROMLEY = new County("BR", "Bromley");
        public static County BATH_AND_NORTH_EAST_SOMERSET = new County("BS", "Bath and North East Somerset");
        public static County BRENT = new County("BT", "Brent");
        public static County BOURNEMOUTH = new County("BU", "Bournemouth");
        public static County BEXLEY = new County("BX", "Bexley");
        public static County BURY = new County("BY", "Bury");
        public static County BRISTOL = new County("BZ", "City of Bristol");
        public static County CALDERDALE = new County("CA", "Calderdale");
        public static County CAMBRIDGESHIRE = new County("CB", "Cambridgeshire");
        public static County CARDIFF = new County("CD", "Cardiff");
        public static County CEREDIGION = new County("CE", "Ceredigion");
        public static County CAERPHILLY = new County("CF", "Caerphilly");
        public static County CHESHIRE_EAST = new County("CH", "Cheshire East");
        public static County CHESHIRE_WEST_AND_CHESTER = new County("CC", "Cheshire West and Chester");
        public static County CLACKMANNANSHIRE = new County("CL", "Clackmannanshire");
        public static County CAMDEN = new County("CM", "Camden");
        public static County CORNWALL = new County("CN", "Cornwall");
        public static County CARMARTHENSHIRE = new County("CT", "Carmarthenshire");
        public static County CUMBRIA = new County("CU", "Cumbria");
        public static County COVENTRY = new County("CV", "Coventry");
        public static County CONWY = new County("CW", "Conwy");
        public static County CROYDON = new County("CY", "Croydon");
        public static County CITY_OF_DERBY = new County("DB", "City of Derby");
        public static County DUNDEE_CITY = new County("DD", "Dundee City");
        public static County DENBIGHSHIRE = new County("DE", "Denbighshire");
        public static County DUMFRIES_AND_GALLOWAY = new County("DG", "Dumfries and Galloway");
        public static County DARLINGTON = new County("DL", "Darlington");
        public static County DEVON = new County("DN", "Devon");
        public static County DONCASTER = new County("DR", "Doncaster");
        public static County DORSET = new County("DT", "Dorset");
        public static County DURHAM = new County("DU", "Durham");
        public static County DERBYSHIRE = new County("DY", "Derbyshire");
        public static County DUDLEY = new County("DZ", "Dudley");
        public static County EAST_AYRSHIRE = new County("EA", "East Ayrshire");
        public static County CITY_OF_EDINBURGH = new County("EB", "City of Edinburgh");
        public static County EAST_DUNBARTONSHIRE = new County("ED", "East Dunbartonshire");
        public static County EALING = new County("EG", "Ealing");
        public static County EAST_LOTHIAN = new County("EL", "East Lothian");
        public static County ENFIELD = new County("EN", "Enfield");
        public static County EAST_RENFREWSHIRE = new County("ER", "East Renfrewshire");
        public static County EAST_SUSSEX = new County("ES", "East Sussex");
        public static County ESSEX = new County("EX", "Essex");
        public static County EAST_RIDING_OF_YORKSHIRE = new County("EY", "East Riding of Yorkshire");
        public static County FALKIRK = new County("FA", "Falkirk");
        public static County FIFE = new County("FF", "Fife");
        public static County FLINTSHIRE = new County("FL", "Flintshire");
        public static County GATESHEAD = new County("GH", "Gateshead");
        public static County GLASGOW_CITY = new County("GL", "Glasgow City");
        public static County GLOUCESTERSHIRE = new County("GR", "Gloucestershire");
        public static County GREENWICH = new County("GW", "Greenwich");
        public static County GWYNEDD = new County("GY", "Gwynedd");
        public static County HALTON = new County("HA", "Halton");
        public static County HERTFORDSHIRE = new County("HD", "Hertfordshire");
        public static County HEREFORDSHIRE = new County("HE", "Herefordshire");
        public static County HAMMERSMITH_AND_FULHAM = new County("HF", "Hammersmith and Fulham");
        public static County HARINGEY = new County("HG", "Haringey");
        public static County HILLINGDON = new County("HI", "Hillingdon");
        public static County HIGHLAND = new County("HL", "Highland");
        public static County HACKNEY = new County("HN", "Hackney");
        public static County HAMPSHIRE = new County("HP", "Hampshire");
        public static County HARROW = new County("HR", "Harrow");
        public static County HOUNSLOW = new County("HS", "Hounslow");
        public static County HARTLEPOOL = new County("HT", "Hartlepool");
        public static County HAVERING = new County("HV", "Havering");
        public static County ISLE_OF_ANGLESEY = new County("IA", "Isle of Anglesey");
        public static County ISLINGTON = new County("IL", "Islington");
        public static County ISLE_OF_MAN = new County("IM", "Isle of Man");
        public static County INVERCLYDE = new County("IN", "Inverclyde");
        public static County ISLES_OF_SCILLY = new County("IS", "Isles of Scilly");
        public static County CITY_OF_INVERNESS = new County("IV", "City of Inverness");
        public static County ISLE_OF_WIGHT = new County("IW", "Isle of Wight");
        public static County ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA = new County("KC", "Royal Borough of Kensington and Chelsea");
        public static County KINGSTON_UPON_THAMES = new County("KG", "Kingston upon Thames");
        public static County CITY_OF_KINGSTON_UPON_HULL = new County("KH", "City of Kingston upon Hull");
        public static County KIRKLEES = new County("KL", "Kirklees");
        public static County KNOWSLEY = new County("KN", "Knowsley");
        public static County KENT = new County("KT", "Kent");
        public static County LANCASHIRE = new County("LA", "Lancashire");
        public static County LAMBETH = new County("LB", "Lambeth");
        public static County CITY_OF_LEICESTER = new County("LC", "City of Leicester");
        public static County LEEDS = new County("LD", "Leeds");
        public static County LINCOLNSHIRE = new County("LL", "Lincolnshire");
        public static County LUTON = new County("LN", "Luton");
        public static County CITY_OF_LONDON = new County("LO", "City of London");
        public static County LIVERPOOL = new County("LP", "Liverpool");
        public static County LEWISHAM = new County("LS", "Lewisham");
        public static County LEICESTERSHIRE = new County("LT", "Leicestershire");
        public static County MANCHESTER = new County("MA", "Manchester");
        public static County MIDDLESBROUGH = new County("MB", "Middlesbrough");
        public static County MEDWAY = new County("ME", "Medway");
        public static County MIDLOTHIAN = new County("MI", "Midlothian");
        public static County MILTON_KEYNES = new County("MK", "Milton Keynes");
        public static County MONMOUTHSHIRE = new County("MM", "Monmouthshire");
        public static County MORAY = new County("MO", "Moray");
        public static County MERTON = new County("MR", "Merton");
        public static County MERTHYR_TYDFIL = new County("MT", "Merthyr Tydfil");
        public static County NORTH_AYRSHIRE = new County("NA", "North Ayrshire");
        public static County NORTH_EAST_LINCOLNSHIRE = new County("NC", "North East Lincolnshire");
        public static County NORTHUMBERLAND = new County("ND", "Northumberland");
        public static County NEWPORT = new County("NE", "Newport");
        public static County CITY_OF_NOTTINGHAM = new County("NG", "City of Nottingham");
        public static County NEWHAM = new County("NH", "Newham");
        public static County NORTH_LINCOLNSHIRE = new County("NI", "North Lincolnshire");
        public static County NORFOLK = new County("NK", "Norfolk");
        public static County NORTH_LANARKSHIRE = new County("NL", "North Lanarkshire");
        public static County NORTHAMPTONSHIRE = new County("NN", "Northamptonshire");
        public static County NEATH_PORT_TALBOT = new County("NP", "Neath Port Talbot");
        public static County NORTH_TYNESIDE = new County("NR", "North Tyneside");
        public static County NORTH_SOMERSET = new County("NS", "North Somerset");
        public static County NOTTINGHAMSHIRE = new County("NT", "Nottinghamshire");
        public static County NEWCASTLE_UPON_TYNE = new County("NW", "Newcastle upon Tyne");
        public static County NORTH_YORKSHIRE = new County("NY", "North Yorkshire");
        public static County OLDHAM = new County("OH", "Oldham");
        public static County ORKNEY_ISLANDS = new County("OK", "Orkney Islands");
        public static County OXFORDSHIRE = new County("ON", "Oxfordshire");
        public static County PEMBROKESHIRE = new County("PB", "Pembrokeshire");
        public static County CITY_OF_PETERBOROUGH = new County("PE", "City of Peterborough");
        public static County PERTH_AND_KINROSS = new County("PK", "Perth and Kinross");
        public static County POOLE = new County("PL", "Poole");
        public static County CITY_OF_PORTSMOUTH = new County("PO", "City of Portsmouth");
        public static County POWYS = new County("PW", "Powys");
        public static County CITY_OF_PLYMOUTH = new County("PY", "City of Plymouth");
        public static County REDBRIDGE = new County("RB", "Redbridge");
        public static County REDCAR_AND_CLEVELAND = new County("RC", "Redcar and Cleveland");
        public static County ROCHDALE = new County("RD", "Rochdale");
        public static County RENFREWSHIRE = new County("RE", "Renfrewshire");
        public static County READING = new County("RG", "Reading");
        public static County RHONDDA_CYNON_TAFF = new County("RH", "Rhondda Cynon Taff");
        public static County RUTLAND = new County("RL", "Rutland");
        public static County ROTHERHAM = new County("RO", "Rotherham");
        public static County RICHMOND_UPON_THAMES = new County("RT", "Richmond upon Thames");
        public static County SANDWELL = new County("SA", "Sandwell");
        public static County SCOTTISH_BORDERS = new County("SB", "Scottish Borders");
        public static County SALFORD = new County("SC", "Salford");
        public static County SWINDON = new County("SD", "Swindon");
        public static County SEFTON = new County("SE", "Sefton");
        public static County STAFFORDSHIRE = new County("SF", "Staffordshire");
        public static County SOUTH_GLOUCESTERSHIRE = new County("SG", "South Gloucestershire");
        public static County SHROPSHIRE = new County("SH", "Shropshire");
        public static County SHETLAND_ISLANDS = new County("SI", "Shetland Islands");
        public static County CITY_OF_STOKE_ON_TRENT = new County("SJ", "City of Stoke-on-Trent");
        public static County SUFFOLK = new County("SK", "Suffolk");
        public static County SOUTH_LANARKSHIRE = new County("SL", "South Lanarkshire");
        public static County STOCKTON_ON_TEES = new County("SM", "Stockton-on-Tees");
        public static County ST_HELENS = new County("SN", "St Helens");
        public static County CITY_OF_SOUTHAMPTON = new County("SO", "City of Southampton");
        public static County SHEFFIELD = new County("SP", "Sheffield");
        public static County SOLIHULL = new County("SQ", "Solihull");
        public static County STIRLING = new County("SR", "Stirling");
        public static County SWANSEA = new County("SS", "Swansea");
        public static County SOMERSET = new County("ST", "Somerset");
        public static County SURREY = new County("SU", "Surrey");
        public static County SUNDERLAND = new County("SV", "Sunderland");
        public static County SOUTHWARK = new County("SW", "Southwark");
        public static County SOUTH_AYRSHIRE = new County("SX", "South Ayrshire");
        public static County SOUTH_TYNESIDE = new County("SY", "South Tyneside");
        public static County SUTTON = new County("SZ", "Sutton");
        public static County TORBAY = new County("TB", "Torbay");
        public static County TORFAEN = new County("TF", "Torfaen");
        public static County TOWER_HAMLETS = new County("TH", "Tower Hamlets");
        public static County TRAFFORD = new County("TR", "Trafford");
        public static County TAMESIDE = new County("TS", "Tameside");
        public static County THURROCK = new County("TU", "Thurrock");
        public static County VALE_OF_GLAMORGAN = new County("VG", "Vale of Glamorgan");
        public static County WALSALL = new County("WA", "Walsall");
        public static County WEST_BERKSHIRE = new County("WB", "West Berkshire");
        public static County WINDSOR_AND_MAIDENHEAD = new County("WC", "Windsor and Maidenhead");
        public static County WEST_DUNBARTONSHIRE = new County("WD", "West Dunbartonshire");
        public static County WAKEFIELD = new County("WE", "Wakefield");
        public static County WALTHAM_FOREST = new County("WF", "Waltham Forest");
        public static County WARRINGTON = new County("WG", "Warrington");
        public static County CITY_OF_WOLVERHAMPTON = new County("WH", "City of Wolverhampton");
        public static County WESTERN_ISLES = new County("WI", "Na h-Eileanan an Iar");
        public static County WOKINGHAM = new County("WJ", "Wokingham");
        public static County WARWICKSHIRE = new County("WK", "Warwickshire");
        public static County WEST_LOTHIAN = new County("WL", "West Lothian");
        public static County CITY_OF_WESTMINSTER = new County("WM", "City of Westminster");
        public static County WIGAN = new County("WN", "Wigan");
        public static County WORCESTERSHIRE = new County("WO", "Worcestershire");
        public static County TELFORD_AND_WREKIN = new County("WP", "Telford and Wrekin");
        public static County WIRRAL = new County("WR", "Wirral");
        public static County WEST_SUSSEX = new County("WS", "West Sussex");
        public static County WILTSHIRE = new County("WT", "Wiltshire");
        public static County WANDSWORTH = new County("WW", "Wandsworth");
        public static County WREXHAM = new County("WX", "Wrexham");
        public static County YORK = new County("YK", "York");
        public static County SOUTHEND_ON_SEA = new County("YS", "Southend-on-Sea");
        public static County SLOUGH = new County("YT", "Slough");
        public static County STOCKPORT = new County("YY", "Stockport");

        static CountyConversion()
        {
            AddConversion(Regions.CAITHNESS, HIGHLAND);
            AddConversion(Regions.SUTHERLAND, HIGHLAND);
            AddConversion(Regions.ROSS_CROMARTY, HIGHLAND);
            AddConversion(Regions.ROSS_CROMARTY, WESTERN_ISLES);
            AddConversion(Regions.INVERNESS, HIGHLAND);
            AddConversion(Regions.INVERNESS, ABERDEENSHIRE);
            AddConversion(Regions.INVERNESS, MORAY);
            AddConversion(Regions.INVERNESS, ARGYLL_AND_BUTE);
            AddConversion(Regions.INVERNESS, WESTERN_ISLES);
            AddConversion(Regions.NAIRN, HIGHLAND);
            AddConversion(Regions.NAIRN, MORAY);
            AddConversion(Regions.MORAY, MORAY);
            AddConversion(Regions.MORAY, ABERDEENSHIRE);
            AddConversion(Regions.MORAY, HIGHLAND);
            AddConversion(Regions.BANFF, MORAY);
            AddConversion(Regions.BANFF, ABERDEENSHIRE);
            AddConversion(Regions.ABERDEEN, ABERDEEN_CITY);
            AddConversion(Regions.ABERDEEN, ABERDEENSHIRE);
            AddConversion(Regions.ABERDEEN, MORAY);
            AddConversion(Regions.KINCARDINE, ABERDEENSHIRE);
            AddConversion(Regions.KINCARDINE, ABERDEEN_CITY);
            AddConversion(Regions.KINCARDINE, ANGUS);
            AddConversion(Regions.ANGUS, ANGUS);
            AddConversion(Regions.ANGUS, ABERDEENSHIRE);
            AddConversion(Regions.ANGUS, PERTH_AND_KINROSS);
            AddConversion(Regions.ANGUS, DUNDEE_CITY);
            AddConversion(Regions.PERTH, PERTH_AND_KINROSS);
            AddConversion(Regions.PERTH, STIRLING);
            AddConversion(Regions.PERTH, CLACKMANNANSHIRE);
            AddConversion(Regions.PERTH, FIFE);
            AddConversion(Regions.PERTH, ANGUS);
            AddConversion(Regions.PERTH, DUNDEE_CITY);
            AddConversion(Regions.ARGYLL, ARGYLL_AND_BUTE);
            AddConversion(Regions.ARGYLL, HIGHLAND);
            AddConversion(Regions.ARGYLL, PERTH_AND_KINROSS);
            AddConversion(Regions.ARGYLL, STIRLING);
            AddConversion(Regions.BUTE, ARGYLL_AND_BUTE);
            AddConversion(Regions.BUTE, NORTH_AYRSHIRE);
            AddConversion(Regions.AYR, EAST_AYRSHIRE);
            AddConversion(Regions.AYR, NORTH_AYRSHIRE);
            AddConversion(Regions.AYR, SOUTH_AYRSHIRE);
            AddConversion(Regions.RENFREW, GLASGOW_CITY);
            AddConversion(Regions.RENFREW, INVERCLYDE);
            AddConversion(Regions.RENFREW, RENFREWSHIRE);
            AddConversion(Regions.RENFREW, EAST_RENFREWSHIRE);
            AddConversion(Regions.DUNBARTON, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, WEST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, GLASGOW_CITY);
            AddConversion(Regions.DUNBARTON, NORTH_LANARKSHIRE);
            AddConversion(Regions.DUNBARTON, STIRLING);
            AddConversion(Regions.STIRLING, STIRLING);
            AddConversion(Regions.STIRLING, PERTH_AND_KINROSS);
            AddConversion(Regions.STIRLING, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.STIRLING, NORTH_LANARKSHIRE);
            AddConversion(Regions.STIRLING, FALKIRK);
            AddConversion(Regions.STIRLING, CLACKMANNANSHIRE);
            AddConversion(Regions.CLACKMANNAN, CLACKMANNANSHIRE);
            AddConversion(Regions.CLACKMANNAN, STIRLING);
            AddConversion(Regions.CLACKMANNAN, PERTH_AND_KINROSS);
            AddConversion(Regions.KINROSS, PERTH_AND_KINROSS);
            AddConversion(Regions.KINROSS, FIFE);
            AddConversion(Regions.KINROSS, CLACKMANNANSHIRE);
            AddConversion(Regions.FIFE, FIFE);
            AddConversion(Regions.FIFE, PERTH_AND_KINROSS);
            AddConversion(Regions.WEST_LOTHIAN, WEST_LOTHIAN);
            AddConversion(Regions.WEST_LOTHIAN, NORTH_LANARKSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, SOUTH_LANARKSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, CITY_OF_EDINBURGH);
            AddConversion(Regions.WEST_LOTHIAN, FALKIRK);
            AddConversion(Regions.WEST_LOTHIAN, SCOTTISH_BORDERS);
            AddConversion(Regions.MIDLOTHIAN, CITY_OF_EDINBURGH);
            AddConversion(Regions.MIDLOTHIAN, MIDLOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, WEST_LOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, SCOTTISH_BORDERS);
            AddConversion(Regions.EAST_LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.EAST_LOTHIAN, MIDLOTHIAN);
            AddConversion(Regions.EAST_LOTHIAN, CITY_OF_EDINBURGH);
            AddConversion(Regions.EAST_LOTHIAN, SCOTTISH_BORDERS);
            AddConversion(Regions.EAST_LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.BERWICK, SCOTTISH_BORDERS);
            AddConversion(Regions.BERWICK, EAST_LOTHIAN);
            AddConversion(Regions.BERWICK, MIDLOTHIAN);
            AddConversion(Regions.ROXBURGH, SCOTTISH_BORDERS);
            AddConversion(Regions.DUMFRIES, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.DUMFRIES, SCOTTISH_BORDERS);
            AddConversion(Regions.DUMFRIES, SOUTH_LANARKSHIRE);
            AddConversion(Regions.KIRKCUDBRIGHT, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.WIGTOWN, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.LANARK, GLASGOW_CITY);
            AddConversion(Regions.LANARK, NORTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, SOUTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.LANARK, SCOTTISH_BORDERS);
            AddConversion(Regions.LANARK, WEST_LOTHIAN);
            AddConversion(Regions.LANARK, EAST_RENFREWSHIRE);
            AddConversion(Regions.SELKIRK, SCOTTISH_BORDERS);
            AddConversion(Regions.PEEBLES, SCOTTISH_BORDERS);
            AddConversion(Regions.PEEBLES, SOUTH_LANARKSHIRE);
            AddConversion(Regions.PEEBLES, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.PEEBLES, MIDLOTHIAN);
            AddConversion(Regions.PEEBLES, WEST_LOTHIAN);
            AddConversion(Regions.ABERDEEN_CITY, ABERDEEN_CITY);
            AddConversion(Regions.ABERDEEN_CITY, ABERDEENSHIRE);
            AddConversion(Regions.ORKNEY, ORKNEY_ISLANDS);
            AddConversion(Regions.SHETLAND, SHETLAND_ISLANDS);
            AddConversion(Regions.BORDERS, SCOTTISH_BORDERS);

            #region Modern Counties - as per Gazetteer

            AddConversion(Regions.BARKING, BARKING_AND_DAGENHAM);
            AddConversion(Regions.BARNET, BARNET);
            AddConversion(Regions.BARNSLEY, BARNSLEY);
            AddConversion(Regions.BATH, BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.BEDS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BERKS, WEST_BERKSHIRE);
            AddConversion(Regions.BEXLEY, BEXLEY);
            AddConversion(Regions.BIRMINGHAM, BIRMINGHAM);
            AddConversion(Regions.BLACKBURN, BLACKBURN_WITH_DARWEN);
            AddConversion(Regions.BLACKPOOL, BLACKPOOL);
            AddConversion(Regions.BLAENAU_GWENT, BLAENAU_GWENT);
            AddConversion(Regions.BOLTON, BOLTON);
            AddConversion(Regions.BOURNEMOUTH, BOURNEMOUTH);
            AddConversion(Regions.BRACKNELL, BRACKNELL_FOREST);
            AddConversion(Regions.BRADFORD, BRADFORD);
            AddConversion(Regions.BRENT, BRENT);
            AddConversion(Regions.BRIDGEND, BRIDGEND);
            AddConversion(Regions.BRIGHTON, CITY_OF_BRIGHTON_AND_HOVE);
            AddConversion(Regions.BRISTOL, BRISTOL);
            AddConversion(Regions.BROMLEY, BROMLEY);
            AddConversion(Regions.BUCKS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BURY, BURY);
            AddConversion(Regions.BUTE, ARGYLL_AND_BUTE);
            AddConversion(Regions.CAERPHILLY, CAERPHILLY);
            AddConversion(Regions.CALDERDALE, CALDERDALE);
            AddConversion(Regions.CAMBS, CAMBRIDGESHIRE);
            AddConversion(Regions.CAMDEN, CAMDEN);
            AddConversion(Regions.CARDIFF, CARDIFF);
            AddConversion(Regions.CARMARTHEN, CARMARTHENSHIRE);
            AddConversion(Regions.CENTRAL_BEDFORDSHIRE, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.CEREDIGION, CEREDIGION);
            AddConversion(Regions.CHESHIRE, CHESHIRE_EAST);
            AddConversion(Regions.CHESHIRE, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.CLACKMANNAN, CLACKMANNANSHIRE);
            AddConversion(Regions.CONWY, CONWY);
            AddConversion(Regions.CORNWALL, CORNWALL);
            AddConversion(Regions.COVENTRY, COVENTRY);
            AddConversion(Regions.CROYDON, CROYDON);
            AddConversion(Regions.CUMBRIA, CUMBRIA);
            AddConversion(Regions.DARLINGTON, DARLINGTON);
            AddConversion(Regions.DENBIGH, DENBIGHSHIRE);
            AddConversion(Regions.DERBY, CITY_OF_DERBY);
            AddConversion(Regions.DERBY, DERBYSHIRE);
            AddConversion(Regions.DEVON, DEVON);
            AddConversion(Regions.DONCASTER, DONCASTER);
            AddConversion(Regions.DORSET, DORSET);
            AddConversion(Regions.DUDLEY, DUDLEY);
            AddConversion(Regions.DUMFRIES_GALLOWAY, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.DUNBARTON, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, WEST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNDEE_CITY, DUNDEE_CITY);
            AddConversion(Regions.DURHAM, DURHAM);
            AddConversion(Regions.EALING, EALING);
            AddConversion(Regions.EAST_AYRSHIRE, EAST_AYRSHIRE);
            AddConversion(Regions.EAST_DUNBARTONSHIRE, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.EAST_LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.EAST_RENFREW, EAST_RENFREWSHIRE);
            AddConversion(Regions.EAST_YORKSHIRE, EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.EAST_SUSSEX, EAST_SUSSEX);
            AddConversion(Regions.EDINBURGH_CITY, CITY_OF_EDINBURGH);
            AddConversion(Regions.ENFIELD, ENFIELD);
            AddConversion(Regions.ESSEX, ESSEX);
            AddConversion(Regions.FALKIRK, FALKIRK);
            AddConversion(Regions.FIFE, FIFE);
            AddConversion(Regions.FLINT, FLINTSHIRE);
            CONVERSIONS.Add(new County("Gateshead", GATESHEAD);
            CONVERSIONS.Add(new County("Glasgow City", GLASGOW_CITY);
            CONVERSIONS.Add(new County("Gloucestershire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Gloucestershire", SOUTH_GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Greenwich", GRENWICH);
            CONVERSIONS.Add(new County("Gwynedd", GWYNEDD);
            CONVERSIONS.Add(new County("Hackney", HACKNEY);
            CONVERSIONS.Add(new County("Halton", HALTON);
            CONVERSIONS.Add(new County("Hammersmith and Fulham", HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.HANTS, HAMPSHIRE);
            CONVERSIONS.Add(new County("Haringey", HARINGEY);
            CONVERSIONS.Add(new County("Harrow", HARROW);
            CONVERSIONS.Add(new County("Hartlepool", HARTLEPOOL);
            CONVERSIONS.Add(new County("Havering", HAVERING);
            CONVERSIONS.Add(new County("Herefordshire", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Hertfordshire", HERTFORDSHIRE);
            CONVERSIONS.Add(new County("Highland", HIGHLAND);
            CONVERSIONS.Add(new County("Hillingdon", "HI", "Hillingdon"));
            CONVERSIONS.Add(new County("Hounslow", "HS", "Hounslow"));
            CONVERSIONS.Add(new County("Hove", CITY_OF_BRIGHTON_AND_HOVE);
            CONVERSIONS.Add(new County("Inverclyde", INVERCLYDE);
            CONVERSIONS.Add(new County("Isle of Anglesey", ISLE_OF_ANGLESEY);
            CONVERSIONS.Add(new County("Isle of Man", "IM", "Isle of Man"));
            CONVERSIONS.Add(new County("Isle of Wight", "IW", "Isle of Wight"));
            CONVERSIONS.Add(new County("Isles of Scilly", "IS", "Isles of Scilly"));
            CONVERSIONS.Add(new County("Islington", "IL", "Islington"));
            CONVERSIONS.Add(new County("Kent", KENT);
            CONVERSIONS.Add(new County("Kingston upon Hull", "KH", "City of Kingston upon Hull"));
            CONVERSIONS.Add(new County("Kingston upon Thames", "KG", "Kingston upon Thames"));
            CONVERSIONS.Add(new County("Kirklees", "KL", "Kirklees"));
            CONVERSIONS.Add(new County("Knowsley", "KN", "Knowsley"));
            CONVERSIONS.Add(new County("Lambeth", "LB", "Lambeth"));
            AddConversion(Regions.LANARK, NORTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, SOUTH_LANARKSHIRE);
            CONVERSIONS.Add(new County("Lancashire", "LA", "Lancashire"));
            CONVERSIONS.Add(new County("Leeds", "LD", "Leeds"));
            CONVERSIONS.Add(new County("Leicester", "LC", "City of Leicester"));
            CONVERSIONS.Add(new County("Leicestershire", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Lewisham", "LS", "Lewisham"));
            CONVERSIONS.Add(new County("Lincolnshire", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Lincolnshire", "NC", "North East Lincolnshire"));
            CONVERSIONS.Add(new County("Lincolnshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("Liverpool", "LP", "Liverpool"));
            CONVERSIONS.Add(new County("London", "LO", "City of London"));
            CONVERSIONS.Add(new County("Lothian", EAST_LOTHIAN);
            CONVERSIONS.Add(new County("Lothian", WEST_LOTHIAN);
            CONVERSIONS.Add(new County("Luton", "LN", "Luton"));
            CONVERSIONS.Add(new County("Maidenhead", WINDSOR_AND_MAIDENHEAD);
            CONVERSIONS.Add(new County("Manchester", MANCHESTER);
            CONVERSIONS.Add(new County("Medway", "ME", "Medway"));
            CONVERSIONS.Add(new County("Merthyr Tydfil", "MT", "Merthyr Tydfil"));
            CONVERSIONS.Add(new County("Merton", "MR", "Merton"));
            CONVERSIONS.Add(new County("Middlesbrough", "MB", "Middlesbrough"));
            AddConversion(Regions.MIDLOTHIAN, MIDLOTHIAN);
            CONVERSIONS.Add(new County("Milton Keynes", MILTON_KEYNES
            CONVERSIONS.Add(new County("Monmouthshire", MONMOUTHSHIRE);
            AddConversion(Regions.MORAY, MORAY);
            CONVERSIONS.Add(new County("Na h-Eileanan an Iar", WESTERN_ISLES);
            CONVERSIONS.Add(new County("Neath Port Talbot", "NP", "Neath Port Talbot"));
            CONVERSIONS.Add(new County("Newcastle upon Tyne", "NW", "Newcastle upon Tyne"));
            CONVERSIONS.Add(new County("Newham", "NH", "Newham"));
            CONVERSIONS.Add(new County("Newport", "NE", "Newport"));
            CONVERSIONS.Add(new County("Norfolk", NORFOLK);
            CONVERSIONS.Add(new County("North Ayrshire", NORTH_AYRSHIRE);
            CONVERSIONS.Add(new County("North East Lincolnshire", "NC", "North East Lincolnshire"));
            CONVERSIONS.Add(new County("North Lanarkshire", NORTH_LANARKSHIRE
            CONVERSIONS.Add(new County("North Lincolnshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("North Somerset", "NS", "North Somerset"));
            CONVERSIONS.Add(new County("North Tyneside", "NR", "North Tyneside"));
            CONVERSIONS.Add(new County("North Yorkshire", "NY", "North Yorkshire"));
            CONVERSIONS.Add(new County("Northamptonshire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Northumberland", "ND", "Northumberland"));
            CONVERSIONS.Add(new County("Nottingham", "NG", "City of Nottingham"));
            CONVERSIONS.Add(new County("Nottinghamshire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("Oldham", OLDHAM);
            CONVERSIONS.Add(new County("Orkney Islands", ORKNEY_ISLANDS);
            CONVERSIONS.Add(new County("Oxfordshire", OXFORDSHIRE);
            CONVERSIONS.Add(new County("Pembrokeshire", PEMBROKESHIRE);
            CONVERSIONS.Add(new County("Perth and Kinross", PERTH_AND_KINROSS);
            CONVERSIONS.Add(new County("Peterborough", CITY_OF_PETERBOROUGH);
            CONVERSIONS.Add(new County("Plymouth", "PY", "City of Plymouth"));
            CONVERSIONS.Add(new County("Poole", "PL", "Poole"));
            CONVERSIONS.Add(new County("Portsmouth", "PO", "City of Portsmouth"));
            CONVERSIONS.Add(new County("Powys", POWYS);
            CONVERSIONS.Add(new County("Reading", "RG", "Reading"));
            CONVERSIONS.Add(new County("Redbridge", "RB", "Redbridge"));
            CONVERSIONS.Add(new County("Redcar and Cleveland", "RC", "Redcar and Cleveland"));
            AddConversion(Regions.RENFREW, EAST_RENFREWSHIRE);
            AddConversion(Regions.RENFREW, RENFREWSHIRE);
            CONVERSIONS.Add(new County("Rhondda", "RH", "Rhondda,Cynon,Taff"));
            CONVERSIONS.Add(new County("Richmond upon Thames", "RT", "Richmond upon Thames"));
            CONVERSIONS.Add(new County("Rochdale", "RD", "Rochdale"));
            CONVERSIONS.Add(new County("Rotherham", "RO", "Rotherham"));
            CONVERSIONS.Add(new County("Royal Borough of Kensington and Chelsea", "KC", "Royal Borough of Kensington and Chelsea"));
            CONVERSIONS.Add(new County("Rutland", "RL", "Rutland"));
            CONVERSIONS.Add(new County("Salford", "SC", "Salford"));
            CONVERSIONS.Add(new County("Sandwell", "SA", "Sandwell"));
            CONVERSIONS.Add(new County("Scottish Borders", SCOTTISH_BORDERS);
            CONVERSIONS.Add(new County("Sefton", "SE", "Sefton"));
            CONVERSIONS.Add(new County("Sheffield", "SP", "Sheffield"));
            CONVERSIONS.Add(new County("Shetland Islands", SHETLAND_ISLANDS);
            CONVERSIONS.Add(new County("Shropshire", SHROPSHIRE);
            CONVERSIONS.Add(new County("Slough", SLOUGH);
            CONVERSIONS.Add(new County("Solihull", "SQ", "Solihull"));
            CONVERSIONS.Add(new County("Somerset", BATH_AND_NORTH_EAST_SOMERSET);
            CONVERSIONS.Add(new County("Somerset", "NS", "North Somerset"));
            CONVERSIONS.Add(new County("Somerset", "ST", "Somerset"));
            CONVERSIONS.Add(new County("South Ayrshire", SOUTH_AYRSHIRE);
            CONVERSIONS.Add(new County("South Gloucestershire", SOUTH_GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("South Lanarkshire", SOUTH_LANARKSHIRE);
            CONVERSIONS.Add(new County("South Tyneside", "SY", "South Tyneside"));
            CONVERSIONS.Add(new County("Southampton", "SO", "City of Southampton"));
            CONVERSIONS.Add(new County("Southend-on-Sea", "YS", "Southend-on-Sea"));
            CONVERSIONS.Add(new County("Southwark", "SW", "Southwark"));
            CONVERSIONS.Add(new County("St Helens", "SN", "St Helens"));
            CONVERSIONS.Add(new County("Staffordshire", STAFFORDSHIRE);
            CONVERSIONS.Add(new County("Stirling", STIRLING);
            CONVERSIONS.Add(new County("Stockport", STOCKPORT);
            CONVERSIONS.Add(new County("Stockton on Tees", "SM", "Stockton on Tees"));
            CONVERSIONS.Add(new County("Stoke-on-Trent", "SJ", "City of Stoke-on-Trent"));
            CONVERSIONS.Add(new County("Suffolk", SUFFOLK);
            CONVERSIONS.Add(new County("Sunderland", "SV", "Sunderland"));
            CONVERSIONS.Add(new County("Surrey", SURREY);
            CONVERSIONS.Add(new County("Sussex", EAST_SUSSEX);
            CONVERSIONS.Add(new County("Sussex", "WS", "West Sussex"));
            CONVERSIONS.Add(new County("Sutton", "SZ", "Sutton"));
            CONVERSIONS.Add(new County("Swansea", SWANSEA);
            CONVERSIONS.Add(new County("Swindon", "SD", "Swindon"));
            CONVERSIONS.Add(new County("Tameside", TAMESIDE);
            CONVERSIONS.Add(new County("Telford and Wrekin", "WP", "Telford and Wrekin"));
            CONVERSIONS.Add(new County("Thurrock", "TU", "Thurrock"));
            CONVERSIONS.Add(new County("Torbay", "TB", "Torbay"));
            CONVERSIONS.Add(new County("Torfaen", "TF", "Torfaen"));
            CONVERSIONS.Add(new County("Tower Hamlets", "TH", "Tower Hamlets"));
            CONVERSIONS.Add(new County("Trafford", TRAFFORD);
            CONVERSIONS.Add(new County("Vale of Glamorgan", "VG", "The Vale of Glamorgan"));
            CONVERSIONS.Add(new County("Wakefield", "WE", "Wakefield"));
            CONVERSIONS.Add(new County("Walsall", "WA", "Walsall"));
            CONVERSIONS.Add(new County("Waltham Forest", "WF", "Waltham Forest"));
            CONVERSIONS.Add(new County("Wandsworth", "WW", "Wandsworth"));
            CONVERSIONS.Add(new County("Warrington", WARRINGTON);
            CONVERSIONS.Add(new County("Warwickshire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("West Berkshire", WEST_BERKSHIRE);
            CONVERSIONS.Add(new County("West Dunbartonshire", WEST_DUNBARTONSHIRE
            AddConversion(Regions.WEST_LOTHIAN, WEST_LOTHIAN);
            CONVERSIONS.Add(new County("West Sussex", "WS", "West Sussex"));
            CONVERSIONS.Add(new County("Western Isles", WESTERN_ISLES);
            CONVERSIONS.Add(new County("Westminster", "WM", "City of Westminster"));
            CONVERSIONS.Add(new County("Wigan", "WN", "Wigan"));
            CONVERSIONS.Add(new County("Wiltshire", WILTSHIRE);
            CONVERSIONS.Add(new County("Windsor and Maidenhead", WINDSOR_AND_MAIDENHEAD);
            CONVERSIONS.Add(new County("Wirral", WIRRAL);
            CONVERSIONS.Add(new County("Wokingham", WOKINGHAM);
            CONVERSIONS.Add(new County("Wolverhampton", "WH", "City of Wolverhampton"));
            CONVERSIONS.Add(new County("Worcestershire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("Wrexham", WREXHAM);
            CONVERSIONS.Add(new County("York", "YK", "York"));
            #endregion

            // Alternate names for Modern Counties
            //CONVERSIONS.Add(new County("Barking", BARKING_AND_DAGENHAM);
            //CONVERSIONS.Add(new County("Bath", BATH_AND_NORTH_EAST_SOMERSET);
            //CONVERSIONS.Add(new County("Bedford", BEDFORD);
            //CONVERSIONS.Add(new County("Blackburn", BLACKBURN_WITH_DARWEN);
            //CONVERSIONS.Add(new County("Brighton", CITY_OF_BRIGHTON_AND_HOVE);
            //CONVERSIONS.Add(new County("Bristol", BRISTOL);
            //CONVERSIONS.Add(new County("Chelsea", "KC", "Royal Borough of Kensington and Chelsea"));
            //CONVERSIONS.Add(new County("Chester", CHESHIRE_WEST_AND_CHESTER);
            //CONVERSIONS.Add(new County("Hammersmith", HAMMERSMITH_AND_FULHAM);
            //CONVERSIONS.Add(new County("Kensington and Chelsea", "KC", "Royal Borough of Kensington and Chelsea"));
            //CONVERSIONS.Add(new County("Kensington", "KC", "Royal Borough of Kensington and Chelsea"));
            //CONVERSIONS.Add(new County("Telford", "WP", "Telford and Wrekin"));
            //CONVERSIONS.Add(new County("Tyneside", "NR", "North Tyneside"));
            //CONVERSIONS.Add(new County("Tyneside", "SY", "South Tyneside"));
            //CONVERSIONS.Add(new County("Warwickshire", BIRMINGHAM);
            //CONVERSIONS.Add(new County("Windsor", WINDSOR_AND_MAIDENHEAD);
            //CONVERSIONS.Add(new County("Wrekin", "WP", "Telford and Wrekin"));

            // from parish maps
            CONVERSIONS.Add(new County("Anglesey", ISLE_OF_ANGLESEY);
            AddConversion(Regions.BEDS, BEDFORD);
            AddConversion(Regions.BEDS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BEDS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BEDS, CAMBRIDGESHIRE);
            AddConversion(Regions.BEDS, HERTFORDSHIRE);
            AddConversion(Regions.BEDS, "LN", "Luton"));
            AddConversion(Regions.BEDS, MILTON_KEYNES
            AddConversion(Regions.BERKS, BRACKNELL_FOREST);
            AddConversion(Regions.BERKS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BERKS, GLOUCESTERSHIRE);
            AddConversion(Regions.BERKS, HAMPSHIRE);
            AddConversion(Regions.BERKS, OXFORDSHIRE);
            AddConversion(Regions.BERKS, "RG", "Reading"));
            AddConversion(Regions.BERKS, "SD", "Swindon"));
            AddConversion(Regions.BERKS, SURREY);
            AddConversion(Regions.BERKS, WEST_BERKSHIRE);
            AddConversion(Regions.BERKS, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.BERKS, WOKINGHAM);
            AddConversion(Regions.BERKS, WILTSHIRE);
            AddConversion(Regions.BRECON, BLAENAU_GWENT);
            AddConversion(Regions.BRECON, CEREDIGION);
            AddConversion(Regions.BRECON, CAERPHILLY);
            AddConversion(Regions.BRECON, CARMARTHENSHIRE);
            AddConversion(Regions.BRECON, HEREFORDSHIRE);
            AddConversion(Regions.BRECON, MONMOUTHSHIRE);
            AddConversion(Regions.BRECON, "MT", "Merthyr Tydfil"));
            AddConversion(Regions.BRECON, "NP", "Neath Port Talbot"));
            AddConversion(Regions.BRECON, POWYS);
            AddConversion(Regions.BRECON, "RH", "Rhondda,Cynon,Taff"));
            AddConversion(Regions.BRECON, "TF", "Torfaen"));
            AddConversion(Regions.BUCKS, BEDFORD);
            AddConversion(Regions.BUCKS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BUCKS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BUCKS, HERTFORDSHIRE);
            AddConversion(Regions.BUCKS, MILTON_KEYNES
            AddConversion(Regions.BUCKS, NORTHAMPTONSHIRE);
            AddConversion(Regions.BUCKS, OXFORDSHIRE);
            AddConversion(Regions.BUCKS, SURREY);
            AddConversion(Regions.BUCKS, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.BUCKS, WOKINGHAM);
            AddConversion(Regions.BUCKS, SLOUGH);
            AddConversion(Regions.CAERNARFON, CONWY);
            AddConversion(Regions.CAERNARFON, GWYNEDD);
            AddConversion(Regions.CAERNARFON, ISLE_OF_ANGLESEY);
            AddConversion(Regions.CAMBS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.CAMBS, CAMBRIDGESHIRE);
            AddConversion(Regions.CAMBS, ESSEX);
            AddConversion(Regions.CAMBS, HERTFORDSHIRE);
            AddConversion(Regions.CAMBS, LINCOLNSHIRE);
            AddConversion(Regions.CAMBS, NORFOLK);
            AddConversion(Regions.CAMBS, CITY_OF_PETERBOROUGH);
            AddConversion(Regions.CAMBS, SUFFOLK);
            AddConversion(Regions.CEREDIGION, CEREDIGION);
            AddConversion(Regions.CEREDIGION, CARMARTHENSHIRE);
            AddConversion(Regions.CEREDIGION, GWYNEDD);
            AddConversion(Regions.CEREDIGION, PEMBROKESHIRE);
            AddConversion(Regions.CEREDIGION, POWYS);
            AddConversion(Regions.CARMARTHEN, CEREDIGION);
            AddConversion(Regions.CARMARTHEN, CARMARTHENSHIRE);
            AddConversion(Regions.CARMARTHEN, "NP", "Neath Port Talbot"));
            AddConversion(Regions.CARMARTHEN, PEMBROKESHIRE);
            AddConversion(Regions.CARMARTHEN, POWYS);
            AddConversion(Regions.CARMARTHEN, SWANSEA);
            AddConversion(Regions.CHESHIRE, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.CHESHIRE, CHESHIRE_EAST);
            AddConversion(Regions.CHESHIRE, DERBYSHIRE);
            AddConversion(Regions.CHESHIRE, FLINTSHIRE);
            AddConversion(Regions.CHESHIRE, HALTON);
            AddConversion(Regions.CHESHIRE, MANCHESTER);
            AddConversion(Regions.CHESHIRE, OLDHAM);
            AddConversion(Regions.CHESHIRE, STAFFORDSHIRE);
            AddConversion(Regions.CHESHIRE, SHROPSHIRE);
            AddConversion(Regions.CHESHIRE, TRAFFORD);
            AddConversion(Regions.CHESHIRE, TAMESIDE);
            AddConversion(Regions.CHESHIRE, WARRINGTON);
            AddConversion(Regions.CHESHIRE, WIRRAL);
            AddConversion(Regions.CHESHIRE, WREXHAM);
            AddConversion(Regions.CHESHIRE, STOCKPORT);
            AddConversion(Regions.CORNWALL, CORNWALL);
            AddConversion(Regions.CORNWALL, DEVON);
            AddConversion(Regions.DURHAM, CUMBRIA);
            AddConversion(Regions.DURHAM, DARLINGTON);
            AddConversion(Regions.DURHAM, DURHAM);
            AddConversion(Regions.DURHAM, GATESHEAD);
            AddConversion(Regions.DURHAM, HARTLEPOOL);
            AddConversion(Regions.DURHAM, "MB", "Middlesbrough"));
            AddConversion(Regions.DURHAM, "ND", "Northumberland"));
            AddConversion(Regions.DURHAM, "NR", "North Tyneside"));
            AddConversion(Regions.DURHAM, "NW", "Newcastle upon Tyne"));
            AddConversion(Regions.DURHAM, "NY", "North Yorkshire"));
            AddConversion(Regions.DURHAM, "SM", "Stockton on Tees"));
            AddConversion(Regions.DURHAM, "SV", "Sunderland"));
            AddConversion(Regions.DURHAM, "SY", "South Tyneside"));
            AddConversion(Regions.CUMBERLAND, CUMBRIA);
            AddConversion(Regions.CUMBERLAND, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.CUMBERLAND, "ND", "Northumberland"));
            AddConversion(Regions.CUMBERLAND, SCOTTISH_BORDERS);
            AddConversion(Regions.DENBIGH, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.DENBIGH, CONWY);
            AddConversion(Regions.DENBIGH, DENBIGHSHIRE);
            AddConversion(Regions.DENBIGH, FLINTSHIRE);
            AddConversion(Regions.DENBIGH, GWYNEDD);
            AddConversion(Regions.DENBIGH, POWYS);
            AddConversion(Regions.DENBIGH, SHROPSHIRE);
            AddConversion(Regions.DENBIGH, WREXHAM);
            AddConversion(Regions.DERBY, CHESHIRE_EAST);
            AddConversion(Regions.DERBY, CITY_OF_DERBY);
            AddConversion(Regions.DERBY, DERBYSHIRE);
            AddConversion(Regions.DERBY, "LT", "Leicestershire"));
            AddConversion(Regions.DERBY, "NT", "Nottinghamshire"));
            AddConversion(Regions.DERBY, STAFFORDSHIRE);
            AddConversion(Regions.DERBY, "SP", "Sheffield"));
            AddConversion(Regions.DERBY, TAMESIDE);
            AddConversion(Regions.DERBY, STOCKPORT);
            AddConversion(Regions.DEVON, CORNWALL);
            AddConversion(Regions.DEVON, DEVON);
            AddConversion(Regions.DEVON, HAMPSHIRE);
            AddConversion(Regions.DEVON, "PY", "City of Plymouth"));
            AddConversion(Regions.DEVON, "ST", "Somerset"));
            AddConversion(Regions.DEVON, "TB", "Torbay"));
            AddConversion(Regions.DORSET, BOURNEMOUTH);
            AddConversion(Regions.DORSET, DEVON);
            AddConversion(Regions.DORSET, DORSET);
            AddConversion(Regions.DORSET, "PL", "Poole"));
            AddConversion(Regions.DORSET, "ST", "Somerset"));
            AddConversion(Regions.DORSET, WILTSHIRE);
            AddConversion(Regions.DURHAM, CUMBRIA);
            AddConversion(Regions.DURHAM, DARLINGTON);
            AddConversion(Regions.DURHAM, DURHAM);
            AddConversion(Regions.DURHAM, GATESHEAD);
            AddConversion(Regions.DURHAM, HARTLEPOOL);
            AddConversion(Regions.DURHAM, "MB", "Middlesbrough"));
            AddConversion(Regions.DURHAM, "ND", "Northumberland"));
            AddConversion(Regions.DURHAM, "NR", "North Tyneside"));
            AddConversion(Regions.DURHAM, "NW", "Newcastle upon Tyne"));
            AddConversion(Regions.DURHAM, "NY", "North Yorkshire"));
            AddConversion(Regions.DURHAM, "SM", "Stockton on Tees"));
            AddConversion(Regions.DURHAM, "SV", "Sunderland"));
            AddConversion(Regions.DURHAM, "SY", "South Tyneside"));
            AddConversion(Regions.ESSEX, BARKING_AND_DAGENHAM);
            AddConversion(Regions.ESSEX, CAMBRIDGESHIRE);
            AddConversion(Regions.ESSEX, ENFIELD);
            AddConversion(Regions.ESSEX, ESSEX);
            AddConversion(Regions.ESSEX, GRENWICH);
            AddConversion(Regions.ESSEX, HERTFORDSHIRE);
            AddConversion(Regions.ESSEX, HAVERING);
            AddConversion(Regions.ESSEX, KENT);
            AddConversion(Regions.ESSEX, "ME", "Medway"));
            AddConversion(Regions.ESSEX, "NH", "Newham"));
            AddConversion(Regions.ESSEX, "RB", "Redbridge"));
            AddConversion(Regions.ESSEX, SUFFOLK);
            AddConversion(Regions.ESSEX, "TU", "Thurrock"));
            AddConversion(Regions.ESSEX, "WF", "Waltham Forest"));
            AddConversion(Regions.ESSEX, "YS", "Southend-on-Sea"));
            AddConversion(Regions.FLINT, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.FLINT, CONWY);
            AddConversion(Regions.FLINT, DENBIGHSHIRE);
            AddConversion(Regions.FLINT, FLINTSHIRE);
            AddConversion(Regions.FLINT, SHROPSHIRE);
            AddConversion(Regions.FLINT, WREXHAM);
            AddConversion(Regions.GLAMORGAN, BRIDGEND);
            AddConversion(Regions.GLAMORGAN, CARDIFF);
            AddConversion(Regions.GLAMORGAN, CAERPHILLY);
            AddConversion(Regions.GLAMORGAN, CARMARTHENSHIRE);
            AddConversion(Regions.GLAMORGAN, "MT", "Merthyr Tydfil"));
            AddConversion(Regions.GLAMORGAN, "NE", "Newport"));
            AddConversion(Regions.GLAMORGAN, "NP", "Neath Port Talbot"));
            AddConversion(Regions.GLAMORGAN, POWYS);
            AddConversion(Regions.GLAMORGAN, "RH", "Rhondda,Cynon,Taff"));
            AddConversion(Regions.GLAMORGAN, SWANSEA);
            AddConversion(Regions.GLAMORGAN, "VG", "The Vale of Glamorgan"));
            CONVERSIONS.Add(new County("Gloucestershire", BATH_AND_NORTH_EAST_SOMERSET);
            CONVERSIONS.Add(new County("Gloucestershire", BRISTOL);
            CONVERSIONS.Add(new County("Gloucestershire", DORSET);
            CONVERSIONS.Add(new County("Gloucestershire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Gloucestershire", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Gloucestershire", MONMOUTHSHIRE);
            CONVERSIONS.Add(new County("Gloucestershire", "NS", "North Somerset"));
            CONVERSIONS.Add(new County("Gloucestershire", OXFORDSHIRE);
            CONVERSIONS.Add(new County("Gloucestershire", "SD", "Swindon"));
            CONVERSIONS.Add(new County("Gloucestershire", SOUTH_GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Gloucestershire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Gloucestershire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("Gloucestershire", WILTSHIRE);
            AddConversion(Regions.HANTS, BOURNEMOUTH);
            AddConversion(Regions.HANTS, DORSET);
            AddConversion(Regions.HANTS, HALTON);
            AddConversion(Regions.HANTS, HAMPSHIRE);
            AddConversion(Regions.HANTS, "IW", "Isle of Wight"));
            AddConversion(Regions.HANTS, "PL", "Poole"));
            AddConversion(Regions.HANTS, "PO", "City of Portsmouth"));
            AddConversion(Regions.HANTS, "SO", "City of Southampton"));
            AddConversion(Regions.HANTS, SURREY);
            AddConversion(Regions.HANTS, WEST_BERKSHIRE);
            AddConversion(Regions.HANTS, WOKINGHAM);
            AddConversion(Regions.HANTS, "WS", "West Sussex"));
            AddConversion(Regions.HANTS, WILTSHIRE);
            CONVERSIONS.Add(new County("Herefordshire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Herefordshire", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Herefordshire", MONMOUTHSHIRE);
            CONVERSIONS.Add(new County("Herefordshire", POWYS);
            CONVERSIONS.Add(new County("Herefordshire", SHROPSHIRE);
            CONVERSIONS.Add(new County("Herefordshire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("Hertfordshire", CENTRAL_BEDFORDSHIRE);
            CONVERSIONS.Add(new County("Hertfordshire", BUCKINGHAMSHIRE);
            CONVERSIONS.Add(new County("Hertfordshire", BARNET);
            CONVERSIONS.Add(new County("Hertfordshire", ENFIELD);
            CONVERSIONS.Add(new County("Hertfordshire", ESSEX);
            CONVERSIONS.Add(new County("Hertfordshire", HERTFORDSHIRE);
            CONVERSIONS.Add(new County("Hertfordshire", "HI", "Hillingdon"));
            CONVERSIONS.Add(new County("Hertfordshire", HARROW);
            CONVERSIONS.Add(new County("Huntingdonshire", BEDFORD);
            CONVERSIONS.Add(new County("Huntingdonshire", CAMBRIDGESHIRE);
            CONVERSIONS.Add(new County("Huntingdonshire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Huntingdonshire", CITY_OF_PETERBOROUGH);
            CONVERSIONS.Add(new County("Kent", BROMLEY);
            CONVERSIONS.Add(new County("Kent", BEXLEY);
            CONVERSIONS.Add(new County("Kent", CROYDON);
            CONVERSIONS.Add(new County("Kent", EAST_SUSSEX);
            CONVERSIONS.Add(new County("Kent", GRENWICH);
            CONVERSIONS.Add(new County("Kent", HAVERING);
            CONVERSIONS.Add(new County("Kent", KENT);
            CONVERSIONS.Add(new County("Kent", "LS", "Lewisham"));
            CONVERSIONS.Add(new County("Kent", "ME", "Medway"));
            CONVERSIONS.Add(new County("Kent", "NH", "Newham"));
            CONVERSIONS.Add(new County("Kent", SURREY);
            CONVERSIONS.Add(new County("Kent", "TH", "Tower Hamlets"));
            CONVERSIONS.Add(new County("Kent", "TU", "Thurrock"));
            CONVERSIONS.Add(new County("Lancashire", BLACKBURN_WITH_DARWEN);
            CONVERSIONS.Add(new County("Lancashire", BOLTON);
            CONVERSIONS.Add(new County("Lancashire", BLACKPOOL);
            CONVERSIONS.Add(new County("Lancashire", BURY);
            CONVERSIONS.Add(new County("Lancashire", CALDERDALE);
            CONVERSIONS.Add(new County("Lancashire", CHESHIRE_EAST);
            CONVERSIONS.Add(new County("Lancashire", CUMBRIA);
            CONVERSIONS.Add(new County("Lancashire", HALTON);
            CONVERSIONS.Add(new County("Lancashire", "KN", "Knowsley"));
            CONVERSIONS.Add(new County("Lancashire", "LA", "Lancashire"));
            CONVERSIONS.Add(new County("Lancashire", "LP", "Liverpool"));
            CONVERSIONS.Add(new County("Lancashire", MANCHESTER);
            CONVERSIONS.Add(new County("Lancashire", "NY", "North Yorkshire"));
            CONVERSIONS.Add(new County("Lancashire", OLDHAM);
            CONVERSIONS.Add(new County("Lancashire", "RD", "Rochdale"));
            CONVERSIONS.Add(new County("Lancashire", "SC", "Salford"));
            CONVERSIONS.Add(new County("Lancashire", "SE", "Sefton"));
            CONVERSIONS.Add(new County("Lancashire", "SN", "St Helens"));
            CONVERSIONS.Add(new County("Lancashire", TRAFFORD);
            CONVERSIONS.Add(new County("Lancashire", TAMESIDE);
            CONVERSIONS.Add(new County("Lancashire", WARRINGTON);
            CONVERSIONS.Add(new County("Lancashire", "WN", "Wigan"));
            CONVERSIONS.Add(new County("Lancashire", STOCKPORT);
            CONVERSIONS.Add(new County("Leicestershire", DERBYSHIRE);
            CONVERSIONS.Add(new County("Leicestershire", "LC", "City of Leicester"));
            CONVERSIONS.Add(new County("Leicestershire", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Leicestershire", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Leicestershire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Leicestershire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("Leicestershire", "RL", "Rutland"));
            CONVERSIONS.Add(new County("Leicestershire", STAFFORDSHIRE);
            CONVERSIONS.Add(new County("Leicestershire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Lincolnshire", CAMBRIDGESHIRE);
            CONVERSIONS.Add(new County("Lincolnshire", DONCASTER);
            CONVERSIONS.Add(new County("Lincolnshire", EAST_RIDING_OF_YORKSHIRE);
            CONVERSIONS.Add(new County("Lincolnshire", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Lincolnshire", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Lincolnshire", "NC", "North East Lincolnshire"));
            CONVERSIONS.Add(new County("Lincolnshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("Lincolnshire", NORFOLK);
            CONVERSIONS.Add(new County("Lincolnshire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Lincolnshire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("Lincolnshire", CITY_OF_PETERBOROUGH);
            CONVERSIONS.Add(new County("Lincolnshire", "RL", "Rutland"));
            CONVERSIONS.Add(new County("London", BRACKNELL_FOREST);
            CONVERSIONS.Add(new County("London", BARNET);
            CONVERSIONS.Add(new County("London", BROMLEY);
            CONVERSIONS.Add(new County("London", BRENT);
            CONVERSIONS.Add(new County("London", CAMDEN);
            CONVERSIONS.Add(new County("London", CROYDON);
            CONVERSIONS.Add(new County("London", EALING);
            CONVERSIONS.Add(new County("London", ENFIELD);
            CONVERSIONS.Add(new County("London", EAST_SUSSEX);
            CONVERSIONS.Add(new County("London", ESSEX);
            CONVERSIONS.Add(new County("London", HAMMERSMITH_AND_FULHAM);
            CONVERSIONS.Add(new County("London", HARINGEY);
            CONVERSIONS.Add(new County("London", "HI", "Hillingdon"));
            CONVERSIONS.Add(new County("London", HACKNEY);
            CONVERSIONS.Add(new County("London", HARROW);
            CONVERSIONS.Add(new County("London", "HS", "Hounslow"));
            CONVERSIONS.Add(new County("London", "IL", "Islington"));
            CONVERSIONS.Add(new County("London", "KC", "Royal Borough of Kensington and Chelsea"));
            CONVERSIONS.Add(new County("London", "KG", "Kingston upon Thames"));
            CONVERSIONS.Add(new County("London", KENT);
            CONVERSIONS.Add(new County("London", "LB", "Lambeth"));
            CONVERSIONS.Add(new County("London", "LO", "City of London"));
            CONVERSIONS.Add(new County("London", "LS", "Lewisham"));
            CONVERSIONS.Add(new County("London", "MR", "Merton"));
            CONVERSIONS.Add(new County("London", "NH", "Newham"));
            CONVERSIONS.Add(new County("London", "RT", "Richmond upon Thames"));
            CONVERSIONS.Add(new County("London", SURREY);
            CONVERSIONS.Add(new County("London", "SW", "Southwark"));
            CONVERSIONS.Add(new County("London", "SZ", "Sutton"));
            CONVERSIONS.Add(new County("London", "TH", "Tower Hamlets"));
            CONVERSIONS.Add(new County("London", WINDSOR_AND_MAIDENHEAD);
            CONVERSIONS.Add(new County("London", "WM", "City of Westminster"));
            CONVERSIONS.Add(new County("London", "WS", "West Sussex"));
            CONVERSIONS.Add(new County("London", "WS", "West Sussex"));
            CONVERSIONS.Add(new County("London", "WW", "Wandsworth"));
            CONVERSIONS.Add(new County("London", "WW", "Wandsworth"));
            CONVERSIONS.Add(new County("Manchester", OLDHAM);
            CONVERSIONS.Add(new County("Manchester", OLDHAM);
            CONVERSIONS.Add(new County("Manchester", TAMESIDE);
            CONVERSIONS.Add(new County("Merioneth", CONWY);
            CONVERSIONS.Add(new County("Merioneth", DENBIGHSHIRE);
            CONVERSIONS.Add(new County("Merioneth", GWYNEDD);
            CONVERSIONS.Add(new County("Merioneth", POWYS);
            CONVERSIONS.Add(new County("Middlesex", BUCKINGHAMSHIRE);
            CONVERSIONS.Add(new County("Middlesex", BARNET);
            CONVERSIONS.Add(new County("Middlesex", BRENT);
            CONVERSIONS.Add(new County("Middlesex", CAMDEN);
            CONVERSIONS.Add(new County("Middlesex", EALING);
            CONVERSIONS.Add(new County("Middlesex", ENFIELD);
            CONVERSIONS.Add(new County("Middlesex", ESSEX);
            CONVERSIONS.Add(new County("Middlesex", HERTFORDSHIRE);
            CONVERSIONS.Add(new County("Middlesex", HAMMERSMITH_AND_FULHAM);
            CONVERSIONS.Add(new County("Middlesex", HARINGEY);
            CONVERSIONS.Add(new County("Middlesex", "HI", "Hillingdon"));
            CONVERSIONS.Add(new County("Middlesex", HACKNEY);
            CONVERSIONS.Add(new County("Middlesex", HARROW);
            CONVERSIONS.Add(new County("Middlesex", "HS", "Hounslow"));
            CONVERSIONS.Add(new County("Middlesex", "IL", "Islington"));
            CONVERSIONS.Add(new County("Middlesex", "KC", "Royal Borough of Kensington and Chelsea"));
            CONVERSIONS.Add(new County("Middlesex", "LB", "Lambeth"));
            CONVERSIONS.Add(new County("Middlesex", "LO", "City of London"));
            CONVERSIONS.Add(new County("Middlesex", "NH", "Newham"));
            CONVERSIONS.Add(new County("Middlesex", "RT", "Richmond upon Thames"));
            CONVERSIONS.Add(new County("Middlesex", SURREY);
            CONVERSIONS.Add(new County("Middlesex", "SW", "Southwark"));
            CONVERSIONS.Add(new County("Middlesex", "TH", "Tower Hamlets"));
            CONVERSIONS.Add(new County("Middlesex", WINDSOR_AND_MAIDENHEAD);
            CONVERSIONS.Add(new County("Middlesex", "WM", "City of Westminster"));
            CONVERSIONS.Add(new County("Middlesex", "WW", "Wandsworth"));
            CONVERSIONS.Add(new County("Monmouth", BLAENAU_GWENT);
            CONVERSIONS.Add(new County("Monmouth", CARDIFF);
            CONVERSIONS.Add(new County("Monmouth", CAERPHILLY);
            CONVERSIONS.Add(new County("Monmouth", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Monmouth", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Monmouth", MONMOUTHSHIRE);
            CONVERSIONS.Add(new County("Monmouth", "MT", "Merthyr Tydfil"));
            CONVERSIONS.Add(new County("Monmouth", "NE", "Newport"));
            CONVERSIONS.Add(new County("Monmouth", POWYS);
            CONVERSIONS.Add(new County("Monmouth", "RH", "Rhondda,Cynon,Taff"));
            CONVERSIONS.Add(new County("Monmouth", "TF", "Torfaen"));
            CONVERSIONS.Add(new County("Montgomery", CEREDIGION);
            CONVERSIONS.Add(new County("Montgomery", GWYNEDD);
            CONVERSIONS.Add(new County("Montgomery", POWYS);
            CONVERSIONS.Add(new County("Montgomery", SHROPSHIRE);
            CONVERSIONS.Add(new County("Norfolk", CAMBRIDGESHIRE);
            CONVERSIONS.Add(new County("Norfolk", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Norfolk", NORFOLK);
            CONVERSIONS.Add(new County("Norfolk", SUFFOLK);
            CONVERSIONS.Add(new County("North Yorkshire", DARLINGTON);
            CONVERSIONS.Add(new County("North Yorkshire", "MB", "Middlesbrough"));
            CONVERSIONS.Add(new County("North Yorkshire", "RC", "Redcar and Cleveland"));
            CONVERSIONS.Add(new County("North Yorkshire", "SM", "Stockton on Tees"));
            CONVERSIONS.Add(new County("Northamptonshire", BEDFORD);
            CONVERSIONS.Add(new County("Northamptonshire", BUCKINGHAMSHIRE);
            CONVERSIONS.Add(new County("Northamptonshire", CAMBRIDGESHIRE);
            CONVERSIONS.Add(new County("Northamptonshire", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Northamptonshire", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Northamptonshire", MILTON_KEYNES
            CONVERSIONS.Add(new County("Northamptonshire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Northamptonshire", OXFORDSHIRE);
            CONVERSIONS.Add(new County("Northamptonshire", CITY_OF_PETERBOROUGH);
            CONVERSIONS.Add(new County("Northamptonshire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Northumberland", CUMBRIA);
            CONVERSIONS.Add(new County("Northumberland", DURHAM);
            CONVERSIONS.Add(new County("Northumberland", GATESHEAD);
            CONVERSIONS.Add(new County("Northumberland", "ND", "Northumberland"));
            CONVERSIONS.Add(new County("Northumberland", "NR", "North Tyneside"));
            CONVERSIONS.Add(new County("Northumberland", "NW", "Newcastle upon Tyne"));
            CONVERSIONS.Add(new County("Northumberland", SCOTTISH_BORDERS);
            CONVERSIONS.Add(new County("Nottinghamshire", DONCASTER);
            CONVERSIONS.Add(new County("Nottinghamshire", DERBYSHIRE);
            CONVERSIONS.Add(new County("Nottinghamshire", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Nottinghamshire", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Nottinghamshire", "NG", "City of Nottingham"));
            CONVERSIONS.Add(new County("Nottinghamshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("Nottinghamshire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("Oxfordshire", BUCKINGHAMSHIRE);
            CONVERSIONS.Add(new County("Oxfordshire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Oxfordshire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Oxfordshire", OXFORDSHIRE);
            CONVERSIONS.Add(new County("Oxfordshire", "RG", "Reading"));
            CONVERSIONS.Add(new County("Oxfordshire", WEST_BERKSHIRE);
            CONVERSIONS.Add(new County("Oxfordshire", WOKINGHAM);
            CONVERSIONS.Add(new County("Oxfordshire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Pembroke", CEREDIGION);
            CONVERSIONS.Add(new County("Pembroke", CARMARTHENSHIRE);
            CONVERSIONS.Add(new County("Pembroke", PEMBROKESHIRE);
            CONVERSIONS.Add(new County("Radnor", CEREDIGION);
            CONVERSIONS.Add(new County("Radnor", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Radnor", POWYS);
            CONVERSIONS.Add(new County("Radnor", SHROPSHIRE);
            CONVERSIONS.Add(new County("Rutland", LINCOLNSHIRE);
            CONVERSIONS.Add(new County("Rutland", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Rutland", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Rutland", "RL", "Rutland"));
            CONVERSIONS.Add(new County("Shropshire", CHESHIRE_EAST);
            CONVERSIONS.Add(new County("Shropshire", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Shropshire", POWYS);
            CONVERSIONS.Add(new County("Shropshire", STAFFORDSHIRE);
            CONVERSIONS.Add(new County("Shropshire", SHROPSHIRE);
            CONVERSIONS.Add(new County("Shropshire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("Shropshire", "WP", "Telford and Wrekin"));
            CONVERSIONS.Add(new County("Shropshire", WREXHAM);
            CONVERSIONS.Add(new County("Somerset", BATH_AND_NORTH_EAST_SOMERSET);
            CONVERSIONS.Add(new County("Somerset", BRISTOL);
            CONVERSIONS.Add(new County("Somerset", DEVON);
            CONVERSIONS.Add(new County("Somerset", DORSET);
            CONVERSIONS.Add(new County("Somerset", "NS", "North Somerset"));
            CONVERSIONS.Add(new County("Somerset", SOUTH_GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Somerset", "ST", "Somerset"));
            CONVERSIONS.Add(new County("Somerset", WILTSHIRE);
            CONVERSIONS.Add(new County("South Yorkshire", BRADFORD);
            CONVERSIONS.Add(new County("South Yorkshire", BARNSLEY);
            CONVERSIONS.Add(new County("South Yorkshire", CALDERDALE);
            CONVERSIONS.Add(new County("South Yorkshire", CHESHIRE_EAST);
            CONVERSIONS.Add(new County("South Yorkshire", CUMBRIA);
            CONVERSIONS.Add(new County("South Yorkshire", DONCASTER);
            CONVERSIONS.Add(new County("South Yorkshire", DURHAM);
            CONVERSIONS.Add(new County("South Yorkshire", DERBYSHIRE);
            CONVERSIONS.Add(new County("South Yorkshire", EAST_RIDING_OF_YORKSHIRE);
            CONVERSIONS.Add(new County("South Yorkshire", "KL", "Kirklees"));
            CONVERSIONS.Add(new County("South Yorkshire", "LA", "Lancashire"));
            CONVERSIONS.Add(new County("South Yorkshire", "LD", "Leeds"));
            CONVERSIONS.Add(new County("South Yorkshire", MANCHESTER);
            CONVERSIONS.Add(new County("South Yorkshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("South Yorkshire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("South Yorkshire", "NY", "North Yorkshire"));
            CONVERSIONS.Add(new County("South Yorkshire", OLDHAM);
            CONVERSIONS.Add(new County("South Yorkshire", "RD", "Rochdale"));
            CONVERSIONS.Add(new County("South Yorkshire", "RO", "Rotherham"));
            CONVERSIONS.Add(new County("South Yorkshire", "SP", "Sheffield"));
            CONVERSIONS.Add(new County("South Yorkshire", TAMESIDE);
            CONVERSIONS.Add(new County("South Yorkshire", "WE", "Wakefield"));
            CONVERSIONS.Add(new County("South Yorkshire", "YK", "York"));
            CONVERSIONS.Add(new County("Staffordshire", BIRMINGHAM);
            CONVERSIONS.Add(new County("Staffordshire", CHESHIRE_EAST);
            CONVERSIONS.Add(new County("Staffordshire", DERBYSHIRE);
            CONVERSIONS.Add(new County("Staffordshire", DUDLEY);
            CONVERSIONS.Add(new County("Staffordshire", "SA", "Sandwell"));
            CONVERSIONS.Add(new County("Staffordshire", STAFFORDSHIRE);
            CONVERSIONS.Add(new County("Staffordshire", SHROPSHIRE);
            CONVERSIONS.Add(new County("Staffordshire", "SJ", "City of Stoke-on-Trent"));
            CONVERSIONS.Add(new County("Staffordshire", "SY", "South Tyneside"));
            CONVERSIONS.Add(new County("Staffordshire", "WA", "Walsall"));
            CONVERSIONS.Add(new County("Staffordshire", "WH", "City of Wolverhampton"));
            CONVERSIONS.Add(new County("Staffordshire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Staffordshire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("Suffolk", CAMBRIDGESHIRE);
            CONVERSIONS.Add(new County("Suffolk", ESSEX);
            CONVERSIONS.Add(new County("Suffolk", NORFOLK);
            CONVERSIONS.Add(new County("Suffolk", SUFFOLK);
            CONVERSIONS.Add(new County("Surrey", BRACKNELL_FOREST);
            CONVERSIONS.Add(new County("Surrey", BROMLEY);
            CONVERSIONS.Add(new County("Surrey", CROYDON);
            CONVERSIONS.Add(new County("Surrey", EAST_SUSSEX);
            CONVERSIONS.Add(new County("Surrey", HAMPSHIRE);
            CONVERSIONS.Add(new County("Surrey", "HS", "Hounslow"));
            CONVERSIONS.Add(new County("Surrey", "KC", "Royal Borough of Kensington and Chelsea"));
            CONVERSIONS.Add(new County("Surrey", "KG", "Kingston upon Thames"));
            CONVERSIONS.Add(new County("Surrey", KENT);
            CONVERSIONS.Add(new County("Surrey", "LB", "Lambeth"));
            CONVERSIONS.Add(new County("Surrey", "LO", "City of London"));
            CONVERSIONS.Add(new County("Surrey", "LS", "Lewisham"));
            CONVERSIONS.Add(new County("Surrey", "MR", "Merton"));
            CONVERSIONS.Add(new County("Surrey", "RT", "Richmond upon Thames"));
            CONVERSIONS.Add(new County("Surrey", SURREY);
            CONVERSIONS.Add(new County("Surrey", "SW", "Southwark"));
            CONVERSIONS.Add(new County("Surrey", "SZ", "Sutton"));
            CONVERSIONS.Add(new County("Surrey", "TH", "Tower Hamlets"));
            CONVERSIONS.Add(new County("Surrey", WINDSOR_AND_MAIDENHEAD);
            CONVERSIONS.Add(new County("Surrey", "WM", "City of Westminster"));
            CONVERSIONS.Add(new County("Surrey", "WS", "West Sussex"));
            CONVERSIONS.Add(new County("Surrey", "WW", "Wandsworth"));
            CONVERSIONS.Add(new County("Sussex", CITY_OF_BRIGHTON_AND_HOVE);
            CONVERSIONS.Add(new County("Sussex", EAST_SUSSEX);
            CONVERSIONS.Add(new County("Sussex", HAMPSHIRE);
            CONVERSIONS.Add(new County("Sussex", KENT);
            CONVERSIONS.Add(new County("Sussex", SURREY);
            CONVERSIONS.Add(new County("Sussex", "WS", "West Sussex"));
            CONVERSIONS.Add(new County("Warwickshire", BIRMINGHAM);
            CONVERSIONS.Add(new County("Warwickshire", BUCKINGHAMSHIRE);
            CONVERSIONS.Add(new County("Warwickshire", COVENTRY);
            CONVERSIONS.Add(new County("Warwickshire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Warwickshire", "LT", "Leicestershire"));
            CONVERSIONS.Add(new County("Warwickshire", NORTHAMPTONSHIRE);
            CONVERSIONS.Add(new County("Warwickshire", OXFORDSHIRE);
            CONVERSIONS.Add(new County("Warwickshire", STAFFORDSHIRE);
            CONVERSIONS.Add(new County("Warwickshire", "SQ", "Solihull"));
            CONVERSIONS.Add(new County("Warwickshire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Warwickshire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("West Glamorgan", SWANSEA);
            CONVERSIONS.Add(new County("West Yorkshire", BRADFORD);
            CONVERSIONS.Add(new County("West Yorkshire", BARNSLEY);
            CONVERSIONS.Add(new County("West Yorkshire", CALDERDALE);
            CONVERSIONS.Add(new County("West Yorkshire", CHESHIRE_EAST);
            CONVERSIONS.Add(new County("West Yorkshire", CUMBRIA);
            CONVERSIONS.Add(new County("West Yorkshire", DONCASTER);
            CONVERSIONS.Add(new County("West Yorkshire", DURHAM);
            CONVERSIONS.Add(new County("West Yorkshire", DERBYSHIRE);
            CONVERSIONS.Add(new County("West Yorkshire", EAST_RIDING_OF_YORKSHIRE);
            CONVERSIONS.Add(new County("West Yorkshire", "KL", "Kirklees"));
            CONVERSIONS.Add(new County("West Yorkshire", "LA", "Lancashire"));
            CONVERSIONS.Add(new County("West Yorkshire", "LD", "Leeds"));
            CONVERSIONS.Add(new County("West Yorkshire", MANCHESTER);
            CONVERSIONS.Add(new County("West Yorkshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("West Yorkshire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("West Yorkshire", "NY", "North Yorkshire"));
            CONVERSIONS.Add(new County("West Yorkshire", OLDHAM);
            CONVERSIONS.Add(new County("West Yorkshire", "RD", "Rochdale"));
            CONVERSIONS.Add(new County("West Yorkshire", "RO", "Rotherham"));
            CONVERSIONS.Add(new County("West Yorkshire", "SP", "Sheffield"));
            CONVERSIONS.Add(new County("West Yorkshire", TAMESIDE);
            CONVERSIONS.Add(new County("West Yorkshire", "WE", "Wakefield"));
            CONVERSIONS.Add(new County("West Yorkshire", "YK", "York"));
            CONVERSIONS.Add(new County("Westmorland", CUMBRIA);
            CONVERSIONS.Add(new County("Westmorland", DURHAM);
            CONVERSIONS.Add(new County("Westmorland", "LA", "Lancashire"));
            CONVERSIONS.Add(new County("Wiltshire", BATH_AND_NORTH_EAST_SOMERSET);
            CONVERSIONS.Add(new County("Wiltshire", DORSET);
            CONVERSIONS.Add(new County("Wiltshire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Wiltshire", HAMPSHIRE);
            CONVERSIONS.Add(new County("Wiltshire", OXFORDSHIRE);
            CONVERSIONS.Add(new County("Wiltshire", "SD", "Swindon"));
            CONVERSIONS.Add(new County("Wiltshire", SOUTH_GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Wiltshire", "ST", "Somerset"));
            CONVERSIONS.Add(new County("Wiltshire", WEST_BERKSHIRE);
            CONVERSIONS.Add(new County("Wiltshire", WILTSHIRE);
            CONVERSIONS.Add(new County("Worcestershire", BIRMINGHAM);
            CONVERSIONS.Add(new County("Worcestershire", DUDLEY);
            CONVERSIONS.Add(new County("Worcestershire", GLOUCESTERSHIRE);
            CONVERSIONS.Add(new County("Worcestershire", HEREFORDSHIRE);
            CONVERSIONS.Add(new County("Worcestershire", "SA", "Sandwell"));
            CONVERSIONS.Add(new County("Worcestershire", STAFFORDSHIRE);
            CONVERSIONS.Add(new County("Worcestershire", SHROPSHIRE);
            CONVERSIONS.Add(new County("Worcestershire", "SQ", "Solihull"));
            CONVERSIONS.Add(new County("Worcestershire", "WK", "Warwickshire"));
            CONVERSIONS.Add(new County("Worcestershire", "WO", "Worcestershire"));
            CONVERSIONS.Add(new County("Yorkshire", BRADFORD);
            CONVERSIONS.Add(new County("Yorkshire", BARNSLEY);
            CONVERSIONS.Add(new County("Yorkshire", CALDERDALE);
            CONVERSIONS.Add(new County("Yorkshire", CUMBRIA);
            CONVERSIONS.Add(new County("Yorkshire", DARLINGTON);
            CONVERSIONS.Add(new County("Yorkshire", DONCASTER);
            CONVERSIONS.Add(new County("Yorkshire", DURHAM);
            CONVERSIONS.Add(new County("Yorkshire", DERBYSHIRE);
            CONVERSIONS.Add(new County("Yorkshire", EAST_RIDING_OF_YORKSHIRE);
            CONVERSIONS.Add(new County("Yorkshire", "KH", "City of Kingston upon Hull"));
            CONVERSIONS.Add(new County("Yorkshire", "KL", "Kirklees"));
            CONVERSIONS.Add(new County("Yorkshire", "LA", "Lancashire"));
            CONVERSIONS.Add(new County("Yorkshire", "LD", "Leeds"));
            CONVERSIONS.Add(new County("Yorkshire", MANCHESTER);
            CONVERSIONS.Add(new County("Yorkshire", "MB", "Middlesbrough"));
            CONVERSIONS.Add(new County("Yorkshire", "NI", "North Lincolnshire"));
            CONVERSIONS.Add(new County("Yorkshire", "NT", "Nottinghamshire"));
            CONVERSIONS.Add(new County("Yorkshire", "NY", "North Yorkshire"));
            CONVERSIONS.Add(new County("Yorkshire", OLDHAM);
            CONVERSIONS.Add(new County("Yorkshire", "RC", "Redcar and Cleveland"));
            CONVERSIONS.Add(new County("Yorkshire", "RD", "Rochdale"));
            CONVERSIONS.Add(new County("Yorkshire", "RO", "Rotherham"));
            CONVERSIONS.Add(new County("Yorkshire", "SM", "Stockton on Tees"));
            CONVERSIONS.Add(new County("Yorkshire", "SP", "Sheffield"));
            CONVERSIONS.Add(new County("Yorkshire", TAMESIDE);
            CONVERSIONS.Add(new County("Yorkshire", "WE", "Wakefield"));
            CONVERSIONS.Add(new County("Yorkshire", "YK", "York"));
        }

        private static void AddConversion(Region region, County county)
        {
            List<County> counties;
 	        if(CONVERSIONS.ContainsKey(region))
                counties = CONVERSIONS[region];
            else
            {
                counties = new List<County>();
                CONVERSIONS.Add(region, counties);
            }
            counties.Add(county);
        }
    }
}
