using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FTAnalyzer.Mapping
{
    public class CountyConversion
    {
        public static readonly Dictionary<Region, List<County>> CONVERSIONS = new Dictionary<Region, List<County>>();
        public static readonly List<County> MODERN_COUNTIES;

        public class County
        {
            public string CountyCode { get; private set; }
            public string CountyName { get; private set; }

            public County(string code, string countyName)
            {
                CountyCode = code;
                CountyName = countyName;
            }

            public override string ToString()
            {
                return CountyCode + ": " + CountyName;
            }
        }

        public static List<County> GetCounties(Region lookup)
        {
            if (CONVERSIONS.ContainsKey(lookup))
                return CONVERSIONS[lookup];
            return new List<County>();
        }

        public static County GetCounty(string code)
        {
            return MODERN_COUNTIES.First(c => c.CountyCode.Equals(code));
        }

        #region Modern County List
        public static County ABERDEENSHIRE = new County("AB", "Aberdeenshire");
        public static County ANGUS = new County("AG", "Angus");
        public static County ABERDEEN_CITY = new County("AN", "Aberdeen City");
        public static County ARGYLL_AND_BUTE = new County("AR", "Argyll and Bute");
        public static County BRADFORD = new County("BA", "Bradford");
        public static County BLACKBURN_WITH_DARWEN = new County("BB", "Blackburn with Darwen");
        public static County BRACKNELL_FOREST = new County("BC", "Bracknell Forest");
        public static County BARKING_AND_DAGENHAM = new County("BD", "Barking and Dagenham");
        public static County BRIDGEND = new County("BE", "Bridgend");
        public static County BEDFORDSHIRE = new County("BF", "Bedfordshire");
        public static County BLAENAU_GWENT = new County("BG", "Blaenau Gwent");
        public static County CITY_OF_BRIGHTON_AND_HOVE = new County("BH", "City of Brighton and Hove");
        public static County BIRMINGHAM = new County("BI", "Birmingham");
        public static County CENTRAL_BEDFORDSHIRE = new County("BK", "Central Bedfordshire"); // extra to gazetteer index
        public static County BARNSLEY = new County("BL", "Barnsley");
        public static County BUCKINGHAMSHIRE = new County("BM", "Buckinghamshire");
        public static County BARNET = new County("BN", "Barnet");
        public static County BOLTON = new County("BO", "Bolton");
        public static County BLACKPOOL = new County("BP", "Blackpool");
        public static County BROMLEY = new County("BR", "Bromley");
        public static County BATH_AND_NORTH_EAST_SOMERSET = new County("BS", "Bath and North East Somerset");
        public static County BRENT = new County("BT", "Brent");
        public static County BOURNEMOUTH = new County("BU", "Bournemouth");
        public static County BEXLEY = new County("BX", "Bexley");
        public static County BURY = new County("BY", "Bury");
        public static County BRISTOL = new County("BZ", "City of Bristol");
        public static County CALDERDALE = new County("CA", "Calderdale");
        public static County CAMBRIDGESHIRE = new County("CB", "Cambridgeshire");
        public static County CARDIFF = new County("CD", "Cardiff");
        public static County CEREDIGION = new County("CE", "Ceredigion");
        public static County CAERPHILLY = new County("CF", "Caerphilly");
        public static County CHESHIRE_EAST = new County("CH", "Cheshire East");
        public static County CHESHIRE_WEST_AND_CHESTER = new County("CC", "Cheshire West and Chester");
        public static County CLACKMANNANSHIRE = new County("CL", "Clackmannanshire");
        public static County CAMDEN = new County("CM", "Camden");
        public static County CORNWALL = new County("CN", "Cornwall");
        public static County CARMARTHENSHIRE = new County("CT", "Carmarthenshire");
        public static County CUMBRIA = new County("CU", "Cumbria");
        public static County COVENTRY = new County("CV", "Coventry");
        public static County CONWY = new County("CW", "Conwy");
        public static County CROYDON = new County("CY", "Croydon");
        public static County CITY_OF_DERBY = new County("DB", "City of Derby");
        public static County DUNDEE_CITY = new County("DD", "Dundee City");
        public static County DENBIGHSHIRE = new County("DE", "Denbighshire");
        public static County DUMFRIES_AND_GALLOWAY = new County("DG", "Dumfries and Galloway");
        public static County DARLINGTON = new County("DL", "Darlington");
        public static County DEVON = new County("DN", "Devon");
        public static County DONCASTER = new County("DR", "Doncaster");
        public static County DORSET = new County("DT", "Dorset");
        public static County DURHAM = new County("DU", "Durham");
        public static County DERBYSHIRE = new County("DY", "Derbyshire");
        public static County DUDLEY = new County("DZ", "Dudley");
        public static County EAST_AYRSHIRE = new County("EA", "East Ayrshire");
        public static County CITY_OF_EDINBURGH = new County("EB", "City of Edinburgh");
        public static County EAST_DUNBARTONSHIRE = new County("ED", "East Dunbartonshire");
        public static County EALING = new County("EG", "Ealing");
        public static County EAST_LOTHIAN = new County("EL", "East Lothian");
        public static County ENFIELD = new County("EN", "Enfield");
        public static County EAST_RENFREWSHIRE = new County("ER", "East Renfrewshire");
        public static County EAST_SUSSEX = new County("ES", "East Sussex");
        public static County ESSEX = new County("EX", "Essex");
        public static County EAST_RIDING_OF_YORKSHIRE = new County("EY", "East Riding of Yorkshire");
        public static County FALKIRK = new County("FA", "Falkirk");
        public static County FIFE = new County("FF", "Fife");
        public static County FLINTSHIRE = new County("FL", "Flintshire");
        public static County GATESHEAD = new County("GH", "Gateshead");
        public static County GLASGOW_CITY = new County("GL", "Glasgow City");
        public static County GLOUCESTERSHIRE = new County("GR", "Gloucestershire");
        public static County GREENWICH = new County("GW", "Greenwich");
        public static County GWYNEDD = new County("GY", "Gwynedd");
        public static County HALTON = new County("HA", "Halton");
        public static County HERTFORDSHIRE = new County("HD", "Hertfordshire");
        public static County HEREFORDSHIRE = new County("HE", "Herefordshire");
        public static County HAMMERSMITH_AND_FULHAM = new County("HF", "Hammersmith and Fulham");
        public static County HARINGEY = new County("HG", "Haringey");
        public static County HILLINGDON = new County("HI", "Hillingdon");
        public static County HIGHLAND = new County("HL", "Highland");
        public static County HACKNEY = new County("HN", "Hackney");
        public static County HAMPSHIRE = new County("HP", "Hampshire");
        public static County HARROW = new County("HR", "Harrow");
        public static County HOUNSLOW = new County("HS", "Hounslow");
        public static County HARTLEPOOL = new County("HT", "Hartlepool");
        public static County HAVERING = new County("HV", "Havering");
        public static County ISLE_OF_ANGLESEY = new County("IA", "Isle of Anglesey");
        public static County ISLINGTON = new County("IL", "Islington");
        public static County ISLE_OF_MAN = new County("IM", "Isle of Man");
        public static County INVERCLYDE = new County("IN", "Inverclyde");
        public static County ISLES_OF_SCILLY = new County("IS", "Isles of Scilly");
        public static County CITY_OF_INVERNESS = new County("IV", "City of Inverness");
        public static County ISLE_OF_WIGHT = new County("IW", "Isle of Wight");
        public static County ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA = new County("KC", "Royal Borough of Kensington and Chelsea");
        public static County KINGSTON_UPON_THAMES = new County("KG", "Kingston upon Thames");
        public static County CITY_OF_KINGSTON_UPON_HULL = new County("KH", "City of Kingston upon Hull");
        public static County KIRKLEES = new County("KL", "Kirklees");
        public static County KNOWSLEY = new County("KN", "Knowsley");
        public static County KENT = new County("KT", "Kent");
        public static County LANCASHIRE = new County("LA", "Lancashire");
        public static County LAMBETH = new County("LB", "Lambeth");
        public static County CITY_OF_LEICESTER = new County("LC", "City of Leicester");
        public static County LEEDS = new County("LD", "Leeds");
        public static County LINCOLNSHIRE = new County("LL", "Lincolnshire");
        public static County LUTON = new County("LN", "Luton");
        public static County CITY_OF_LONDON = new County("LO", "City of London");
        public static County LIVERPOOL = new County("LP", "Liverpool");
        public static County LEWISHAM = new County("LS", "Lewisham");
        public static County LEICESTERSHIRE = new County("LT", "Leicestershire");
        public static County MANCHESTER = new County("MA", "Manchester");
        public static County MIDDLESBROUGH = new County("MB", "Middlesbrough");
        public static County MEDWAY = new County("ME", "Medway");
        public static County MIDLOTHIAN = new County("MI", "Midlothian");
        public static County MILTON_KEYNES = new County("MK", "Milton Keynes");
        public static County MONMOUTHSHIRE = new County("MM", "Monmouthshire");
        public static County MORAY = new County("MO", "Moray");
        public static County MERTON = new County("MR", "Merton");
        public static County MERTHYR_TYDFIL = new County("MT", "Merthyr Tydfil");
        public static County NORTH_AYRSHIRE = new County("NA", "North Ayrshire");
        public static County NORTH_EAST_LINCOLNSHIRE = new County("NC", "North East Lincolnshire");
        public static County NORTHUMBERLAND = new County("ND", "Northumberland");
        public static County NEWPORT = new County("NE", "Newport");
        public static County CITY_OF_NOTTINGHAM = new County("NG", "City of Nottingham");
        public static County NEWHAM = new County("NH", "Newham");
        public static County NORTH_LINCOLNSHIRE = new County("NI", "North Lincolnshire");
        public static County NORFOLK = new County("NK", "Norfolk");
        public static County NORTH_LANARKSHIRE = new County("NL", "North Lanarkshire");
        public static County NORTHAMPTONSHIRE = new County("NN", "Northamptonshire");
        public static County NEATH_PORT_TALBOT = new County("NP", "Neath Port Talbot");
        public static County NORTH_TYNESIDE = new County("NR", "North Tyneside");
        public static County NORTH_SOMERSET = new County("NS", "North Somerset");
        public static County NOTTINGHAMSHIRE = new County("NT", "Nottinghamshire");
        public static County NEWCASTLE_UPON_TYNE = new County("NW", "Newcastle upon Tyne");
        public static County NORTH_YORKSHIRE = new County("NY", "North Yorkshire");
        public static County OLDHAM = new County("OH", "Oldham");
        public static County ORKNEY_ISLANDS = new County("OK", "Orkney Islands");
        public static County OXFORDSHIRE = new County("ON", "Oxfordshire");
        public static County PEMBROKESHIRE = new County("PB", "Pembrokeshire");
        public static County CITY_OF_PETERBOROUGH = new County("PE", "City of Peterborough");
        public static County PERTH_AND_KINROSS = new County("PK", "Perth and Kinross");
        public static County POOLE = new County("PL", "Poole");
        public static County CITY_OF_PORTSMOUTH = new County("PO", "City of Portsmouth");
        public static County POWYS = new County("PW", "Powys");
        public static County CITY_OF_PLYMOUTH = new County("PY", "City of Plymouth");
        public static County REDBRIDGE = new County("RB", "Redbridge");
        public static County REDCAR_AND_CLEVELAND = new County("RC", "Redcar and Cleveland");
        public static County ROCHDALE = new County("RD", "Rochdale");
        public static County RENFREWSHIRE = new County("RE", "Renfrewshire");
        public static County READING = new County("RG", "Reading");
        public static County RHONDDA_CYNON_TAFF = new County("RH", "Rhondda Cynon Taff");
        public static County RUTLAND = new County("RL", "Rutland");
        public static County ROTHERHAM = new County("RO", "Rotherham");
        public static County RICHMOND_UPON_THAMES = new County("RT", "Richmond upon Thames");
        public static County SANDWELL = new County("SA", "Sandwell");
        public static County SCOTTISH_BORDERS = new County("SB", "Scottish Borders");
        public static County SALFORD = new County("SC", "Salford");
        public static County SWINDON = new County("SD", "Swindon");
        public static County SEFTON = new County("SE", "Sefton");
        public static County STAFFORDSHIRE = new County("SF", "Staffordshire");
        public static County SOUTH_GLOUCESTERSHIRE = new County("SG", "South Gloucestershire");
        public static County SHROPSHIRE = new County("SH", "Shropshire");
        public static County SHETLAND_ISLANDS = new County("SI", "Shetland Islands");
        public static County CITY_OF_STOKE_ON_TRENT = new County("SJ", "City of Stoke-on-Trent");
        public static County SUFFOLK = new County("SK", "Suffolk");
        public static County SOUTH_LANARKSHIRE = new County("SL", "South Lanarkshire");
        public static County STOCKTON_ON_TEES = new County("SM", "Stockton-on-Tees");
        public static County ST_HELENS = new County("SN", "St Helens");
        public static County CITY_OF_SOUTHAMPTON = new County("SO", "City of Southampton");
        public static County SHEFFIELD = new County("SP", "Sheffield");
        public static County SOLIHULL = new County("SQ", "Solihull");
        public static County STIRLING = new County("SR", "Stirling");
        public static County SWANSEA = new County("SS", "Swansea");
        public static County SOMERSET = new County("ST", "Somerset");
        public static County SURREY = new County("SU", "Surrey");
        public static County SUNDERLAND = new County("SV", "Sunderland");
        public static County SOUTHWARK = new County("SW", "Southwark");
        public static County SOUTH_AYRSHIRE = new County("SX", "South Ayrshire");
        public static County SOUTH_TYNESIDE = new County("SY", "South Tyneside");
        public static County SUTTON = new County("SZ", "Sutton");
        public static County TORBAY = new County("TB", "Torbay");
        public static County TORFAEN = new County("TF", "Torfaen");
        public static County TOWER_HAMLETS = new County("TH", "Tower Hamlets");
        public static County TRAFFORD = new County("TR", "Trafford");
        public static County TAMESIDE = new County("TS", "Tameside");
        public static County THURROCK = new County("TU", "Thurrock");
        public static County VALE_OF_GLAMORGAN = new County("VG", "Vale of Glamorgan");
        public static County WALSALL = new County("WA", "Walsall");
        public static County WEST_BERKSHIRE = new County("WB", "West Berkshire");
        public static County WINDSOR_AND_MAIDENHEAD = new County("WC", "Windsor and Maidenhead");
        public static County WEST_DUNBARTONSHIRE = new County("WD", "West Dunbartonshire");
        public static County WAKEFIELD = new County("WE", "Wakefield");
        public static County WALTHAM_FOREST = new County("WF", "Waltham Forest");
        public static County WARRINGTON = new County("WG", "Warrington");
        public static County CITY_OF_WOLVERHAMPTON = new County("WH", "City of Wolverhampton");
        public static County WESTERN_ISLES = new County("WI", "Na h-Eileanan an Iar");
        public static County WOKINGHAM = new County("WJ", "Wokingham");
        public static County WARWICKSHIRE = new County("WK", "Warwickshire");
        public static County WEST_LOTHIAN = new County("WL", "West Lothian");
        public static County CITY_OF_WESTMINSTER = new County("WM", "City of Westminster");
        public static County WIGAN = new County("WN", "Wigan");
        public static County WORCESTERSHIRE = new County("WO", "Worcestershire");
        public static County TELFORD_AND_WREKIN = new County("WP", "Telford and Wrekin");
        public static County WIRRAL = new County("WR", "Wirral");
        public static County WEST_SUSSEX = new County("WS", "West Sussex");
        public static County WILTSHIRE = new County("WT", "Wiltshire");
        public static County WANDSWORTH = new County("WW", "Wandsworth");
        public static County WREXHAM = new County("WX", "Wrexham");
        public static County YORK = new County("YK", "York");
        public static County SOUTHEND_ON_SEA = new County("YS", "Southend-on-Sea");
        public static County SLOUGH = new County("YT", "Slough");
        public static County STOCKPORT = new County("YY", "Stockport");
        #endregion

        static CountyConversion()
        {
            MODERN_COUNTIES = new List<County>(new County[] { 
                ABERDEEN_CITY, ANGUS, ABERDEENSHIRE, ARGYLL_AND_BUTE, BRADFORD, BLACKBURN_WITH_DARWEN,
                BRACKNELL_FOREST, BARKING_AND_DAGENHAM, BRIDGEND, BEDFORDSHIRE, BLAENAU_GWENT, 
                CITY_OF_BRIGHTON_AND_HOVE, BIRMINGHAM, CENTRAL_BEDFORDSHIRE, BARNSLEY, BUCKINGHAMSHIRE,
                BARNET, BOLTON, BLACKPOOL, BROMLEY, BATH_AND_NORTH_EAST_SOMERSET, BRENT, BOURNEMOUTH,
                BEXLEY, BURY, BRISTOL, CALDERDALE, CAMBRIDGESHIRE, CARDIFF, CEREDIGION, CAERPHILLY, 
                CHESHIRE_EAST, CHESHIRE_WEST_AND_CHESTER, CLACKMANNANSHIRE, CAMDEN, CORNWALL, 
                CARMARTHENSHIRE, CUMBRIA, COVENTRY, CONWY, CROYDON, CITY_OF_DERBY, DUNDEE_CITY, DENBIGHSHIRE,
                DUMFRIES_AND_GALLOWAY, DARLINGTON, DEVON, DONCASTER, DORSET, DURHAM, DERBYSHIRE, EAST_AYRSHIRE,
                CITY_OF_EDINBURGH, EAST_DUNBARTONSHIRE, EALING, EAST_LOTHIAN, ENFIELD, EAST_RENFREWSHIRE, 
                EAST_SUSSEX, ESSEX, EAST_RIDING_OF_YORKSHIRE, FALKIRK, FIFE, FLINTSHIRE, GATESHEAD, 
                GLASGOW_CITY, GLOUCESTERSHIRE, GREENWICH, GWYNEDD, HALTON, HERTFORDSHIRE, HEREFORDSHIRE,
                HAMMERSMITH_AND_FULHAM, HARINGEY, HILLINGDON, HIGHLAND, HACKNEY, HAMPSHIRE, HARROW,
                HOUNSLOW, HARTLEPOOL, HAVERING, ISLE_OF_ANGLESEY, ISLINGTON, ISLE_OF_MAN, INVERCLYDE,
                ISLES_OF_SCILLY, CITY_OF_INVERNESS, ISLE_OF_WIGHT, ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA,
                KINGSTON_UPON_THAMES, CITY_OF_KINGSTON_UPON_HULL, KIRKLEES, KNOWSLEY, KENT, LANCASHIRE,
                LAMBETH, CITY_OF_LEICESTER, LEEDS, LINCOLNSHIRE, LUTON, CITY_OF_LONDON, LIVERPOOL, 
                LEWISHAM, LEICESTERSHIRE, MANCHESTER, MIDDLESBROUGH, MEDWAY, MIDLOTHIAN, MILTON_KEYNES
        });
            bool ignore = Regions.IsKnownRegion("Aberdeenshire"); // forced Regions static class to load.
            AddConversion(Regions.CAITHNESS, HIGHLAND);
            AddConversion(Regions.SUTHERLAND, HIGHLAND);
            AddConversion(Regions.ROSS_CROMARTY, HIGHLAND);
            AddConversion(Regions.ROSS_CROMARTY, WESTERN_ISLES);
            AddConversion(Regions.INVERNESS, HIGHLAND);
            AddConversion(Regions.INVERNESS, ABERDEENSHIRE);
            AddConversion(Regions.INVERNESS, MORAY);
            AddConversion(Regions.INVERNESS, ARGYLL_AND_BUTE);
            AddConversion(Regions.INVERNESS, WESTERN_ISLES);
            AddConversion(Regions.NAIRN, HIGHLAND);
            AddConversion(Regions.NAIRN, MORAY);
            AddConversion(Regions.MORAY, MORAY);
            AddConversion(Regions.MORAY, ABERDEENSHIRE);
            AddConversion(Regions.MORAY, HIGHLAND);
            AddConversion(Regions.BANFF, MORAY);
            AddConversion(Regions.BANFF, ABERDEENSHIRE);
            AddConversion(Regions.ABERDEEN, ABERDEEN_CITY);
            AddConversion(Regions.ABERDEEN, ABERDEENSHIRE);
            AddConversion(Regions.ABERDEEN, MORAY);
            AddConversion(Regions.KINCARDINE, ABERDEENSHIRE);
            AddConversion(Regions.KINCARDINE, ABERDEEN_CITY);
            AddConversion(Regions.KINCARDINE, ANGUS);
            AddConversion(Regions.ANGUS, ANGUS);
            AddConversion(Regions.ANGUS, ABERDEENSHIRE);
            AddConversion(Regions.ANGUS, PERTH_AND_KINROSS);
            AddConversion(Regions.ANGUS, DUNDEE_CITY);
            AddConversion(Regions.PERTH, PERTH_AND_KINROSS);
            AddConversion(Regions.PERTH, STIRLING);
            AddConversion(Regions.PERTH, CLACKMANNANSHIRE);
            AddConversion(Regions.PERTH, FIFE);
            AddConversion(Regions.PERTH, ANGUS);
            AddConversion(Regions.PERTH, DUNDEE_CITY);
            AddConversion(Regions.ARGYLL, ARGYLL_AND_BUTE);
            AddConversion(Regions.ARGYLL, HIGHLAND);
            AddConversion(Regions.ARGYLL, PERTH_AND_KINROSS);
            AddConversion(Regions.ARGYLL, STIRLING);
            AddConversion(Regions.BUTE, ARGYLL_AND_BUTE);
            AddConversion(Regions.BUTE, NORTH_AYRSHIRE);
            AddConversion(Regions.AYR, EAST_AYRSHIRE);
            AddConversion(Regions.AYR, NORTH_AYRSHIRE);
            AddConversion(Regions.AYR, SOUTH_AYRSHIRE);
            AddConversion(Regions.RENFREW, GLASGOW_CITY);
            AddConversion(Regions.RENFREW, INVERCLYDE);
            AddConversion(Regions.RENFREW, RENFREWSHIRE);
            AddConversion(Regions.RENFREW, EAST_RENFREWSHIRE);
            AddConversion(Regions.DUNBARTON, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, WEST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, GLASGOW_CITY);
            AddConversion(Regions.DUNBARTON, NORTH_LANARKSHIRE);
            AddConversion(Regions.DUNBARTON, STIRLING);
            AddConversion(Regions.STIRLING, STIRLING);
            AddConversion(Regions.STIRLING, PERTH_AND_KINROSS);
            AddConversion(Regions.STIRLING, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.STIRLING, NORTH_LANARKSHIRE);
            AddConversion(Regions.STIRLING, FALKIRK);
            AddConversion(Regions.STIRLING, CLACKMANNANSHIRE);
            AddConversion(Regions.CLACKMANNAN, CLACKMANNANSHIRE);
            AddConversion(Regions.CLACKMANNAN, STIRLING);
            AddConversion(Regions.CLACKMANNAN, PERTH_AND_KINROSS);
            AddConversion(Regions.KINROSS, PERTH_AND_KINROSS);
            AddConversion(Regions.KINROSS, FIFE);
            AddConversion(Regions.KINROSS, CLACKMANNANSHIRE);
            AddConversion(Regions.FIFE, FIFE);
            AddConversion(Regions.FIFE, PERTH_AND_KINROSS);
            AddConversion(Regions.WEST_LOTHIAN, WEST_LOTHIAN);
            AddConversion(Regions.WEST_LOTHIAN, NORTH_LANARKSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, SOUTH_LANARKSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, CITY_OF_EDINBURGH);
            AddConversion(Regions.WEST_LOTHIAN, FALKIRK);
            AddConversion(Regions.WEST_LOTHIAN, SCOTTISH_BORDERS);
            AddConversion(Regions.MIDLOTHIAN, CITY_OF_EDINBURGH);
            AddConversion(Regions.MIDLOTHIAN, MIDLOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, WEST_LOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.MIDLOTHIAN, SCOTTISH_BORDERS);
            AddConversion(Regions.EAST_LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.EAST_LOTHIAN, MIDLOTHIAN);
            AddConversion(Regions.EAST_LOTHIAN, CITY_OF_EDINBURGH);
            AddConversion(Regions.EAST_LOTHIAN, SCOTTISH_BORDERS);
            AddConversion(Regions.EAST_LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.BERWICK, SCOTTISH_BORDERS);
            AddConversion(Regions.BERWICK, EAST_LOTHIAN);
            AddConversion(Regions.BERWICK, MIDLOTHIAN);
            AddConversion(Regions.ROXBURGH, SCOTTISH_BORDERS);
            AddConversion(Regions.DUMFRIES, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.DUMFRIES, SCOTTISH_BORDERS);
            AddConversion(Regions.DUMFRIES, SOUTH_LANARKSHIRE);
            AddConversion(Regions.KIRKCUDBRIGHT, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.WIGTOWN, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.LANARK, GLASGOW_CITY);
            AddConversion(Regions.LANARK, NORTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, SOUTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.LANARK, SCOTTISH_BORDERS);
            AddConversion(Regions.LANARK, WEST_LOTHIAN);
            AddConversion(Regions.LANARK, EAST_RENFREWSHIRE);
            AddConversion(Regions.SELKIRK, SCOTTISH_BORDERS);
            AddConversion(Regions.PEEBLES, SCOTTISH_BORDERS);
            AddConversion(Regions.PEEBLES, SOUTH_LANARKSHIRE);
            AddConversion(Regions.PEEBLES, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.PEEBLES, MIDLOTHIAN);
            AddConversion(Regions.PEEBLES, WEST_LOTHIAN);
            AddConversion(Regions.ABERDEEN_CITY, ABERDEEN_CITY);
            AddConversion(Regions.ABERDEEN_CITY, ABERDEENSHIRE);
            AddConversion(Regions.ORKNEY, ORKNEY_ISLANDS);
            AddConversion(Regions.SHETLAND, SHETLAND_ISLANDS);
            AddConversion(Regions.BORDERS, SCOTTISH_BORDERS);

            #region Modern Counties - as per Gazetteer

            AddConversion(Regions.BARKING, BARKING_AND_DAGENHAM);
            AddConversion(Regions.BARNET, BARNET);
            AddConversion(Regions.BARNSLEY, BARNSLEY);
            AddConversion(Regions.BATH, BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.BEDS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BERKS, WEST_BERKSHIRE);
            AddConversion(Regions.BEXLEY, BEXLEY);
            AddConversion(Regions.BIRMINGHAM, BIRMINGHAM);
            AddConversion(Regions.BLACKBURN, BLACKBURN_WITH_DARWEN);
            AddConversion(Regions.BLACKPOOL, BLACKPOOL);
            AddConversion(Regions.BLAENAU_GWENT, BLAENAU_GWENT);
            AddConversion(Regions.BOLTON, BOLTON);
            AddConversion(Regions.BOURNEMOUTH, BOURNEMOUTH);
            AddConversion(Regions.BRACKNELL, BRACKNELL_FOREST);
            AddConversion(Regions.BRADFORD, BRADFORD);
            AddConversion(Regions.BRENT, BRENT);
            AddConversion(Regions.BRIDGEND, BRIDGEND);
            AddConversion(Regions.BRIGHTON, CITY_OF_BRIGHTON_AND_HOVE);
            AddConversion(Regions.BRISTOL, BRISTOL);
            AddConversion(Regions.BROMLEY, BROMLEY);
            AddConversion(Regions.BUCKS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BURY, BURY);
            AddConversion(Regions.BUTE, ARGYLL_AND_BUTE);
            AddConversion(Regions.CAERPHILLY, CAERPHILLY);
            AddConversion(Regions.CALDERDALE, CALDERDALE);
            AddConversion(Regions.CAMBS, CAMBRIDGESHIRE);
            AddConversion(Regions.CAMDEN, CAMDEN);
            AddConversion(Regions.CARDIFF, CARDIFF);
            AddConversion(Regions.CARMARTHEN, CARMARTHENSHIRE);
            AddConversion(Regions.CENTRAL_BEDFORDSHIRE, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.CEREDIGION, CEREDIGION);
            AddConversion(Regions.CHESHIRE, CHESHIRE_EAST);
            AddConversion(Regions.CHESHIRE, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.CLACKMANNAN, CLACKMANNANSHIRE);
            AddConversion(Regions.CONWY, CONWY);
            AddConversion(Regions.CORNWALL, CORNWALL);
            AddConversion(Regions.COVENTRY, COVENTRY);
            AddConversion(Regions.CROYDON, CROYDON);
            AddConversion(Regions.CUMBRIA, CUMBRIA);
            AddConversion(Regions.DARLINGTON, DARLINGTON);
            AddConversion(Regions.DENBIGH, DENBIGHSHIRE);
            AddConversion(Regions.DERBY, CITY_OF_DERBY);
            AddConversion(Regions.DERBY, DERBYSHIRE);
            AddConversion(Regions.DEVON, DEVON);
            AddConversion(Regions.DONCASTER, DONCASTER);
            AddConversion(Regions.DORSET, DORSET);
            AddConversion(Regions.DUDLEY, DUDLEY);
            AddConversion(Regions.DUMFRIES_GALLOWAY, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.DUNBARTON, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNBARTON, WEST_DUNBARTONSHIRE);
            AddConversion(Regions.DUNDEE_CITY, DUNDEE_CITY);
            AddConversion(Regions.DURHAM, DURHAM);
            AddConversion(Regions.EALING, EALING);
            AddConversion(Regions.EAST_AYRSHIRE, EAST_AYRSHIRE);
            AddConversion(Regions.EAST_DUNBARTONSHIRE, EAST_DUNBARTONSHIRE);
            AddConversion(Regions.EAST_LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.EAST_RENFREW, EAST_RENFREWSHIRE);
            AddConversion(Regions.EAST_YORKSHIRE, EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.EAST_SUSSEX, EAST_SUSSEX);
            AddConversion(Regions.EDINBURGH_CITY, CITY_OF_EDINBURGH);
            AddConversion(Regions.ENFIELD, ENFIELD);
            AddConversion(Regions.ESSEX, ESSEX);
            AddConversion(Regions.FALKIRK, FALKIRK);
            AddConversion(Regions.FIFE, FIFE);
            AddConversion(Regions.FLINT, FLINTSHIRE);
            AddConversion(Regions.GATESHEAD, GATESHEAD);
            AddConversion(Regions.GLASGOW_CITY, GLASGOW_CITY);
            AddConversion(Regions.GLOUCS, GLOUCESTERSHIRE);
            AddConversion(Regions.GLOUCS, SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.GREENWICH, GREENWICH);
            AddConversion(Regions.GWYNEDD, GWYNEDD);
            AddConversion(Regions.HACKNEY, HACKNEY);
            AddConversion(Regions.HALTON, HALTON);
            AddConversion(Regions.HAMMERSMITH, HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.HANTS, HAMPSHIRE);
            AddConversion(Regions.HARINGEY, HARINGEY);
            AddConversion(Regions.HARROW, HARROW);
            AddConversion(Regions.HARTLEPOOL, HARTLEPOOL);
            AddConversion(Regions.HAVERING, HAVERING);
            AddConversion(Regions.HEREFORD, HEREFORDSHIRE);
            AddConversion(Regions.HERTS, HERTFORDSHIRE);
            AddConversion(Regions.HIGHLAND, HIGHLAND);
            AddConversion(Regions.HILLINGDON, HILLINGDON);
            AddConversion(Regions.HOUNSLOW, HOUNSLOW);
            AddConversion(Regions.INVERCLYDE, INVERCLYDE);
            AddConversion(Regions.ANGLESEY, ISLE_OF_ANGLESEY);
            AddConversion(Regions.IOM, ISLE_OF_MAN);
            AddConversion(Regions.IOW, ISLE_OF_WIGHT);
            AddConversion(Regions.ISLES_OF_SCILLY, ISLES_OF_SCILLY);
            AddConversion(Regions.ISLINGTON, ISLINGTON);
            AddConversion(Regions.KENT, KENT);
            AddConversion(Regions.KINGSTON_HULL, CITY_OF_KINGSTON_UPON_HULL);
            AddConversion(Regions.KINGSTON_THAMES, KINGSTON_UPON_THAMES);
            AddConversion(Regions.KIRKLEES, KIRKLEES);
            AddConversion(Regions.KNOWSLEY, KNOWSLEY);
            AddConversion(Regions.LAMBETH, LAMBETH);
            AddConversion(Regions.LANARK, NORTH_LANARKSHIRE);
            AddConversion(Regions.LANARK, SOUTH_LANARKSHIRE);
            AddConversion(Regions.LANCS, LANCASHIRE);
            AddConversion(Regions.LEEDS, LEEDS);
            AddConversion(Regions.LEICESTER_CITY, CITY_OF_LEICESTER);
            AddConversion(Regions.LEICS, LEICESTERSHIRE);
            AddConversion(Regions.LEWISHAM, LEWISHAM);
            AddConversion(Regions.LINCS, LINCOLNSHIRE);
            AddConversion(Regions.LINCS, NORTH_EAST_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.LIVERPOOL, LIVERPOOL);
            AddConversion(Regions.LONDON, CITY_OF_LONDON);
            AddConversion(Regions.LOTHIAN, EAST_LOTHIAN);
            AddConversion(Regions.LOTHIAN, WEST_LOTHIAN);
            AddConversion(Regions.LUTON, LUTON);
            AddConversion(Regions.MANCHESTER, MANCHESTER);
            AddConversion(Regions.MEDWAY, MEDWAY);
            AddConversion(Regions.MERTHYL, MERTHYR_TYDFIL);
            AddConversion(Regions.MERTON, MERTON);
            AddConversion(Regions.MIDDLESBROUGH, MIDDLESBROUGH);
            AddConversion(Regions.MIDLOTHIAN, MIDLOTHIAN);
            AddConversion(Regions.MILTON_KEYNES, MILTON_KEYNES);
            AddConversion(Regions.MONMOUTH, MONMOUTHSHIRE);
            AddConversion(Regions.MORAY, MORAY);
            AddConversion(Regions.WESTERN_ISLES, WESTERN_ISLES);
            AddConversion(Regions.NEATH, NEATH_PORT_TALBOT);
            AddConversion(Regions.NEWCASTLE, NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.NEWHAM, NEWHAM);
            AddConversion(Regions.NEWPORT, NEWPORT);
            AddConversion(Regions.NORFOLK, NORFOLK);
            AddConversion(Regions.NORTH_AYRSHIRE, NORTH_AYRSHIRE);
            AddConversion(Regions.NE_LINCOLNSHIRE, NORTH_EAST_LINCOLNSHIRE);
            AddConversion(Regions.NORTH_LANARK, NORTH_LANARKSHIRE);
            AddConversion(Regions.NORTH_LINCOLNSHIRE, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.NORTH_SOMERSET, NORTH_SOMERSET);
            AddConversion(Regions.NORTH_TYNESIDE, NORTH_TYNESIDE);
            AddConversion(Regions.NORTH_YORKSHIRE, NORTH_YORKSHIRE);
            AddConversion(Regions.NORTHAMPTON, NORTHAMPTONSHIRE);
            AddConversion(Regions.NORTHUMBERLAND, NORTHUMBERLAND);
            AddConversion(Regions.NOTTINGHAM_CITY, CITY_OF_NOTTINGHAM);
            AddConversion(Regions.NOTTS, NOTTINGHAMSHIRE);
            AddConversion(Regions.OLDHAM, OLDHAM);
            AddConversion(Regions.ORKNEY, ORKNEY_ISLANDS);
            AddConversion(Regions.OXFORD, OXFORDSHIRE);
            AddConversion(Regions.PEMBROKE, PEMBROKESHIRE);
            AddConversion(Regions.PERTH_KINROSS, PERTH_AND_KINROSS);
            AddConversion(Regions.PETERBOROUGH, CITY_OF_PETERBOROUGH);
            AddConversion(Regions.PLYMOUTH, CITY_OF_PLYMOUTH);
            AddConversion(Regions.POOLE, POOLE);
            AddConversion(Regions.PORTSMOUTH, CITY_OF_PORTSMOUTH);
            AddConversion(Regions.POWYS, POWYS);
            AddConversion(Regions.READING, READING);
            AddConversion(Regions.REDBRIDGE, REDBRIDGE);
            AddConversion(Regions.REDCAR, REDCAR_AND_CLEVELAND);
            AddConversion(Regions.RENFREW, EAST_RENFREWSHIRE);
            AddConversion(Regions.RENFREW, RENFREWSHIRE);
            AddConversion(Regions.RHONDDA, RHONDDA_CYNON_TAFF);
            AddConversion(Regions.RICHMOND_THAMES, RICHMOND_UPON_THAMES);
            AddConversion(Regions.ROCHDALE, ROCHDALE);
            AddConversion(Regions.ROTHERHAM, ROTHERHAM);
            AddConversion(Regions.KENSINGTON, ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.RUTLAND, RUTLAND);
            AddConversion(Regions.SALFORD, SALFORD);
            AddConversion(Regions.SANDWELL, SANDWELL);
            AddConversion(Regions.BORDERS, SCOTTISH_BORDERS);
            AddConversion(Regions.SEFTON, SEFTON);
            AddConversion(Regions.SHEFFIELD, SHEFFIELD);
            AddConversion(Regions.SHETLAND, SHETLAND_ISLANDS);
            AddConversion(Regions.SHROPS, SHROPSHIRE);
            AddConversion(Regions.SLOUGH, SLOUGH);
            AddConversion(Regions.SOLIHULL, SOLIHULL);
            AddConversion(Regions.SOMERSET, BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.SOMERSET, NORTH_SOMERSET);
            AddConversion(Regions.SOMERSET, SOMERSET);
            AddConversion(Regions.SOUTH_AYRSHIRE, SOUTH_AYRSHIRE);
            AddConversion(Regions.SOUTH_GLOUCESTERSHIRE, SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.SOUTH_LANARK, SOUTH_LANARKSHIRE);
            AddConversion(Regions.SOUTH_TYNESIDE, SOUTH_TYNESIDE);
            AddConversion(Regions.SOUTHAMPTON, CITY_OF_SOUTHAMPTON);
            AddConversion(Regions.SOUTHEND, SOUTHEND_ON_SEA);
            AddConversion(Regions.SOUTHWARK, SOUTHWARK);
            AddConversion(Regions.ST_HELENS, ST_HELENS);
            AddConversion(Regions.STAFFS, STAFFORDSHIRE);
            AddConversion(Regions.STIRLING, STIRLING);
            AddConversion(Regions.STOCKPORT, STOCKPORT);
            AddConversion(Regions.STOCKTON, STOCKTON_ON_TEES);
            AddConversion(Regions.STOKE, CITY_OF_STOKE_ON_TRENT);
            AddConversion(Regions.SUFFOLK, SUFFOLK);
            AddConversion(Regions.SUNDERLAND, SUNDERLAND);
            AddConversion(Regions.SURREY, SURREY);
            AddConversion(Regions.SUSSEX, EAST_SUSSEX);
            AddConversion(Regions.SUSSEX, WEST_SUSSEX);
            AddConversion(Regions.SUTTON, SUTTON);
            AddConversion(Regions.SWANSEA, SWANSEA);
            AddConversion(Regions.SWINDON, SWINDON);
            AddConversion(Regions.TAMESIDE, TAMESIDE);
            AddConversion(Regions.TELFORD, TELFORD_AND_WREKIN);
            AddConversion(Regions.THURROCK, THURROCK);
            AddConversion(Regions.TORBAY, TORBAY);
            AddConversion(Regions.TORFAEN, TORFAEN);
            AddConversion(Regions.TOWER_HAMLETS, TOWER_HAMLETS);
            AddConversion(Regions.TRAFFORD, TRAFFORD);
            AddConversion(Regions.VALE_GLAMORGAN, VALE_OF_GLAMORGAN);
            AddConversion(Regions.WAKEFIELD, WAKEFIELD);
            AddConversion(Regions.WALSALL, WALSALL);
            AddConversion(Regions.WALTHAM_FOREST, WALTHAM_FOREST);
            AddConversion(Regions.WANDSWORTH, WANDSWORTH);
            AddConversion(Regions.WARRINGTON, WARRINGTON);
            AddConversion(Regions.WARWICK, WARWICKSHIRE);
            AddConversion(Regions.WEST_BERKSHIRE, WEST_BERKSHIRE);
            AddConversion(Regions.WEST_DUNBARTON, WEST_DUNBARTONSHIRE);
            AddConversion(Regions.WEST_LOTHIAN, WEST_LOTHIAN);
            AddConversion(Regions.WEST_SUSSEX, WEST_SUSSEX);
            AddConversion(Regions.WESTERN_ISLES, WESTERN_ISLES);
            AddConversion(Regions.WESTMINSTER, CITY_OF_WESTMINSTER);
            AddConversion(Regions.WIGAN, WIGAN);
            AddConversion(Regions.WILTS, WILTSHIRE);
            AddConversion(Regions.WINDSOR, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.WIRRAL, WIRRAL);
            AddConversion(Regions.WOKINGHAM, WOKINGHAM);
            AddConversion(Regions.WOLVERHAMPTON, CITY_OF_WOLVERHAMPTON);
            AddConversion(Regions.WORCESTER, WORCESTERSHIRE);
            AddConversion(Regions.WREXHAM, WREXHAM);
            AddConversion(Regions.YORK, YORK);
            #endregion

            // Alternate names for Modern Counties
            //CONVERSIONS.Add(new County("Barking", BARKING_AND_DAGENHAM);
            //CONVERSIONS.Add(new County("Bath", BATH_AND_NORTH_EAST_SOMERSET);
            //CONVERSIONS.Add(new County("Bedford", BEDFORD);
            //CONVERSIONS.Add(new County("Blackburn", BLACKBURN_WITH_DARWEN);
            //CONVERSIONS.Add(new County("Brighton", CITY_OF_BRIGHTON_AND_HOVE);
            //CONVERSIONS.Add(new County("Bristol", BRISTOL);
            //CONVERSIONS.Add(new County("Chelsea", ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            //CONVERSIONS.Add(new County("Chester", CHESHIRE_WEST_AND_CHESTER);
            //CONVERSIONS.Add(new County("Hammersmith", HAMMERSMITH_AND_FULHAM);
            //CONVERSIONS.Add(new County("Kensington and Chelsea", ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            //CONVERSIONS.Add(new County("Kensington", ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            //CONVERSIONS.Add(new County("Telford", TELFORD_AND_WREKIN);
            //CONVERSIONS.Add(new County("Tyneside", NORTH_TYNESIDE);
            //CONVERSIONS.Add(new County("Tyneside", SOUTH_TYNESIDE);
            //AddConversion(Regions.WARWICK, BIRMINGHAM);
            //CONVERSIONS.Add(new County("Windsor", WINDSOR_AND_MAIDENHEAD);
            //CONVERSIONS.Add(new County("Wrekin", TELFORD_AND_WREKIN);

            // from parish maps
            AddConversion(Regions.ANGLESEY, ISLE_OF_ANGLESEY);
            AddConversion(Regions.BEDS, BEDFORDSHIRE);
            AddConversion(Regions.BEDS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BEDS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BEDS, CAMBRIDGESHIRE);
            AddConversion(Regions.BEDS, HERTFORDSHIRE);
            AddConversion(Regions.BEDS, LUTON);
            AddConversion(Regions.BEDS, MILTON_KEYNES);
            AddConversion(Regions.BERKS, BRACKNELL_FOREST);
            AddConversion(Regions.BERKS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BERKS, GLOUCESTERSHIRE);
            AddConversion(Regions.BERKS, HAMPSHIRE);
            AddConversion(Regions.BERKS, OXFORDSHIRE);
            AddConversion(Regions.BERKS, READING);
            AddConversion(Regions.BERKS, SWINDON);
            AddConversion(Regions.BERKS, SURREY);
            AddConversion(Regions.BERKS, WEST_BERKSHIRE);
            AddConversion(Regions.BERKS, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.BERKS, WOKINGHAM);
            AddConversion(Regions.BERKS, WILTSHIRE);
            AddConversion(Regions.BRECON, BLAENAU_GWENT);
            AddConversion(Regions.BRECON, CEREDIGION);
            AddConversion(Regions.BRECON, CAERPHILLY);
            AddConversion(Regions.BRECON, CARMARTHENSHIRE);
            AddConversion(Regions.BRECON, HEREFORDSHIRE);
            AddConversion(Regions.BRECON, MONMOUTHSHIRE);
            AddConversion(Regions.BRECON, MERTHYR_TYDFIL);
            AddConversion(Regions.BRECON, NEATH_PORT_TALBOT);
            AddConversion(Regions.BRECON, POWYS);
            AddConversion(Regions.BRECON, RHONDDA_CYNON_TAFF);
            AddConversion(Regions.BRECON, TORFAEN);
            AddConversion(Regions.BUCKS, BEDFORDSHIRE);
            AddConversion(Regions.BUCKS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.BUCKS, BUCKINGHAMSHIRE);
            AddConversion(Regions.BUCKS, HERTFORDSHIRE);
            AddConversion(Regions.BUCKS, MILTON_KEYNES);
            AddConversion(Regions.BUCKS, NORTHAMPTONSHIRE);
            AddConversion(Regions.BUCKS, OXFORDSHIRE);
            AddConversion(Regions.BUCKS, SURREY);
            AddConversion(Regions.BUCKS, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.BUCKS, WOKINGHAM);
            AddConversion(Regions.BUCKS, SLOUGH);
            AddConversion(Regions.CAERNARFON, CONWY);
            AddConversion(Regions.CAERNARFON, GWYNEDD);
            AddConversion(Regions.CAERNARFON, ISLE_OF_ANGLESEY);
            AddConversion(Regions.CAMBS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.CAMBS, CAMBRIDGESHIRE);
            AddConversion(Regions.CAMBS, ESSEX);
            AddConversion(Regions.CAMBS, HERTFORDSHIRE);
            AddConversion(Regions.CAMBS, LINCOLNSHIRE);
            AddConversion(Regions.CAMBS, NORFOLK);
            AddConversion(Regions.CAMBS, CITY_OF_PETERBOROUGH);
            AddConversion(Regions.CAMBS, SUFFOLK);
            AddConversion(Regions.CEREDIGION, CEREDIGION);
            AddConversion(Regions.CEREDIGION, CARMARTHENSHIRE);
            AddConversion(Regions.CEREDIGION, GWYNEDD);
            AddConversion(Regions.CEREDIGION, PEMBROKESHIRE);
            AddConversion(Regions.CEREDIGION, POWYS);
            AddConversion(Regions.CARMARTHEN, CEREDIGION);
            AddConversion(Regions.CARMARTHEN, CARMARTHENSHIRE);
            AddConversion(Regions.CARMARTHEN, NEATH_PORT_TALBOT);
            AddConversion(Regions.CARMARTHEN, PEMBROKESHIRE);
            AddConversion(Regions.CARMARTHEN, POWYS);
            AddConversion(Regions.CARMARTHEN, SWANSEA);
            AddConversion(Regions.CHESHIRE, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.CHESHIRE, CHESHIRE_EAST);
            AddConversion(Regions.CHESHIRE, DERBYSHIRE);
            AddConversion(Regions.CHESHIRE, FLINTSHIRE);
            AddConversion(Regions.CHESHIRE, HALTON);
            AddConversion(Regions.CHESHIRE, MANCHESTER);
            AddConversion(Regions.CHESHIRE, OLDHAM);
            AddConversion(Regions.CHESHIRE, STAFFORDSHIRE);
            AddConversion(Regions.CHESHIRE, SHROPSHIRE);
            AddConversion(Regions.CHESHIRE, TRAFFORD);
            AddConversion(Regions.CHESHIRE, TAMESIDE);
            AddConversion(Regions.CHESHIRE, WARRINGTON);
            AddConversion(Regions.CHESHIRE, WIRRAL);
            AddConversion(Regions.CHESHIRE, WREXHAM);
            AddConversion(Regions.CHESHIRE, STOCKPORT);
            AddConversion(Regions.CORNWALL, CORNWALL);
            AddConversion(Regions.CORNWALL, DEVON);
            AddConversion(Regions.DURHAM, CUMBRIA);
            AddConversion(Regions.DURHAM, DARLINGTON);
            AddConversion(Regions.DURHAM, DURHAM);
            AddConversion(Regions.DURHAM, GATESHEAD);
            AddConversion(Regions.DURHAM, HARTLEPOOL);
            AddConversion(Regions.DURHAM, MIDDLESBROUGH);
            AddConversion(Regions.DURHAM, NORTHUMBERLAND);
            AddConversion(Regions.DURHAM, NORTH_TYNESIDE);
            AddConversion(Regions.DURHAM, NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.DURHAM, NORTH_YORKSHIRE);
            AddConversion(Regions.DURHAM, STOCKTON_ON_TEES);
            AddConversion(Regions.DURHAM, SUNDERLAND);
            AddConversion(Regions.DURHAM, SOUTH_TYNESIDE);
            AddConversion(Regions.CUMBERLAND, CUMBRIA);
            AddConversion(Regions.CUMBERLAND, DUMFRIES_AND_GALLOWAY);
            AddConversion(Regions.CUMBERLAND, NORTHUMBERLAND);
            AddConversion(Regions.CUMBERLAND, SCOTTISH_BORDERS);
            AddConversion(Regions.DENBIGH, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.DENBIGH, CONWY);
            AddConversion(Regions.DENBIGH, DENBIGHSHIRE);
            AddConversion(Regions.DENBIGH, FLINTSHIRE);
            AddConversion(Regions.DENBIGH, GWYNEDD);
            AddConversion(Regions.DENBIGH, POWYS);
            AddConversion(Regions.DENBIGH, SHROPSHIRE);
            AddConversion(Regions.DENBIGH, WREXHAM);
            AddConversion(Regions.DERBY, CHESHIRE_EAST);
            AddConversion(Regions.DERBY, CITY_OF_DERBY);
            AddConversion(Regions.DERBY, DERBYSHIRE);
            AddConversion(Regions.DERBY, LEICESTERSHIRE);
            AddConversion(Regions.DERBY, NOTTINGHAMSHIRE);
            AddConversion(Regions.DERBY, STAFFORDSHIRE);
            AddConversion(Regions.DERBY, SHEFFIELD);
            AddConversion(Regions.DERBY, TAMESIDE);
            AddConversion(Regions.DERBY, STOCKPORT);
            AddConversion(Regions.DEVON, CORNWALL);
            AddConversion(Regions.DEVON, DEVON);
            AddConversion(Regions.DEVON, HAMPSHIRE);
            AddConversion(Regions.DEVON, CITY_OF_PLYMOUTH);
            AddConversion(Regions.DEVON, SOMERSET);
            AddConversion(Regions.DEVON, TORBAY);
            AddConversion(Regions.DORSET, BOURNEMOUTH);
            AddConversion(Regions.DORSET, DEVON);
            AddConversion(Regions.DORSET, DORSET);
            AddConversion(Regions.DORSET, POOLE);
            AddConversion(Regions.DORSET, SOMERSET);
            AddConversion(Regions.DORSET, WILTSHIRE);
            AddConversion(Regions.DURHAM, CUMBRIA);
            AddConversion(Regions.DURHAM, DARLINGTON);
            AddConversion(Regions.DURHAM, DURHAM);
            AddConversion(Regions.DURHAM, GATESHEAD);
            AddConversion(Regions.DURHAM, HARTLEPOOL);
            AddConversion(Regions.DURHAM, MIDDLESBROUGH);
            AddConversion(Regions.DURHAM, NORTHUMBERLAND);
            AddConversion(Regions.DURHAM, NORTH_TYNESIDE);
            AddConversion(Regions.DURHAM, NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.DURHAM, NORTH_YORKSHIRE);
            AddConversion(Regions.DURHAM, STOCKTON_ON_TEES);
            AddConversion(Regions.DURHAM, SUNDERLAND);
            AddConversion(Regions.DURHAM, SOUTH_TYNESIDE);
            AddConversion(Regions.ESSEX, BARKING_AND_DAGENHAM);
            AddConversion(Regions.ESSEX, CAMBRIDGESHIRE);
            AddConversion(Regions.ESSEX, ENFIELD);
            AddConversion(Regions.ESSEX, ESSEX);
            AddConversion(Regions.ESSEX, GREENWICH);
            AddConversion(Regions.ESSEX, HERTFORDSHIRE);
            AddConversion(Regions.ESSEX, HAVERING);
            AddConversion(Regions.ESSEX, KENT);
            AddConversion(Regions.ESSEX, MEDWAY);
            AddConversion(Regions.ESSEX, NEWHAM);
            AddConversion(Regions.ESSEX, REDBRIDGE);
            AddConversion(Regions.ESSEX, SUFFOLK);
            AddConversion(Regions.ESSEX, THURROCK);
            AddConversion(Regions.ESSEX, WALTHAM_FOREST);
            AddConversion(Regions.ESSEX, SOUTHEND_ON_SEA);
            AddConversion(Regions.FLINT, CHESHIRE_WEST_AND_CHESTER);
            AddConversion(Regions.FLINT, CONWY);
            AddConversion(Regions.FLINT, DENBIGHSHIRE);
            AddConversion(Regions.FLINT, FLINTSHIRE);
            AddConversion(Regions.FLINT, SHROPSHIRE);
            AddConversion(Regions.FLINT, WREXHAM);
            AddConversion(Regions.GLAMORGAN, BRIDGEND);
            AddConversion(Regions.GLAMORGAN, CARDIFF);
            AddConversion(Regions.GLAMORGAN, CAERPHILLY);
            AddConversion(Regions.GLAMORGAN, CARMARTHENSHIRE);
            AddConversion(Regions.GLAMORGAN, MERTHYR_TYDFIL);
            AddConversion(Regions.GLAMORGAN, NEWPORT);
            AddConversion(Regions.GLAMORGAN, NEATH_PORT_TALBOT);
            AddConversion(Regions.GLAMORGAN, POWYS);
            AddConversion(Regions.GLAMORGAN, RHONDDA_CYNON_TAFF);
            AddConversion(Regions.GLAMORGAN, SWANSEA);
            AddConversion(Regions.GLAMORGAN, VALE_OF_GLAMORGAN);
            AddConversion(Regions.GLOUCS, BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.GLOUCS, BRISTOL);
            AddConversion(Regions.GLOUCS, DORSET);
            AddConversion(Regions.GLOUCS, GLOUCESTERSHIRE);
            AddConversion(Regions.GLOUCS, HEREFORDSHIRE);
            AddConversion(Regions.GLOUCS, MONMOUTHSHIRE);
            AddConversion(Regions.GLOUCS, NORTH_SOMERSET);
            AddConversion(Regions.GLOUCS, OXFORDSHIRE);
            AddConversion(Regions.GLOUCS, SWINDON);
            AddConversion(Regions.GLOUCS, SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.GLOUCS, WARWICKSHIRE);
            AddConversion(Regions.GLOUCS, WORCESTERSHIRE);
            AddConversion(Regions.GLOUCS, WILTSHIRE);
            AddConversion(Regions.HANTS, BOURNEMOUTH);
            AddConversion(Regions.HANTS, DORSET);
            AddConversion(Regions.HANTS, HALTON);
            AddConversion(Regions.HANTS, HAMPSHIRE);
            AddConversion(Regions.HANTS, ISLE_OF_WIGHT);
            AddConversion(Regions.HANTS, POOLE);
            AddConversion(Regions.HANTS, CITY_OF_PORTSMOUTH);
            AddConversion(Regions.HANTS, CITY_OF_SOUTHAMPTON);
            AddConversion(Regions.HANTS, SURREY);
            AddConversion(Regions.HANTS, WEST_BERKSHIRE);
            AddConversion(Regions.HANTS, WOKINGHAM);
            AddConversion(Regions.HANTS, WEST_SUSSEX);
            AddConversion(Regions.HANTS, WILTSHIRE);
            AddConversion(Regions.HEREFORD, GLOUCESTERSHIRE);
            AddConversion(Regions.HEREFORD, HEREFORDSHIRE);
            AddConversion(Regions.HEREFORD, MONMOUTHSHIRE);
            AddConversion(Regions.HEREFORD, POWYS);
            AddConversion(Regions.HEREFORD, SHROPSHIRE);
            AddConversion(Regions.HEREFORD, WORCESTERSHIRE);
            AddConversion(Regions.HERTS, CENTRAL_BEDFORDSHIRE);
            AddConversion(Regions.HERTS, BUCKINGHAMSHIRE);
            AddConversion(Regions.HERTS, BARNET);
            AddConversion(Regions.HERTS, ENFIELD);
            AddConversion(Regions.HERTS, ESSEX);
            AddConversion(Regions.HERTS, HERTFORDSHIRE);
            AddConversion(Regions.HERTS, HILLINGDON);
            AddConversion(Regions.HERTS, HARROW);
            AddConversion(Regions.HUNTS, BEDFORDSHIRE);
            AddConversion(Regions.HUNTS, CAMBRIDGESHIRE);
            AddConversion(Regions.HUNTS, NORTHAMPTONSHIRE);
            AddConversion(Regions.HUNTS, CITY_OF_PETERBOROUGH);
            AddConversion(Regions.KENT, BROMLEY);
            AddConversion(Regions.KENT, BEXLEY);
            AddConversion(Regions.KENT, CROYDON);
            AddConversion(Regions.KENT, EAST_SUSSEX);
            AddConversion(Regions.KENT, GREENWICH);
            AddConversion(Regions.KENT, HAVERING);
            AddConversion(Regions.KENT, KENT);
            AddConversion(Regions.KENT, LEWISHAM);
            AddConversion(Regions.KENT, MEDWAY);
            AddConversion(Regions.KENT, NEWHAM);
            AddConversion(Regions.KENT, SURREY);
            AddConversion(Regions.KENT, TOWER_HAMLETS);
            AddConversion(Regions.KENT, THURROCK);
            AddConversion(Regions.LANCS, BLACKBURN_WITH_DARWEN);
            AddConversion(Regions.LANCS, BOLTON);
            AddConversion(Regions.LANCS, BLACKPOOL);
            AddConversion(Regions.LANCS, BURY);
            AddConversion(Regions.LANCS, CALDERDALE);
            AddConversion(Regions.LANCS, CHESHIRE_EAST);
            AddConversion(Regions.LANCS, CUMBRIA);
            AddConversion(Regions.LANCS, HALTON);
            AddConversion(Regions.LANCS, KNOWSLEY);
            AddConversion(Regions.LANCS, LANCASHIRE);
            AddConversion(Regions.LANCS, LIVERPOOL);
            AddConversion(Regions.LANCS, MANCHESTER);
            AddConversion(Regions.LANCS, NORTH_YORKSHIRE);
            AddConversion(Regions.LANCS, OLDHAM);
            AddConversion(Regions.LANCS, ROCHDALE);
            AddConversion(Regions.LANCS, SALFORD);
            AddConversion(Regions.LANCS, SEFTON);
            AddConversion(Regions.LANCS, ST_HELENS);
            AddConversion(Regions.LANCS, TRAFFORD);
            AddConversion(Regions.LANCS, TAMESIDE);
            AddConversion(Regions.LANCS, WARRINGTON);
            AddConversion(Regions.LANCS, WIGAN);
            AddConversion(Regions.LANCS, STOCKPORT);
            AddConversion(Regions.LEICS, DERBYSHIRE);
            AddConversion(Regions.LEICS, CITY_OF_LEICESTER);
            AddConversion(Regions.LEICS, LINCOLNSHIRE);
            AddConversion(Regions.LEICS, LEICESTERSHIRE);
            AddConversion(Regions.LEICS, NORTHAMPTONSHIRE);
            AddConversion(Regions.LEICS, NOTTINGHAMSHIRE);
            AddConversion(Regions.LEICS, RUTLAND);
            AddConversion(Regions.LEICS, STAFFORDSHIRE);
            AddConversion(Regions.LEICS, WARWICKSHIRE);
            AddConversion(Regions.LINCS, CAMBRIDGESHIRE);
            AddConversion(Regions.LINCS, DONCASTER);
            AddConversion(Regions.LINCS, EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.LINCS, LINCOLNSHIRE);
            AddConversion(Regions.LINCS, LEICESTERSHIRE);
            AddConversion(Regions.LINCS, NORTH_EAST_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.LINCS, NORFOLK);
            AddConversion(Regions.LINCS, NORTHAMPTONSHIRE);
            AddConversion(Regions.LINCS, NOTTINGHAMSHIRE);
            AddConversion(Regions.LINCS, CITY_OF_PETERBOROUGH);
            AddConversion(Regions.LINCS, RUTLAND);
            AddConversion(Regions.LONDON, BRACKNELL_FOREST);
            AddConversion(Regions.LONDON, BARNET);
            AddConversion(Regions.LONDON, BROMLEY);
            AddConversion(Regions.LONDON, BRENT);
            AddConversion(Regions.LONDON, CAMDEN);
            AddConversion(Regions.LONDON, CROYDON);
            AddConversion(Regions.LONDON, EALING);
            AddConversion(Regions.LONDON, ENFIELD);
            AddConversion(Regions.LONDON, EAST_SUSSEX);
            AddConversion(Regions.LONDON, ESSEX);
            AddConversion(Regions.LONDON, HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.LONDON, HARINGEY);
            AddConversion(Regions.LONDON, HILLINGDON);
            AddConversion(Regions.LONDON, HACKNEY);
            AddConversion(Regions.LONDON, HARROW);
            AddConversion(Regions.LONDON, HOUNSLOW);
            AddConversion(Regions.LONDON, ISLINGTON);
            AddConversion(Regions.LONDON, ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.LONDON, KINGSTON_UPON_THAMES);
            AddConversion(Regions.LONDON, KENT);
            AddConversion(Regions.LONDON, LAMBETH);
            AddConversion(Regions.LONDON, CITY_OF_LONDON);
            AddConversion(Regions.LONDON, LEWISHAM);
            AddConversion(Regions.LONDON, MERTON);
            AddConversion(Regions.LONDON, NEWHAM);
            AddConversion(Regions.LONDON, RICHMOND_UPON_THAMES);
            AddConversion(Regions.LONDON, SURREY);
            AddConversion(Regions.LONDON, SOUTHWARK);
            AddConversion(Regions.LONDON, SUTTON);
            AddConversion(Regions.LONDON, TOWER_HAMLETS);
            AddConversion(Regions.LONDON, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.LONDON, CITY_OF_WESTMINSTER);
            AddConversion(Regions.LONDON, WEST_SUSSEX);
            AddConversion(Regions.LONDON, WEST_SUSSEX);
            AddConversion(Regions.LONDON, WANDSWORTH);
            AddConversion(Regions.LONDON, WANDSWORTH);
            AddConversion(Regions.MANCHESTER, OLDHAM);
            AddConversion(Regions.MANCHESTER, OLDHAM);
            AddConversion(Regions.MANCHESTER, TAMESIDE);
            AddConversion(Regions.MERIONETH, CONWY);
            AddConversion(Regions.MERIONETH, DENBIGHSHIRE);
            AddConversion(Regions.MERIONETH, GWYNEDD);
            AddConversion(Regions.MERIONETH, POWYS);
            AddConversion(Regions.MIDDLESEX, BUCKINGHAMSHIRE);
            AddConversion(Regions.MIDDLESEX, BARNET);
            AddConversion(Regions.MIDDLESEX, BRENT);
            AddConversion(Regions.MIDDLESEX, CAMDEN);
            AddConversion(Regions.MIDDLESEX, EALING);
            AddConversion(Regions.MIDDLESEX, ENFIELD);
            AddConversion(Regions.MIDDLESEX, ESSEX);
            AddConversion(Regions.MIDDLESEX, HERTFORDSHIRE);
            AddConversion(Regions.MIDDLESEX, HAMMERSMITH_AND_FULHAM);
            AddConversion(Regions.MIDDLESEX, HARINGEY);
            AddConversion(Regions.MIDDLESEX, HILLINGDON);
            AddConversion(Regions.MIDDLESEX, HACKNEY);
            AddConversion(Regions.MIDDLESEX, HARROW);
            AddConversion(Regions.MIDDLESEX, HOUNSLOW);
            AddConversion(Regions.MIDDLESEX, ISLINGTON);
            AddConversion(Regions.MIDDLESEX, ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.MIDDLESEX, LAMBETH);
            AddConversion(Regions.MIDDLESEX, CITY_OF_LONDON);
            AddConversion(Regions.MIDDLESEX, NEWHAM);
            AddConversion(Regions.MIDDLESEX, RICHMOND_UPON_THAMES);
            AddConversion(Regions.MIDDLESEX, SURREY);
            AddConversion(Regions.MIDDLESEX, SOUTHWARK);
            AddConversion(Regions.MIDDLESEX, TOWER_HAMLETS);
            AddConversion(Regions.MIDDLESEX, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.MIDDLESEX, CITY_OF_WESTMINSTER);
            AddConversion(Regions.MIDDLESEX, WANDSWORTH);
            AddConversion(Regions.MONMOUTH, BLAENAU_GWENT);
            AddConversion(Regions.MONMOUTH, CARDIFF);
            AddConversion(Regions.MONMOUTH, CAERPHILLY);
            AddConversion(Regions.MONMOUTH, GLOUCESTERSHIRE);
            AddConversion(Regions.MONMOUTH, HEREFORDSHIRE);
            AddConversion(Regions.MONMOUTH, MONMOUTHSHIRE);
            AddConversion(Regions.MONMOUTH, MERTHYR_TYDFIL);
            AddConversion(Regions.MONMOUTH, NEWPORT);
            AddConversion(Regions.MONMOUTH, POWYS);
            AddConversion(Regions.MONMOUTH, RHONDDA_CYNON_TAFF);
            AddConversion(Regions.MONMOUTH, TORFAEN);
            AddConversion(Regions.MONTGOMERY, CEREDIGION);
            AddConversion(Regions.MONTGOMERY, GWYNEDD);
            AddConversion(Regions.MONTGOMERY, POWYS);
            AddConversion(Regions.MONTGOMERY, SHROPSHIRE);
            AddConversion(Regions.NORFOLK, CAMBRIDGESHIRE);
            AddConversion(Regions.NORFOLK, LINCOLNSHIRE);
            AddConversion(Regions.NORFOLK, NORFOLK);
            AddConversion(Regions.NORFOLK, SUFFOLK);
            AddConversion(Regions.NORTH_YORKSHIRE, DARLINGTON);
            AddConversion(Regions.NORTH_YORKSHIRE, MIDDLESBROUGH);
            AddConversion(Regions.NORTH_YORKSHIRE, REDCAR_AND_CLEVELAND);
            AddConversion(Regions.NORTH_YORKSHIRE, STOCKTON_ON_TEES);
            AddConversion(Regions.NORTHAMPTON, BEDFORDSHIRE);
            AddConversion(Regions.NORTHAMPTON, BUCKINGHAMSHIRE);
            AddConversion(Regions.NORTHAMPTON, CAMBRIDGESHIRE);
            AddConversion(Regions.NORTHAMPTON, LINCOLNSHIRE);
            AddConversion(Regions.NORTHAMPTON, LEICESTERSHIRE);
            AddConversion(Regions.NORTHAMPTON, MILTON_KEYNES);
            AddConversion(Regions.NORTHAMPTON, NORTHAMPTONSHIRE);
            AddConversion(Regions.NORTHAMPTON, OXFORDSHIRE);
            AddConversion(Regions.NORTHAMPTON, CITY_OF_PETERBOROUGH);
            AddConversion(Regions.NORTHAMPTON, WARWICKSHIRE);
            AddConversion(Regions.NORTHUMBERLAND, CUMBRIA);
            AddConversion(Regions.NORTHUMBERLAND, DURHAM);
            AddConversion(Regions.NORTHUMBERLAND, GATESHEAD);
            AddConversion(Regions.NORTHUMBERLAND, NORTHUMBERLAND);
            AddConversion(Regions.NORTHUMBERLAND, NORTH_TYNESIDE);
            AddConversion(Regions.NORTHUMBERLAND, NEWCASTLE_UPON_TYNE);
            AddConversion(Regions.NORTHUMBERLAND, SCOTTISH_BORDERS);
            AddConversion(Regions.NOTTS, DONCASTER);
            AddConversion(Regions.NOTTS, DERBYSHIRE);
            AddConversion(Regions.NOTTS, LINCOLNSHIRE);
            AddConversion(Regions.NOTTS, LEICESTERSHIRE);
            AddConversion(Regions.NOTTS, CITY_OF_NOTTINGHAM);
            AddConversion(Regions.NOTTS, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.NOTTS, NOTTINGHAMSHIRE);
            AddConversion(Regions.OXFORD, BUCKINGHAMSHIRE);
            AddConversion(Regions.OXFORD, GLOUCESTERSHIRE);
            AddConversion(Regions.OXFORD, NORTHAMPTONSHIRE);
            AddConversion(Regions.OXFORD, OXFORDSHIRE);
            AddConversion(Regions.OXFORD, READING);
            AddConversion(Regions.OXFORD, WEST_BERKSHIRE);
            AddConversion(Regions.OXFORD, WOKINGHAM);
            AddConversion(Regions.OXFORD, WARWICKSHIRE);
            AddConversion(Regions.PEMBROKE, CEREDIGION);
            AddConversion(Regions.PEMBROKE, CARMARTHENSHIRE);
            AddConversion(Regions.PEMBROKE, PEMBROKESHIRE);
            AddConversion(Regions.RADNOR, CEREDIGION);
            AddConversion(Regions.RADNOR, HEREFORDSHIRE);
            AddConversion(Regions.RADNOR, POWYS);
            AddConversion(Regions.RADNOR, SHROPSHIRE);
            AddConversion(Regions.RUTLAND, LINCOLNSHIRE);
            AddConversion(Regions.RUTLAND, LEICESTERSHIRE);
            AddConversion(Regions.RUTLAND, NORTHAMPTONSHIRE);
            AddConversion(Regions.RUTLAND, RUTLAND);
            AddConversion(Regions.SHROPS, CHESHIRE_EAST);
            AddConversion(Regions.SHROPS, HEREFORDSHIRE);
            AddConversion(Regions.SHROPS, POWYS);
            AddConversion(Regions.SHROPS, STAFFORDSHIRE);
            AddConversion(Regions.SHROPS, SHROPSHIRE);
            AddConversion(Regions.SHROPS, WORCESTERSHIRE);
            AddConversion(Regions.SHROPS, TELFORD_AND_WREKIN);
            AddConversion(Regions.SHROPS, WREXHAM);
            AddConversion(Regions.SOMERSET, BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.SOMERSET, BRISTOL);
            AddConversion(Regions.SOMERSET, DEVON);
            AddConversion(Regions.SOMERSET, DORSET);
            AddConversion(Regions.SOMERSET, NORTH_SOMERSET);
            AddConversion(Regions.SOMERSET, SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.SOMERSET, SOMERSET);
            AddConversion(Regions.SOMERSET, WILTSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, BRADFORD);
            AddConversion(Regions.SOUTH_YORKSHIRE, BARNSLEY);
            AddConversion(Regions.SOUTH_YORKSHIRE, CALDERDALE);
            AddConversion(Regions.SOUTH_YORKSHIRE, CHESHIRE_EAST);
            AddConversion(Regions.SOUTH_YORKSHIRE, CUMBRIA);
            AddConversion(Regions.SOUTH_YORKSHIRE, DONCASTER);
            AddConversion(Regions.SOUTH_YORKSHIRE, DURHAM);
            AddConversion(Regions.SOUTH_YORKSHIRE, DERBYSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, KIRKLEES);
            AddConversion(Regions.SOUTH_YORKSHIRE, LANCASHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, LEEDS);
            AddConversion(Regions.SOUTH_YORKSHIRE, MANCHESTER);
            AddConversion(Regions.SOUTH_YORKSHIRE, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, NOTTINGHAMSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, NORTH_YORKSHIRE);
            AddConversion(Regions.SOUTH_YORKSHIRE, OLDHAM);
            AddConversion(Regions.SOUTH_YORKSHIRE, ROCHDALE);
            AddConversion(Regions.SOUTH_YORKSHIRE, ROTHERHAM);
            AddConversion(Regions.SOUTH_YORKSHIRE, SHEFFIELD);
            AddConversion(Regions.SOUTH_YORKSHIRE, TAMESIDE);
            AddConversion(Regions.SOUTH_YORKSHIRE, WAKEFIELD);
            AddConversion(Regions.SOUTH_YORKSHIRE, YORK);
            AddConversion(Regions.STAFFS, BIRMINGHAM);
            AddConversion(Regions.STAFFS, CHESHIRE_EAST);
            AddConversion(Regions.STAFFS, DERBYSHIRE);
            AddConversion(Regions.STAFFS, DUDLEY);
            AddConversion(Regions.STAFFS, SANDWELL);
            AddConversion(Regions.STAFFS, STAFFORDSHIRE);
            AddConversion(Regions.STAFFS, SHROPSHIRE);
            AddConversion(Regions.STAFFS, CITY_OF_STOKE_ON_TRENT);
            AddConversion(Regions.STAFFS, SOUTH_TYNESIDE);
            AddConversion(Regions.STAFFS, WALSALL);
            AddConversion(Regions.STAFFS, CITY_OF_WOLVERHAMPTON);
            AddConversion(Regions.STAFFS, WARWICKSHIRE);
            AddConversion(Regions.STAFFS, WORCESTERSHIRE);
            AddConversion(Regions.SUFFOLK, CAMBRIDGESHIRE);
            AddConversion(Regions.SUFFOLK, ESSEX);
            AddConversion(Regions.SUFFOLK, NORFOLK);
            AddConversion(Regions.SUFFOLK, SUFFOLK);
            AddConversion(Regions.SURREY, BRACKNELL_FOREST);
            AddConversion(Regions.SURREY, BROMLEY);
            AddConversion(Regions.SURREY, CROYDON);
            AddConversion(Regions.SURREY, EAST_SUSSEX);
            AddConversion(Regions.SURREY, HAMPSHIRE);
            AddConversion(Regions.SURREY, HOUNSLOW);
            AddConversion(Regions.SURREY, ROYAL_BOROUGH_OF_KENSINGTON_AND_CHELSEA);
            AddConversion(Regions.SURREY, KINGSTON_UPON_THAMES);
            AddConversion(Regions.SURREY, KENT);
            AddConversion(Regions.SURREY, LAMBETH);
            AddConversion(Regions.SURREY, CITY_OF_LONDON);
            AddConversion(Regions.SURREY, LEWISHAM);
            AddConversion(Regions.SURREY, MERTON);
            AddConversion(Regions.SURREY, RICHMOND_UPON_THAMES);
            AddConversion(Regions.SURREY, SURREY);
            AddConversion(Regions.SURREY, SOUTHWARK);
            AddConversion(Regions.SURREY, SUTTON);
            AddConversion(Regions.SURREY, TOWER_HAMLETS);
            AddConversion(Regions.SURREY, WINDSOR_AND_MAIDENHEAD);
            AddConversion(Regions.SURREY, CITY_OF_WESTMINSTER);
            AddConversion(Regions.SURREY, WEST_SUSSEX);
            AddConversion(Regions.SURREY, WANDSWORTH);
            AddConversion(Regions.SUSSEX, CITY_OF_BRIGHTON_AND_HOVE);
            AddConversion(Regions.SUSSEX, EAST_SUSSEX);
            AddConversion(Regions.SUSSEX, HAMPSHIRE);
            AddConversion(Regions.SUSSEX, KENT);
            AddConversion(Regions.SUSSEX, SURREY);
            AddConversion(Regions.SUSSEX, WEST_SUSSEX);
            AddConversion(Regions.WARWICK, BIRMINGHAM);
            AddConversion(Regions.WARWICK, BUCKINGHAMSHIRE);
            AddConversion(Regions.WARWICK, COVENTRY);
            AddConversion(Regions.WARWICK, GLOUCESTERSHIRE);
            AddConversion(Regions.WARWICK, LEICESTERSHIRE);
            AddConversion(Regions.WARWICK, NORTHAMPTONSHIRE);
            AddConversion(Regions.WARWICK, OXFORDSHIRE);
            AddConversion(Regions.WARWICK, STAFFORDSHIRE);
            AddConversion(Regions.WARWICK, SOLIHULL);
            AddConversion(Regions.WARWICK, WARWICKSHIRE);
            AddConversion(Regions.WARWICK, WORCESTERSHIRE);
            AddConversion(Regions.WEST_GLAMORGAN, SWANSEA);
            AddConversion(Regions.WEST_YORKSHIRE, BRADFORD);
            AddConversion(Regions.WEST_YORKSHIRE, BARNSLEY);
            AddConversion(Regions.WEST_YORKSHIRE, CALDERDALE);
            AddConversion(Regions.WEST_YORKSHIRE, CHESHIRE_EAST);
            AddConversion(Regions.WEST_YORKSHIRE, CUMBRIA);
            AddConversion(Regions.WEST_YORKSHIRE, DONCASTER);
            AddConversion(Regions.WEST_YORKSHIRE, DURHAM);
            AddConversion(Regions.WEST_YORKSHIRE, DERBYSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, KIRKLEES);
            AddConversion(Regions.WEST_YORKSHIRE, LANCASHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, LEEDS);
            AddConversion(Regions.WEST_YORKSHIRE, MANCHESTER);
            AddConversion(Regions.WEST_YORKSHIRE, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, NOTTINGHAMSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, NORTH_YORKSHIRE);
            AddConversion(Regions.WEST_YORKSHIRE, OLDHAM);
            AddConversion(Regions.WEST_YORKSHIRE, ROCHDALE);
            AddConversion(Regions.WEST_YORKSHIRE, ROTHERHAM);
            AddConversion(Regions.WEST_YORKSHIRE, SHEFFIELD);
            AddConversion(Regions.WEST_YORKSHIRE, TAMESIDE);
            AddConversion(Regions.WEST_YORKSHIRE, WAKEFIELD);
            AddConversion(Regions.WEST_YORKSHIRE, YORK);
            AddConversion(Regions.WESTMORLAND, CUMBRIA);
            AddConversion(Regions.WESTMORLAND, DURHAM);
            AddConversion(Regions.WESTMORLAND, LANCASHIRE);
            AddConversion(Regions.WILTS, BATH_AND_NORTH_EAST_SOMERSET);
            AddConversion(Regions.WILTS, DORSET);
            AddConversion(Regions.WILTS, GLOUCESTERSHIRE);
            AddConversion(Regions.WILTS, HAMPSHIRE);
            AddConversion(Regions.WILTS, OXFORDSHIRE);
            AddConversion(Regions.WILTS, SWINDON);
            AddConversion(Regions.WILTS, SOUTH_GLOUCESTERSHIRE);
            AddConversion(Regions.WILTS, SOMERSET);
            AddConversion(Regions.WILTS, WEST_BERKSHIRE);
            AddConversion(Regions.WILTS, WILTSHIRE);
            AddConversion(Regions.WORCESTER, BIRMINGHAM);
            AddConversion(Regions.WORCESTER, DUDLEY);
            AddConversion(Regions.WORCESTER, GLOUCESTERSHIRE);
            AddConversion(Regions.WORCESTER, HEREFORDSHIRE);
            AddConversion(Regions.WORCESTER, SANDWELL);
            AddConversion(Regions.WORCESTER, STAFFORDSHIRE);
            AddConversion(Regions.WORCESTER, SHROPSHIRE);
            AddConversion(Regions.WORCESTER, SOLIHULL);
            AddConversion(Regions.WORCESTER, WARWICKSHIRE);
            AddConversion(Regions.WORCESTER, WORCESTERSHIRE);
            AddConversion(Regions.YORKS, BRADFORD);
            AddConversion(Regions.YORKS, BARNSLEY);
            AddConversion(Regions.YORKS, CALDERDALE);
            AddConversion(Regions.YORKS, CUMBRIA);
            AddConversion(Regions.YORKS, DARLINGTON);
            AddConversion(Regions.YORKS, DONCASTER);
            AddConversion(Regions.YORKS, DURHAM);
            AddConversion(Regions.YORKS, DERBYSHIRE);
            AddConversion(Regions.YORKS, EAST_RIDING_OF_YORKSHIRE);
            AddConversion(Regions.YORKS, CITY_OF_KINGSTON_UPON_HULL);
            AddConversion(Regions.YORKS, KIRKLEES);
            AddConversion(Regions.YORKS, LANCASHIRE);
            AddConversion(Regions.YORKS, LEEDS);
            AddConversion(Regions.YORKS, MANCHESTER);
            AddConversion(Regions.YORKS, MIDDLESBROUGH);
            AddConversion(Regions.YORKS, NORTH_LINCOLNSHIRE);
            AddConversion(Regions.YORKS, NOTTINGHAMSHIRE);
            AddConversion(Regions.YORKS, NORTH_YORKSHIRE);
            AddConversion(Regions.YORKS, OLDHAM);
            AddConversion(Regions.YORKS, REDCAR_AND_CLEVELAND);
            AddConversion(Regions.YORKS, ROCHDALE);
            AddConversion(Regions.YORKS, ROTHERHAM);
            AddConversion(Regions.YORKS, STOCKTON_ON_TEES);
            AddConversion(Regions.YORKS, SHEFFIELD);
            AddConversion(Regions.YORKS, TAMESIDE);
            AddConversion(Regions.YORKS, WAKEFIELD);
            AddConversion(Regions.YORKS, YORK);
        }

        private static void AddConversion(Region region, County county)
        {
            List<County> counties;
 	        if(CONVERSIONS.ContainsKey(region))
                counties = CONVERSIONS[region];
            else
            {
                counties = new List<County>();
                CONVERSIONS.Add(region, counties);
            }
            counties.Add(county);
        }
    }
}
