//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAnalyzer.Windows.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralSettingsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralSettingsUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTAnalyzer.Windows.UserControls.GeneralSettingsUI", typeof(GeneralSettingsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkAllowEmptyLocations_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkAllowEmptyLocations.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkAllowEmptyLocations_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkAllowEmptyLocations.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=46}.
        /// </summary>
        internal static System.Drawing.Point chkAllowEmptyLocations_Location {
            get {
                object obj = ResourceManager.GetObject("chkAllowEmptyLocations.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=192, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkAllowEmptyLocations_Size {
            get {
                object obj = ResourceManager.GetObject("chkAllowEmptyLocations.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int chkAllowEmptyLocations_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkAllowEmptyLocations.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Empty Values In Locations (*).
        /// </summary>
        internal static string chkAllowEmptyLocations_Text {
            get {
                return ResourceManager.GetString("chkAllowEmptyLocations.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkHideIgnoredDuplicates_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkHideIgnoredDuplicates.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkHideIgnoredDuplicates_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkHideIgnoredDuplicates.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=282}.
        /// </summary>
        internal static System.Drawing.Point chkHideIgnoredDuplicates_Location {
            get {
                object obj = ResourceManager.GetObject("chkHideIgnoredDuplicates.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=140, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkHideIgnoredDuplicates_Size {
            get {
                object obj = ResourceManager.GetObject("chkHideIgnoredDuplicates.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 35.
        /// </summary>
        internal static int chkHideIgnoredDuplicates_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkHideIgnoredDuplicates.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Ignored Duplicates.
        /// </summary>
        internal static string chkHideIgnoredDuplicates_Text {
            get {
                return ResourceManager.GetString("chkHideIgnoredDuplicates.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkIgnoreFactTypeWarnings_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkIgnoreFactTypeWarnings.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkIgnoreFactTypeWarnings_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkIgnoreFactTypeWarnings.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=190}.
        /// </summary>
        internal static System.Drawing.Point chkIgnoreFactTypeWarnings_Location {
            get {
                object obj = ResourceManager.GetObject("chkIgnoreFactTypeWarnings.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=244, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkIgnoreFactTypeWarnings_Size {
            get {
                object obj = ResourceManager.GetObject("chkIgnoreFactTypeWarnings.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 31.
        /// </summary>
        internal static int chkIgnoreFactTypeWarnings_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkIgnoreFactTypeWarnings.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Unknown/Custom Fact Type Warnings.
        /// </summary>
        internal static string chkIgnoreFactTypeWarnings_Text {
            get {
                return ResourceManager.GetString("chkIgnoreFactTypeWarnings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkIncludeAlternateFacts_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkIncludeAlternateFacts.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkIncludeAlternateFacts_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkIncludeAlternateFacts.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=305}.
        /// </summary>
        internal static System.Drawing.Point chkIncludeAlternateFacts_Location {
            get {
                object obj = ResourceManager.GetObject("chkIncludeAlternateFacts.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=148, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkIncludeAlternateFacts_Size {
            get {
                object obj = ResourceManager.GetObject("chkIncludeAlternateFacts.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 36.
        /// </summary>
        internal static int chkIncludeAlternateFacts_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkIncludeAlternateFacts.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Alternate Facts (*).
        /// </summary>
        internal static string chkIncludeAlternateFacts_Text {
            get {
                return ResourceManager.GetString("chkIncludeAlternateFacts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkMultiAncestor_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkMultiAncestor.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkMultiAncestor_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkMultiAncestor.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=236}.
        /// </summary>
        internal static System.Drawing.Point chkMultiAncestor_Location {
            get {
                object obj = ResourceManager.GetObject("chkMultiAncestor.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=243, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkMultiAncestor_Size {
            get {
                object obj = ResourceManager.GetObject("chkMultiAncestor.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 33.
        /// </summary>
        internal static int chkMultiAncestor_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkMultiAncestor.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ancestors who are related multiple times.
        /// </summary>
        internal static string chkMultiAncestor_Text {
            get {
                return ResourceManager.GetString("chkMultiAncestor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkMultipleFactForms_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkMultipleFactForms.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkMultipleFactForms_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkMultipleFactForms.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=69}.
        /// </summary>
        internal static System.Drawing.Point chkMultipleFactForms_Location {
            get {
                object obj = ResourceManager.GetObject("chkMultipleFactForms.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=223, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkMultipleFactForms_Size {
            get {
                object obj = ResourceManager.GetObject("chkMultipleFactForms.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 23.
        /// </summary>
        internal static int chkMultipleFactForms_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkMultipleFactForms.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Duplicates Facts in Separate Forms.
        /// </summary>
        internal static string chkMultipleFactForms_Text {
            get {
                return ResourceManager.GetString("chkMultipleFactForms.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkReverseLocations_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkReverseLocations.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkReverseLocations_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkReverseLocations.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=144}.
        /// </summary>
        internal static System.Drawing.Point chkReverseLocations_Location {
            get {
                object obj = ResourceManager.GetObject("chkReverseLocations.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=190, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkReverseLocations_Size {
            get {
                object obj = ResourceManager.GetObject("chkReverseLocations.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 27.
        /// </summary>
        internal static int chkReverseLocations_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkReverseLocations.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files use Country First Locations (*).
        /// </summary>
        internal static string chkReverseLocations_Text {
            get {
                return ResourceManager.GetString("chkReverseLocations.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkShowWorldEvents_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkShowWorldEvents.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkShowWorldEvents_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkShowWorldEvents.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=167}.
        /// </summary>
        internal static System.Drawing.Point chkShowWorldEvents_Location {
            get {
                object obj = ResourceManager.GetObject("chkShowWorldEvents.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=243, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkShowWorldEvents_Size {
            get {
                object obj = ResourceManager.GetObject("chkShowWorldEvents.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 29.
        /// </summary>
        internal static int chkShowWorldEvents_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkShowWorldEvents.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show World Events on the &quot;On This Day&quot; tab.
        /// </summary>
        internal static string chkShowWorldEvents_Text {
            get {
                return ResourceManager.GetString("chkShowWorldEvents.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkSkipFixingLocations_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkSkipFixingLocations.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkSkipFixingLocations_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkSkipFixingLocations.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=259}.
        /// </summary>
        internal static System.Drawing.Point chkSkipFixingLocations_Location {
            get {
                object obj = ResourceManager.GetObject("chkSkipFixingLocations.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=181, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkSkipFixingLocations_Size {
            get {
                object obj = ResourceManager.GetObject("chkSkipFixingLocations.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 34.
        /// </summary>
        internal static int chkSkipFixingLocations_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkSkipFixingLocations.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Fixing Locations on Load (*).
        /// </summary>
        internal static string chkSkipFixingLocations_Text {
            get {
                return ResourceManager.GetString("chkSkipFixingLocations.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkTreatFemaleAsUnknown_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkTreatFemaleAsUnknown.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkTreatFemaleAsUnknown_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkTreatFemaleAsUnknown.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=213}.
        /// </summary>
        internal static System.Drawing.Point chkTreatFemaleAsUnknown_Location {
            get {
                object obj = ResourceManager.GetObject("chkTreatFemaleAsUnknown.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkTreatFemaleAsUnknown_Size {
            get {
                object obj = ResourceManager.GetObject("chkTreatFemaleAsUnknown.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 32.
        /// </summary>
        internal static int chkTreatFemaleAsUnknown_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkTreatFemaleAsUnknown.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat Female Surnames in Brackets as Unknown (*).
        /// </summary>
        internal static string chkTreatFemaleAsUnknown_Text {
            get {
                return ResourceManager.GetString("chkTreatFemaleAsUnknown.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkUseAlias_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkUseAlias.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkUseAlias_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkUseAlias.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=121}.
        /// </summary>
        internal static System.Drawing.Point chkUseAlias_Location {
            get {
                object obj = ResourceManager.GetObject("chkUseAlias.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=155, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkUseAlias_Size {
            get {
                object obj = ResourceManager.GetObject("chkUseAlias.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 25.
        /// </summary>
        internal static int chkUseAlias_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkUseAlias.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Alias In Name Displays.
        /// </summary>
        internal static string chkUseAlias_Text {
            get {
                return ResourceManager.GetString("chkUseAlias.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkUseBaptisms_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkUseBaptisms.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=0}.
        /// </summary>
        internal static System.Drawing.Point chkUseBaptisms_Location {
            get {
                object obj = ResourceManager.GetObject("chkUseBaptisms.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=244, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkUseBaptisms_Size {
            get {
                object obj = ResourceManager.GetObject("chkUseBaptisms.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int chkUseBaptisms_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkUseBaptisms.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Baptism/Christening Date If No Birth Date.
        /// </summary>
        internal static string chkUseBaptisms_Text {
            get {
                return ResourceManager.GetString("chkUseBaptisms.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkUseBurials_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkUseBurials.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkUseBurials_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkUseBurials.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=23}.
        /// </summary>
        internal static System.Drawing.Point chkUseBurials_Location {
            get {
                object obj = ResourceManager.GetObject("chkUseBurials.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=236, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkUseBurials_Size {
            get {
                object obj = ResourceManager.GetObject("chkUseBurials.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 22.
        /// </summary>
        internal static int chkUseBurials_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkUseBurials.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Burial/Cremation Date If No Death Date.
        /// </summary>
        internal static string chkUseBurials_Text {
            get {
                return ResourceManager.GetString("chkUseBurials.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point errorProvider1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("errorProvider1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=399}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=203, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) This option requires a GEDCOM reload.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=45,Y=94}.
        /// </summary>
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=181, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose Birth Minimum Parental Age (*).
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=92}.
        /// </summary>
        internal static System.Drawing.Point upDownAge_Location {
            get {
                object obj = ResourceManager.GetObject("upDownAge.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=35, Height=20}.
        /// </summary>
        internal static System.Drawing.Size upDownAge_Size {
            get {
                object obj = ResourceManager.GetObject("upDownAge.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        internal static int upDownAge_TabIndex {
            get {
                object obj = ResourceManager.GetObject("upDownAge.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
