//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAnalyzer.Windows.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MappingSettingsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MappingSettingsUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTAnalyzer.Windows.UserControls.MappingSettingsUI", typeof(MappingSettingsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=282,Y=23}.
        /// </summary>
        internal static System.Drawing.Point btnBrowseFolder_Location {
            get {
                object obj = ResourceManager.GetObject("btnBrowseFolder.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=23}.
        /// </summary>
        internal static System.Drawing.Size btnBrowseFolder_Size {
            get {
                object obj = ResourceManager.GetObject("btnBrowseFolder.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int btnBrowseFolder_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnBrowseFolder.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string btnBrowseFolder_Text {
            get {
                return ResourceManager.GetString("btnBrowseFolder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkIncludePartialGeocoded_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkIncludePartialGeocoded.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode chkIncludePartialGeocoded_ImeMode {
            get {
                object obj = ResourceManager.GetObject("chkIncludePartialGeocoded.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=97}.
        /// </summary>
        internal static System.Drawing.Point chkIncludePartialGeocoded_Location {
            get {
                object obj = ResourceManager.GetObject("chkIncludePartialGeocoded.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=279, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkIncludePartialGeocoded_Size {
            get {
                object obj = ResourceManager.GetObject("chkIncludePartialGeocoded.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int chkIncludePartialGeocoded_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkIncludePartialGeocoded.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Locations With Partial Match Status On Maps.
        /// </summary>
        internal static string chkIncludePartialGeocoded_Text {
            get {
                return ResourceManager.GetString("chkIncludePartialGeocoded.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool ckbHideScaleBar_AutoSize {
            get {
                object obj = ResourceManager.GetObject("ckbHideScaleBar.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode ckbHideScaleBar_ImeMode {
            get {
                object obj = ResourceManager.GetObject("ckbHideScaleBar.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=74}.
        /// </summary>
        internal static System.Drawing.Point ckbHideScaleBar_Location {
            get {
                object obj = ResourceManager.GetObject("ckbHideScaleBar.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=17}.
        /// </summary>
        internal static System.Drawing.Size ckbHideScaleBar_Size {
            get {
                object obj = ResourceManager.GetObject("ckbHideScaleBar.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int ckbHideScaleBar_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ckbHideScaleBar.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Scale Bar.
        /// </summary>
        internal static string ckbHideScaleBar_Text {
            get {
                return ResourceManager.GetString("ckbHideScaleBar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool ckbUseParishBoundaries_AutoSize {
            get {
                object obj = ResourceManager.GetObject("ckbUseParishBoundaries.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=51}.
        /// </summary>
        internal static System.Drawing.Point ckbUseParishBoundaries_Location {
            get {
                object obj = ResourceManager.GetObject("ckbUseParishBoundaries.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=179, Height=17}.
        /// </summary>
        internal static System.Drawing.Size ckbUseParishBoundaries_Size {
            get {
                object obj = ResourceManager.GetObject("ckbUseParishBoundaries.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int ckbUseParishBoundaries_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ckbUseParishBoundaries.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display British Parish Boundaries.
        /// </summary>
        internal static string ckbUseParishBoundaries_Text {
            get {
                return ResourceManager.GetString("ckbUseParishBoundaries.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point errorProvider1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("errorProvider1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=147,Y=17}.
        /// </summary>
        internal static System.Drawing.Point folderBrowserDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("folderBrowserDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=9}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Maps Location:.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=121}.
        /// </summary>
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=82, Height=13}.
        /// </summary>
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google API Key.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=137}.
        /// </summary>
        internal static System.Drawing.Point txtGoogleAPI_Location {
            get {
                object obj = ResourceManager.GetObject("txtGoogleAPI.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=300, Height=20}.
        /// </summary>
        internal static System.Drawing.Size txtGoogleAPI_Size {
            get {
                object obj = ResourceManager.GetObject("txtGoogleAPI.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int txtGoogleAPI_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtGoogleAPI.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtMapPath_Enabled {
            get {
                object obj = ResourceManager.GetObject("txtMapPath.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=25}.
        /// </summary>
        internal static System.Drawing.Point txtMapPath_Location {
            get {
                object obj = ResourceManager.GetObject("txtMapPath.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=270, Height=20}.
        /// </summary>
        internal static System.Drawing.Size txtMapPath_Size {
            get {
                object obj = ResourceManager.GetObject("txtMapPath.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int txtMapPath_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtMapPath.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
