//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;
using System.IO;

namespace FTAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class FileHandling : global::System.Configuration.ApplicationSettingsBase {
        
        private static FileHandling defaultInstance = ((FileHandling)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FileHandling())));
        
        public static FileHandling Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadWithFilters {
            get {
                return ((bool)(this["LoadWithFilters"]));
            }
            set {
                this["LoadWithFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RetryFailedLines {
            get {
                return ((bool)(this["RetryFailedLines"]));
            }
            set {
                this["RetryFailedLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConvertDiacritics {
            get {
                return ((bool)(this["ConvertDiacritics"]));
            }
            set {
                this["ConvertDiacritics"] = value;
            }
        }

        public override void Save()
        {
            ClearUserConfigFile();
            base.Save();
        }

        public static void ClearUserConfigFile()
        {
            //Touch each setting
            foreach (SettingsProperty property in FileHandling.Default.Properties)
            {
                if (property.DefaultValue != FileHandling.Default[property.Name])
                    FileHandling.Default[property.Name] = FileHandling.Default[property.Name];
            }

            //Delete the user.config file
            var config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoaming);
            var userConfigPath = config.FilePath;
            try
            {
                if (File.Exists(userConfigPath) == true)
                    File.Delete(userConfigPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception thrown while deleting user.config : {0}", ex.ToString());
            }
        }

    }
}
