//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FTAnalyzer.Utilities;
using System;
using System.Configuration;
using System.IO;

namespace FTAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class MappingSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MappingSettings defaultInstance = ((MappingSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MappingSettings())));
        
        public static MappingSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomMapPath {
            get {
                return ((string)(this["CustomMapPath"]));
            }
            set {
                this["CustomMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseParishBoundaries {
            get {
                return ((bool)(this["UseParishBoundaries"]));
            }
            set {
                this["UseParishBoundaries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideScaleBar {
            get {
                return ((bool)(this["HideScaleBar"]));
            }
            set {
                this["HideScaleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludePartials {
            get {
                return ((bool)(this["IncludePartials"]));
            }
            set {
                this["IncludePartials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleAPI {
            get {
                return ((string)(this["GoogleAPI"]));
            }
            set {
                this["GoogleAPI"] = value;
            }
        }

        public override void Save()
        {
            try
            {
                ClearUserConfigFile();
                base.Save();
            }
            catch (ConfigurationErrorsException)
            {
                var config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoaming);
                var userConfigPath = config.FilePath;
                UIHelpers.ShowMessage($"Failed to write configuration file. Check you have write permission to file\n\n{userConfigPath}");
            }
        }

        public static void ClearUserConfigFile()
        {
            //Touch each setting
            foreach (SettingsProperty property in MappingSettings.Default.Properties)
            {
                if (property.DefaultValue != MappingSettings.Default[property.Name])
                    MappingSettings.Default[property.Name] = MappingSettings.Default[property.Name];
            }

            //Delete the user.config file
            var config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoaming);
            var userConfigPath = config.FilePath;
            try
            {
                if (File.Exists(userConfigPath) == true)
                    File.Delete(userConfigPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception thrown while deleting user.config : {0}", ex.ToString());
            }
        }
    }
}
