//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTAnalyzer.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: .
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to show the facts for both the individual and their possible match..
        /// </summary>
        internal static string Hints_Duplicates {
            get {
                return ResourceManager.GetString("Hints_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to show a list of facts for the selected family..
        /// </summary>
        internal static string Hints_Family {
            get {
                return ResourceManager.GetString("Hints_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to show a list of facts for the selected individual..
        /// </summary>
        internal static string Hints_Individual {
            get {
                return ResourceManager.GetString("Hints_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift double click to search Lives of First World War life story page..
        /// </summary>
        internal static string Hints_LivesOfFirstWorldWar {
            get {
                return ResourceManager.GetString("Hints_LivesOfFirstWorldWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to show a list of individuals and families at the selected location..
        /// </summary>
        internal static string Hints_Location {
            get {
                return ResourceManager.GetString("Hints_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Births where you could limit the date range. .
        /// </summary>
        internal static string Hints_Loose_Births {
            get {
                return ResourceManager.GetString("Hints_Loose_Births", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Deaths where you could limit the date range. .
        /// </summary>
        internal static string Hints_Loose_Deaths {
            get {
                return ResourceManager.GetString("Hints_Loose_Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to show a list of individuals with the selected occupation..
        /// </summary>
        internal static string Hints_Occupation {
            get {
                return ResourceManager.GetString("Hints_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to show a list of individuals and families with the selected surname. Click links for one name study..
        /// </summary>
        internal static string Hints_Surname {
            get {
                return ResourceManager.GetString("Hints_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented Yet. Coming Soon in a future version..
        /// </summary>
        internal static string NotYet {
            get {
                return ResourceManager.GetString("NotYet", resourceCulture);
            }
        }
    }
}
