//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;
using System.IO;

namespace FTAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class NonGedcomDate : global::System.Configuration.ApplicationSettingsBase {
        
        private static NonGedcomDate defaultInstance = ((NonGedcomDate)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NonGedcomDate())));
        
        public static NonGedcomDate Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseNonGedcomDates {
            get {
                return ((bool)(this["UseNonGedcomDates"]));
            }
            set {
                this["UseNonGedcomDates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd/MM/yyyy")]
        public string DateFormat {
            get {
                return ((string)(this["DateFormat"]));
            }
            set {
                this["DateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\d{1,2}\\/\\d{1,2}\\/\\d{4}$")]
        public string Regex {
            get {
                return ((string)(this["Regex"]));
            }
            set {
                this["Regex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/")]
        public string Separator {
            get {
                return ((string)(this["Separator"]));
            }
            set {
                this["Separator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FormatSelected {
            get {
                return ((int)(this["FormatSelected"]));
            }
            set {
                this["FormatSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }

        public override void Save()
        {
            ClearUserConfigFile();
            base.Save();
        }

        public static void ClearUserConfigFile()
        {
            //Touch each setting
            foreach (SettingsProperty property in NonGedcomDate.Default.Properties)
            {
                if (property.DefaultValue != NonGedcomDate.Default[property.Name])
                    NonGedcomDate.Default[property.Name] = NonGedcomDate.Default[property.Name];
            }

            //Delete the user.config file
            var config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoaming);
            var userConfigPath = config.FilePath;
            try
            {
                if (File.Exists(userConfigPath) == true)
                    File.Delete(userConfigPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception thrown while deleting user.config : {0}", ex.ToString());
            }
        }

    }
}
