//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class NonGedcomDate : global::System.Configuration.ApplicationSettingsBase {
        
        private static NonGedcomDate defaultInstance = ((NonGedcomDate)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NonGedcomDate())));
        
        public static NonGedcomDate Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseNonGedcomDates {
            get {
                return ((bool)(this["UseNonGedcomDates"]));
            }
            set {
                this["UseNonGedcomDates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd/mm/yyyy")]
        public string NonGedcomDateFormat {
            get {
                return ((string)(this["NonGedcomDateFormat"]));
            }
            set {
                this["NonGedcomDateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\d{1,2}\\/\\d{1,2}\\/\\d{4}$")]
        public string NonGedcomDateRegex {
            get {
                return ((string)(this["NonGedcomDateRegex"]));
            }
            set {
                this["NonGedcomDateRegex"] = value;
            }
        }
    }
}
